# Generated by Django 5.2.17 on 2026-09-30 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(default='cash', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('path', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_through', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=160)),
                ('detail', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('csrf', models.CharField(max_length=80)),
                ('expires', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('expiry', models.DateField(null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.document')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='cashier', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('shift_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('bonus_basis', models.CharField(default='store', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cashaccount')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.store'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase_order', 'Замовлення постачальнику'), ('receipt', 'Надходження'), ('opening', 'Початкові залишки'), ('sale', 'Продаж'), ('customer_return', 'Повернення покупця'), ('supplier_return', 'Повернення постачальнику'), ('transfer', 'Переміщення'), ('writeoff', 'Списання'), ('inventory', 'Інвентаризація'), ('production', 'Виробництво'), ('payment', 'Оплата боргу'), ('expense', 'Витрата'), ('cash_opening', 'Початкові кошти'), ('payroll', 'Нарахування зарплати'), ('payroll_payment', 'Виплата зарплати / аванс'), ('customer_order', 'Замовлення покупця')], max_length=24)),
                ('status', models.CharField(default='draft', max_length=12)),
                ('date', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(null=True)),
                ('reversed_at', models.DateTimeField(null=True)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=80, unique=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.cashaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.employee')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.counterparty')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.voucher')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.cashshift')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_reversal', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.stocklot')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='erp.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_reversal', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cashaccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to='erp.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('lot', models.CharField(blank=True, max_length=80)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.document')),
                ('reference_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.voucherline')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse'),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('shift_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bonus_percent', models.DecimalField(decimal_places=3, max_digits=7)),
                ('bonus_basis', models.CharField(max_length=20)),
                ('basis_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('accrued', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('note', models.TextField(blank=True)),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.cashshift')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.employee')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.voucher')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='account_name_in_store'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='warehouse_name_in_store'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['store', 'date', 'status'], name='erp_voucher_store_i_ccb1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['kind', 'status'], name='erp_voucher_kind_c24a9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product', 'code'), name='stock_lot_key'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='stock_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='one_work_shift_per_employee_day'),
        ),
    ]
