# Generated by Django 5.2.17 on 2026-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('until', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='voucher',
            name='kind',
            field=models.CharField(choices=[('purchase_order', 'Замовлення постачальнику'), ('receipt', 'Надходження'), ('opening', 'Початкові залишки'), ('sale', 'Продаж'), ('customer_return', 'Повернення покупця'), ('supplier_return', 'Повернення постачальнику'), ('transfer', 'Переміщення'), ('writeoff', 'Списання'), ('inventory', 'Інвентаризація'), ('production', 'Виробництво'), ('payment', 'Оплата боргу'), ('expense', 'Витрата'), ('cash_opening', 'Початкові кошти'), ('payroll', 'Нарахування зарплати'), ('payroll_payment', 'Виплата зарплати / аванс'), ('customer_order', 'Замовлення покупця'), ('debt_opening', 'Початкова заборгованість'), ('cash_transfer', 'Переміщення коштів')], max_length=24),
        ),
    ]
