# Generated by Django 5.2 on 2026-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_voucher_cash_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voucher',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
