# Generated by Django 5.2 on 2026-10-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_voucher_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default=True)),
                ('min_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.document')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.warehouse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'product'), name='assortment_key'), models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='assortment_min_nonnegative')],
            },
        ),
    ]
