# Generated by Django 5.2.17 on 2026-10-03 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_assortment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyCreateReceipt',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=16)),
                ('document_path', models.CharField(max_length=160, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_fingerprint', models.CharField(max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
