# Generated by Django 5.2.17 on 2026-10-03 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_multilot_lines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_path', models.CharField(db_index=True, max_length=160)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('source', models.CharField(max_length=80)),
                ('reason', models.CharField(max_length=500)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_path', models.CharField(max_length=160)),
                ('terms', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('scope', models.CharField(default='network', max_length=12)),
                ('reason', models.CharField(max_length=500)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stores', models.ManyToManyField(blank=True, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='erp.promotioncampaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'product'), name='campaign_product_price'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='campaign_price_positive')],
            },
        ),
    ]
