# Generated by Django 5.2.17 on 2026-10-03 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_categories(apps,schema_editor):
    Category=apps.get_model('erp','ExpenseCategory');Alias=apps.get_model('erp','ExpenseCategoryAlias');db=schema_editor.connection.alias
    for key,name in [('rent','Оренда'),('utilities','Комунальні'),('logistics','Логістика'),('service','Обслуговування'),('marketing','Маркетинг'),('tax','Податки'),('salary','Зарплата'),('other','Інше')]:
        c=Category.objects.using(db).create(id=uuid.uuid5(uuid.NAMESPACE_URL,'tsukenya:expense-category:'+key),name=name,semantic_key=key)
        Alias.objects.using(db).create(category=c,name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_payment_allocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('semantic_key', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='erp.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('planned_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('create_key', models.CharField(max_length=100, null=True, unique=True)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('mode', models.CharField(choices=[('fixed_amount', 'Постійна сума'), ('variable_amount', 'Змінна сума'), ('revenue_rate', 'Відсоток від виторгу')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('base', models.CharField(default='revenue', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.expensecategory')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.monthlybudget')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('month', 'store'), name='monthly_budget_store'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', True)), fields=('month',), name='monthly_budget_network'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.CheckConstraint(condition=models.Q(('planned_revenue__gte', 0)), name='budget_revenue_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='budget_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='budget_rate_bounds'),
        ),
        migrations.RunPython(seed_categories,migrations.RunPython.noop),
    ]
