# Generated by Django 5.2.17 on 2026-10-03 23:43

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_monthly_budgets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderControl',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='order_control', serialize=False, to='erp.voucher')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('closed_at', models.DateTimeField(null=True)),
                ('reason', models.TextField(blank=True)),
                ('expected_date', models.DateField(null=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderOperation',
            fields=[
                ('key', models.UUIDField(primary_key=True, serialize=False)),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('used', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('released', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.stocklot')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.voucherline')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('reversed_at', models.DateTimeField(null=True)),
                ('released_on_reverse', models.BooleanField(default=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_uses', to='erp.voucherline')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='erp.stockreservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['lot', 'expires_on'], name='reservation_lot_expiry'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('used'), '+', models.F('released'))), ('released__gte', 0), ('used__gte', 0)), name='reservation_quantities_valid'),
        ),
        migrations.AddConstraint(
            model_name='reservationuse',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_use_positive'),
        ),
    ]
