# Generated by Django 5.2.17 on 2026-10-03 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_order_reservations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=30)),
                ('output_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('expiry_policy', models.CharField(choices=[('unspecified', 'Не визначено'), ('components_min', 'Найраніша сировина'), ('minimum_with_shelf_life', 'Сировина та технологічний строк')], max_length=32)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_versions', to='erp.document')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('position', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='erp.document')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='erp.recipeversion')),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='recipe_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.recipeversion'),
        ),
        migrations.CreateModel(
            name='ProductionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=30)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('lot', models.CharField(blank=True, max_length=80)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.document')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_inputs', to='erp.voucher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voucher', 'product'), name='production_input_unique'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='production_input_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='recipe_product_version'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('output_quantity__gt', 0)), name='recipe_output_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.UniqueConstraint(fields=('recipe', 'product'), name='recipe_component_unique'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recipe_component_positive'),
        ),
    ]
