# Generated by Django 5.2.17 on 2026-10-04 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_recipe_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('problem', models.TextField(blank=True)),
                ('hypothesis', models.TextField(blank=True)),
                ('state', models.CharField(default='planned', max_length=16)),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('metric', models.CharField(blank=True, max_length=160)),
                ('metric_unit', models.CharField(blank=True, max_length=80)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('fact_value', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('result_summary', models.TextField(blank=True)),
                ('result_date', models.DateField(null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_initiatives', to=settings.AUTH_USER_MODEL)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='idea_project', to='erp.document')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_initiatives', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_links', to='erp.ideaproject')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_expense', to='erp.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOperation',
            fields=[
                ('key', models.UUIDField(primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.ideaproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_task', to='erp.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_links', to='erp.ideaproject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ideaproject',
            constraint=models.CheckConstraint(condition=models.Q(('planned_budget__gte', 0), ('planned_budget__isnull', True), _connector='OR'), name='initiative_budget_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ideaproject',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['planned', 'active', 'completed', 'cancelled'])), name='initiative_state_valid'),
        ),
    ]
