# Generated by Django 5.2.17 on 2026-10-04 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_managed_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShiftCreateReceipt',
            fields=[
                ('key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='workshift',
            name='one_work_shift_per_employee_day',
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(condition=models.Q(('cash_shift__isnull', False)), fields=('employee', 'date', 'cash_shift'), name='one_work_shift_per_employee_day_till'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(condition=models.Q(('cash_shift__isnull', True)), fields=('employee', 'date'), name='one_unlinked_work_shift_per_employee_day'),
        ),
        migrations.AddField(
            model_name='workshiftcreatereceipt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshiftcreatereceipt',
            name='work_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.workshift'),
        ),
    ]
