# Generated by Django 5.2.17 on 2026-10-04 02:29

import django.db.models.deletion
import server.erp.import_models
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_atomic(apps, schema_editor):
    import re
    from django.utils import timezone
    Document=apps.get_model('erp','Document');Run=apps.get_model('erp','CatalogImportRun');Row=apps.get_model('erp','CatalogImportRow')
    User=apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    alias=schema_editor.connection.alias
    query=Document.objects.using(alias).filter(path__startswith='import_runs/').order_by('path')
    for document in query.iterator(chunk_size=100):
        data=document.data
        try:
            identifier=uuid.UUID(document.path.split('/',1)[1]);owner=data['owner'];result=data['result'];entries=result['entries'];summary=result['counts']
            if type(owner) is not int or not User.objects.using(alias).filter(pk=owner).exists() or not isinstance(entries,list) or not 0<len(entries)<=1000:continue
            if not isinstance(data['payloadHash'],str) or not re.fullmatch('[0-9a-f]{64}',data['payloadHash']):continue
            if any(not isinstance(x,dict) or x.get('action') not in {'create','update'} or not isinstance(x.get('id'),str) or not re.fullmatch('[A-Za-z0-9_-]{1,120}',x['id']) or type(x.get('line')) is not int or not 0<x['line']<=1000000 or not isinstance(x.get('revision'),str) or not re.fullmatch('[0-9a-f]{64}',x['revision']) for x in entries):continue
            created=sum(x['action']=='create' for x in entries);updated=len(entries)-created
            if summary!={'created':created,'updated':updated,'errors':0}:continue
            now=timezone.now();actual=dict.fromkeys(('created','updated','skipped','conflicted','failed','invalid','pending'),0);actual.update(created=created,updated=updated)
            run,_=Run.objects.using(alias).get_or_create(id=identifier,defaults={'owner_id':owner,'mode':'atomic','file_name':'','expected_rows':len(entries),'uploaded_rows':len(entries),'metadata_hash':data['payloadHash'],'input_hash':data['payloadHash'],'status':'completed','phase':'finished','phase_done':len(entries),'phase_total':len(entries),'counts':actual,'planned':{'create':created,'update':updated,'skip':0},'started_at':None,'finished_at':None})
            Row.objects.using(alias).bulk_create([Row(run_id=run.pk,ordinal=index+1,line=x['line'],status='created' if x['action']=='create' else 'updated',action=x['action'],product_path='products/'+x['id'],revision=x['revision'],current_revision=x['revision'],input_hash='') for index,x in enumerate(entries)],batch_size=200,ignore_conflicts=True)
        except (ValueError,KeyError,TypeError,AttributeError):continue


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_multiple_daily_work_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='chunked', max_length=8)),
                ('file_name', models.CharField(blank=True, max_length=250)),
                ('expected_rows', models.PositiveIntegerField()),
                ('uploaded_rows', models.PositiveIntegerField(default=0)),
                ('input_bytes', models.PositiveIntegerField(default=0)),
                ('metadata_hash', models.CharField(max_length=64)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('upload_hash', models.CharField(blank=True, max_length=64)),
                ('plan_material', models.CharField(blank=True, max_length=64)),
                ('default_markup', models.CharField(blank=True, max_length=32)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('generic_as', models.CharField(blank=True, max_length=8)),
                ('pricing_config', models.JSONField(default=dict)),
                ('pricing_revision', models.CharField(blank=True, max_length=64)),
                ('plan_revision', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='uploading', max_length=32)),
                ('phase', models.CharField(default='uploading', max_length=16)),
                ('phase_done', models.PositiveIntegerField(default=0)),
                ('phase_total', models.PositiveIntegerField(default=0)),
                ('catalog_cursor', models.CharField(blank=True, max_length=160)),
                ('row_cursor', models.PositiveIntegerField(default=0)),
                ('counts', models.JSONField(default=server.erp.import_models.counts)),
                ('planned', models.JSONField(default=server.erp.import_models.planned)),
                ('create_receipt', models.JSONField(default=dict)),
                ('seal_receipt', models.JSONField(default=dict)),
                ('apply_receipt', models.JSONField(default=dict)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('error', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('line', models.PositiveIntegerField(null=True)),
                ('input', models.JSONField(default=dict)),
                ('input_hash', models.CharField(max_length=64)),
                ('name_hash', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='uploaded', max_length=16)),
                ('action', models.CharField(blank=True, max_length=8)),
                ('product_path', models.CharField(blank=True, max_length=160)),
                ('revision', models.CharField(blank=True, max_length=64)),
                ('current_revision', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('effective_revision', models.CharField(blank=True, max_length=64)),
                ('error', models.JSONField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='erp.catalogimportrun')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogImportIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_path', models.CharField(max_length=160)),
                ('name_hash', models.CharField(blank=True, max_length=64)),
                ('revision', models.CharField(max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.catalogimportrun')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogImportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('receipt', models.JSONField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.catalogimportrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='catalogimportrun',
            index=models.Index(fields=['owner', '-created_at'], name='import_owner_history'),
        ),
        migrations.AddIndex(
            model_name='catalogimportrun',
            index=models.Index(fields=['status', 'lease_until'], name='import_worker_queue'),
        ),
        migrations.AddIndex(
            model_name='catalogimportrow',
            index=models.Index(fields=['run', 'line'], name='import_input_line'),
        ),
        migrations.AddIndex(
            model_name='catalogimportrow',
            index=models.Index(fields=['run', 'name_hash'], name='import_input_name'),
        ),
        migrations.AddIndex(
            model_name='catalogimportrow',
            index=models.Index(fields=['run', 'barcode'], name='import_input_barcode'),
        ),
        migrations.AddIndex(
            model_name='catalogimportrow',
            index=models.Index(fields=['run', 'status', 'ordinal'], name='import_pending_rows'),
        ),
        migrations.AddConstraint(
            model_name='catalogimportrow',
            constraint=models.UniqueConstraint(fields=('run', 'ordinal'), name='import_row_ordinal'),
        ),
        migrations.AddIndex(
            model_name='catalogimportindex',
            index=models.Index(fields=['run', 'name_hash'], name='import_catalog_name'),
        ),
        migrations.AddConstraint(
            model_name='catalogimportindex',
            constraint=models.UniqueConstraint(fields=('run', 'product_path'), name='import_catalog_path'),
        ),
        migrations.AddConstraint(
            model_name='catalogimportchunk',
            constraint=models.UniqueConstraint(fields=('run', 'offset'), name='import_chunk_offset'),
        ),
        migrations.RunPython(backfill_atomic,migrations.RunPython.noop),
    ]
