# Generated by Django 5.2.17 on 2026-10-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_catalog_import_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('intent_hash', models.CharField(max_length=64)),
                ('report_hash', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=20)),
                ('checks_version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(default=dict)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['-recorded_at'], name='reconcile_run_recorded')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('check_name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('expected', models.TextField(null=True)),
                ('actual', models.TextField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='erp.reconciliationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'ordinal'), name='reconcile_finding_ordinal')],
            },
        ),
    ]
