# Generated by Django 5.2.17 on 2026-10-04 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_reconciliation_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHeartbeat',
            fields=[
                ('instance', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=40)),
                ('seen_at', models.DateTimeField()),
                ('stopped', models.BooleanField(default=False)),
                ('release', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['service', '-seen_at'], name='service_heartbeat_seen')],
            },
        ),
    ]
