# Generated by Django 5.2.17 on 2026-10-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_service_heartbeats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCreateReceipt',
            fields=[
                ('key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=16)),
                ('object_id', models.PositiveBigIntegerField()),
                ('store_id_snapshot', models.PositiveBigIntegerField(null=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('original', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
