# Generated by Django 5.2.17 on 2026-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_entity_create_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacycreatereceipt',
            name='original',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
