# Generated by Django 5.2.17 on 2026-10-04 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_legacy_create_original_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningCreateReceipt',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('resource', models.CharField(choices=[('category', 'Стаття'), ('monthly_budget', 'Місячний бюджет')], max_length=20)),
                ('target_uuid', models.UUIDField(editable=False)),
                ('month', models.DateField(editable=False, null=True)),
                ('request_fingerprint', models.CharField(editable=False, max_length=64)),
                ('created_fingerprint', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.monthlybudget')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.expensecategory')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('budget__isnull', True), ('month__isnull', True), ('resource', 'category'), ('store__isnull', True)), models.Q(('category__isnull', True), ('month__isnull', False), ('resource', 'monthly_budget')), _connector='OR'), name='planning_receipt_resource')],
            },
        ),
    ]
