# Generated by Django 5.2.17 on 2026-10-05 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_trading_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShiftActionReceipt',
            fields=[
                ('key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=5)),
                ('store_id_snapshot', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('original', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cashshift')),
            ],
        ),
    ]
