# Generated by Django 5.2.17 on 2026-10-05 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_cash_shift_action_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingActionReceipt',
            fields=[
                ('key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('setting', models.CharField(max_length=20)),
                ('fingerprint', models.CharField(max_length=64)),
                ('original', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
