# Generated by Django 5.2.17 on 2026-10-05 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def install(apps,schema_editor):
    from server.erp.migration_helpers.contact_tasks_0030_sql import install as apply
    apply(schema_editor.connection)

def uninstall(apps,schema_editor):
    from server.erp.migration_helpers.contact_tasks_0030_sql import uninstall as remove
    remove(schema_editor.connection)


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_customer_report_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('note', models.CharField(blank=True, max_length=4000)),
                ('due_on', models.DateField(null=True)),
                ('status', models.CharField(default='todo', max_length=16)),
                ('archived', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contact_tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.counterparty')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTaskOperation',
            fields=[
                ('key', models.UUIDField(primary_key=True, serialize=False)),
                ('store_id_snapshot', models.PositiveBigIntegerField()),
                ('customer_id_snapshot', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('fingerprint', models.CharField(max_length=64)),
                ('original', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='erp.contacttask')),
            ],
        ),
        migrations.AddIndex(
            model_name='contacttask',
            index=models.Index(fields=['customer', 'store', 'status', 'due_on'], name='contact_customer_queue'),
        ),
        migrations.AddIndex(
            model_name='contacttask',
            index=models.Index(fields=['store', 'status', 'due_on'], name='contact_store_queue'),
        ),
        migrations.AddIndex(
            model_name='contacttask',
            index=models.Index(fields=['assignee', 'store', 'status'], name='contact_assigned_queue'),
        ),
        migrations.AddConstraint(
            model_name='contacttask',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['todo', 'doing', 'done', 'cancelled'])), name='contact_task_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='contacttask',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='contact_task_revision_positive'),
        ),
        migrations.AddIndex(
            model_name='contacttaskoperation',
            index=models.Index(fields=['task', 'created_at'], name='contact_task_history'),
        ),
        migrations.RunPython(install,uninstall),
    ]
