/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/reports/abc': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          store?: number;
          aThreshold?: string;
          bThreshold?: string;
          q?: string;
          class?: '' | 'A' | 'B' | 'C' | 'unclassified';
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Звіт доступних магазинів або повний CSV вибірки */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Report'];
          };
        };
        /** @description Некоректні умови */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Сеанс завершився */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Недостатньо поточних прав */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/reports/abc/export.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          store?: number;
          aThreshold?: string;
          bThreshold?: string;
          q?: string;
          class?: '' | 'A' | 'B' | 'C' | 'unclassified';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Звіт доступних магазинів або повний CSV вибірки */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/csv': string;
          };
        };
        /** @description Некоректні умови */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Сеанс завершився */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Недостатньо поточних прав */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ClassSummary: {
      count: number;
      netRevenue: string;
      share: string | null;
    };
    Summary: {
      productCount: number;
      positiveCount: number;
      zeroCount: number;
      negativeCount: number;
      mixedUnitCount: number;
      hiddenCount: number;
      netRevenue: string;
      positivePoolRevenue: string;
      negativeRevenue: string;
      netCogs: string;
      grossProfit: string;
      classes: {
        A: components['schemas']['ClassSummary'];
        B: components['schemas']['ClassSummary'];
        C: components['schemas']['ClassSummary'];
        unclassified: components['schemas']['ClassSummary'];
      };
    };
    Row: {
      product: string;
      name: string;
      unit: string | null;
      quantity: string | null;
      unitConflicted: boolean;
      hiddenCurrent: boolean;
      netRevenue: string;
      netCogs: string;
      grossProfit: string;
      /** @enum {string} */
      classification: 'A' | 'B' | 'C' | 'unclassified';
      share: string | null;
      cumulativeBefore: string | null;
      cumulativeAfter: string | null;
    };
    Report: {
      /** @constant */
      contract: 'trading-abc-v1';
      /** Format: date */
      from: string;
      /** Format: date */
      to: string;
      store: number | null;
      scopeName: string;
      aThreshold: string;
      bThreshold: string;
      /** @constant */
      basis: 'net_revenue';
      /** @constant */
      reversalPolicy: 'kyiv_reversed_at';
      /** @constant */
      snapshot: 'current';
      /** @constant */
      tiePolicy: 'before_group';
      /** @constant */
      captionBasis: 'first_contributing_line';
      snapshotNotice: string;
      /** Format: date-time */
      generatedAt: string;
      summary: components['schemas']['Summary'];
      items: components['schemas']['Row'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
      q: string;
      /** @enum {string} */
      class: '' | 'A' | 'B' | 'C' | 'unclassified';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
