/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/promotions/recovery/context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current campaign policy/read */
    get: {
      parameters: {
        query: {
          operation: string;
          target?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Confirmed current policy or original outcome */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CampaignRecoveryContext'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/promotions/recovery/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current campaign policy/read */
    get: {
      parameters: {
        query: {
          id: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Confirmed current policy or original outcome */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CampaignRecoveryCurrent'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/promotions/recovery/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Creator-bound immutable intent read */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CampaignRecoveryEnvelope'];
        };
      };
      responses: {
        /** @description Confirmed current policy or original outcome */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CampaignRecoveryAcknowledgement'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/promotions/recovery/execute': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Atomic existing campaign action; compact confirmation, never a current baseline */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CampaignRecoveryEnvelope'];
        };
      };
      responses: {
        /** @description Confirmed current policy or original outcome */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CampaignRecoveryAcknowledgement'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CampaignInput: {
      name: string;
      /** Format: date */
      startsOn: string;
      /** Format: date */
      endsOn: string;
      active: boolean;
      /** @enum {string} */
      scope: 'network' | 'stores';
      stores: number[];
      prices: {
        product: string;
        price: string;
      }[];
      reason: string;
    };
    CampaignRecoveryEnvelope: {
      /** Format: uuid */
      key: string;
      /** @enum {string} */
      operation: 'create' | 'update' | 'archive';
      target: string | null;
      request:
        | {
            name: string;
            /** Format: date */
            startsOn: string;
            /** Format: date */
            endsOn: string;
            active: boolean;
            /** @enum {string} */
            scope: 'network' | 'stores';
            stores: number[];
            prices: {
              product: string;
              price: string;
            }[];
            reason: string;
            /** Format: uuid */
            idempotencyKey?: string;
            revision?: number;
          }
        | {
            revision: number;
            reason: string;
          };
    };
    CampaignRecoveryAcknowledgement: {
      confirmed: boolean;
      /** Format: uuid */
      key: string;
      /** @enum {string} */
      operation: 'create' | 'update' | 'archive';
      target: string | null;
      requestHash: string;
      /** @enum {string} */
      outcome: 'created' | 'saved' | 'archived' | 'unresolved';
    };
    CampaignRecoveryPolicy: {
      /** @constant */
      role: 'owner';
      storeId: null;
      /** @constant */
      networkOwner: true;
      canWrite: boolean;
    };
    CampaignRecoveryContext: {
      /** @enum {string} */
      operation: 'create' | 'update' | 'archive';
      target: string | null;
      exists: boolean | null;
      editing: components['schemas']['CampaignRecoveryPolicy'];
    };
    Campaign: {
      name: string;
      /** Format: date */
      startsOn: string;
      /** Format: date */
      endsOn: string;
      active: boolean;
      /** @enum {string} */
      scope: 'network' | 'stores';
      stores: number[];
      prices: {
        product: string;
        price: string;
        name: string;
      }[];
      reason: string;
      /** Format: uuid */
      id: string;
      revision: number;
      archived: boolean;
      /** @enum {string} */
      status: 'active' | 'scheduled' | 'expired' | 'disabled' | 'archived';
      author: string;
    };
    CampaignRecoveryCurrent: {
      campaign: components['schemas']['Campaign'];
      editing: components['schemas']['CampaignRecoveryPolicy'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
