/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/catalog/recovery/execute': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Creator-bound frozen request. Identity is a CSRF-protected READ ONLY RR read; false is unresolved, never authorship or known absence. Execute delegates unchanged business services under LedgerLock. */
    post: operations['catalogRecoveryExecute'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/recovery/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Creator-bound frozen request. Identity is a CSRF-protected READ ONLY RR read; false is unresolved, never authorship or known absence. Execute delegates unchanged business services under LedgerLock. */
    post: operations['catalogRecoveryIdentity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/recovery/context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['catalogRecoveryContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CatalogRecoveryEnvelope: {
      /** Format: uuid */
      key: string;
      /** @enum {string} */
      operation:
        | 'product_create'
        | 'product_update'
        | 'product_visibility'
        | 'product_delete'
        | 'reference_create'
        | 'reference_commit';
      target: string | null;
      store: number | null;
      request: {
        [key: string]: string | number | boolean | null;
      };
    };
    CatalogRecoveryAcknowledgement: {
      confirmed: boolean;
      /** Format: uuid */
      key: string;
      /** @enum {string} */
      operation:
        | 'product_create'
        | 'product_update'
        | 'product_visibility'
        | 'product_delete'
        | 'reference_create'
        | 'reference_commit';
      target: string | null;
      requestHash: string;
      /** @enum {string} */
      outcome: 'created' | 'saved' | 'deleted' | 'committed' | 'unresolved';
    };
    CatalogRecoveryContext: {
      /** @enum {string} */
      operation:
        | 'product_create'
        | 'product_update'
        | 'product_visibility'
        | 'product_delete'
        | 'reference_create'
        | 'reference_commit';
      target: string | null;
      store: number | null;
      exists: boolean | null;
      editing: {
        /** @enum {string} */
        role: 'owner' | 'manager' | 'warehouse';
        storeId: number | null;
        networkOwner: boolean;
        /** @constant */
        canWrite: true;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  catalogRecoveryExecute: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CatalogRecoveryEnvelope'];
      };
    };
    responses: {
      /** @description Compact initial result; no current revision or Product DTO. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogRecoveryAcknowledgement'];
        };
      };
      /** @description Validation refused; only initial rolled-back live response may include bound write_rejected proof. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Current role/store/activity refuses access. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Collision or stale revision; unknown later response never retires the first intent. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  catalogRecoveryIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CatalogRecoveryEnvelope'];
      };
    };
    responses: {
      /** @description Compact initial result; no current revision or Product DTO. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogRecoveryAcknowledgement'];
        };
      };
      /** @description Validation refused; only initial rolled-back live response may include bound write_rejected proof. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Current role/store/activity refuses access. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Collision or stale revision; unknown later response never retires the first intent. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  catalogRecoveryContext: {
    parameters: {
      query: {
        operation:
          | 'product_create'
          | 'product_update'
          | 'product_visibility'
          | 'product_delete'
          | 'reference_create'
          | 'reference_commit';
        target?: string | null;
        store?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh resource authorization and scalar existence, READ ONLY RR. Unknown and duplicate query keys refused. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogRecoveryContext'];
        };
      };
    };
  };
}
