/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/catalog/references/page': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          field: components['schemas']['Field'];
          q?: string;
          state?: 'active' | 'archived' | 'merged';
          parentId?: string | null;
          parentType?: string | null;
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Fresh READ ONLY snapshot; no business writes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Page'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/references/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['DetailsRequest'];
        };
      };
      responses: {
        /** @description Fresh READ ONLY snapshot; no business writes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Details'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/references/impact-page': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ImpactPageRequest'];
        };
      };
      responses: {
        /** @description Fresh READ ONLY snapshot; no business writes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ImpactPage'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/portal/catalogue.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Complete filtered schema-v1 CSV (transportCSV1 marker unchanged). Fresh read-only snapshot with frozen Kyiv day/config/store, bounded scalar batches, private pre-header disk preparation. Cost/markup columns redacted for cashier. includeHidden=true compatibility is owner-only both states and cannot combine with visibility or filters. No page/limit parameters; unknown or repeated parameters refuse. */
    get: {
      parameters: {
        query?: {
          q?: string;
          type?: string;
          category?: string;
          pack?: string;
          promotion?: '' | 'yes' | 'no';
          visibility?: 'active' | 'hidden';
          store?: number;
          includeHidden?: 'true' | 'false';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All matching rows, including readonly derived metadata; no truncated success. */
        200: {
          headers: {
            'Content-Length'?: number;
            'Cache-Control'?: 'private, no-store';
            [name: string]: unknown;
          };
          content: {
            'text/csv': string;
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Explicit request, authorization, stale snapshot or resource refusal; no partial success. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    Field: 'type' | 'category' | 'pack' | 'size' | 'unit';
    Reference: components['schemas']['ReferenceManagedItem'];
    Query: {
      field: components['schemas']['Field'];
      q: string;
      /** @enum {string} */
      state: 'active' | 'archived' | 'merged';
      parentId: string | null;
      parentType: string | null;
    };
    Selected: {
      field: components['schemas']['Field'];
      id?: string;
      value: string;
      parentType?: string;
    };
    DetailsRequest: {
      items: components['schemas']['Selected'][];
      product?: string;
    };
    Resolved: {
      selected: components['schemas']['Selected'];
      item: components['schemas']['ReferenceManagedItem'] | null;
      resolved: boolean;
    };
    Details: {
      /** @constant */
      contract: 'catalog-reference-details-v1';
      items: components['schemas']['Resolved'][];
      canEdit: boolean;
    };
    Page: {
      /** @constant */
      contract: 'catalog-reference-page-v1';
      items: components['schemas']['ReferenceManagedItem'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
      query: components['schemas']['Query'];
      canEdit: boolean;
      csrf: string;
    };
    /** @enum {string} */
    ImpactSection: 'products' | 'references' | 'coalesced' | 'blocked';
    ImpactPageRequest: {
      request: components['schemas']['ReferenceMutation'];
      snapshot: string;
      section: components['schemas']['ImpactSection'];
      page: number;
    };
    ImpactRow:
      | {
          id: string;
          name: string;
        }
      | {
          before: components['schemas']['ReferenceManagedItem'];
          after: components['schemas']['ReferenceManagedItem'];
        }
      | {
          sourceId: string;
          targetId: string;
          value: string;
        }
      | {
          id: string;
          reason: string;
        };
    ImpactPage: {
      /** @constant */
      contract: 'catalog-reference-impact-page-v1';
      snapshot: string;
      section: components['schemas']['ImpactSection'];
      items: components['schemas']['ImpactRow'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
    };
    /** @enum {string} */
    ReferenceField: 'type' | 'category' | 'pack' | 'size' | 'unit';
    ReferenceManagedItem: {
      id: string;
      field: components['schemas']['ReferenceField'];
      value: string;
      parentType: string;
      /** @enum {string} */
      state: 'active' | 'archived' | 'merged';
      parentId: string | null;
      mergedInto: string | null;
      revision: string;
    };
    Error: {
      error: string;
      code?: string;
    };
    ReferenceMutation: {
      sourceId: string;
      revision: string;
      /** @enum {string} */
      operation: 'rename' | 'merge' | 'archive' | 'restore';
      value?: string;
      targetId?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
