/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/crm/contact-tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          customer?: string;
          store?: string;
          status?: string;
          archived?: string;
          assignee?: string;
          q?: string;
          dueFrom?: string;
          dueTo?: string;
          overdue?: string;
          page?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Page'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Create'];
        };
      };
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Acknowledgement'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crm/contact-tasks/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Current'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Update'];
        };
      };
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Acknowledgement'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/crm/contact-tasks/{id}/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: string;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['History'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crm/contact-tasks/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['IdentityRequest'];
        };
      };
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Identity'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crm/contact-task-context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          id?: string;
          customer?: string;
          store?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Context'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crm/contact-task-assignees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          store?: string;
          q?: string;
          page?: string;
          id?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Fresh scoped read or creator-bound acknowledgement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Assignees'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Terms: {
      title: string;
      note: string;
      due_on: string | null;
      assignee: number | null;
      /** @enum {string} */
      status: 'todo' | 'doing' | 'done' | 'cancelled';
      archived: boolean;
    };
    Task: {
      /** Format: uuid */
      id: string;
      customer: number;
      store: number;
      revision: number;
      terms: components['schemas']['Terms'];
      customerName: string;
      customerActive: boolean;
      storeName: string;
      assigneeName: string | null;
      assigneeActive: boolean | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      completedAt: string | null;
    };
    Create: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      request_key: string;
      customer: number;
      store: number;
      terms: components['schemas']['Terms'];
    };
    Update: {
      /** Format: uuid */
      request_key: string;
      revision: number;
      terms: components['schemas']['Terms'];
    };
    Original: {
      /** Format: uuid */
      id: string;
      customer: number;
      store: number;
      revision: number;
      terms: components['schemas']['Terms'];
    };
    Acknowledgement: {
      /** @enum {string} */
      resource: 'contact_task';
      /** Format: uuid */
      request_key: string;
      /** @enum {string} */
      action: 'create' | 'update';
      original: components['schemas']['Original'];
    };
    Current: {
      /** @enum {string} */
      resource: 'contact_task';
      record: components['schemas']['Task'];
      permissions: {
        canEdit: boolean;
      };
    };
    Page: {
      items: components['schemas']['Task'][];
      total: number;
      page: number;
      pages: number;
      summary: {
        todo: number;
        doing: number;
        done: number;
        cancelled: number;
        overdue: number;
      };
      scope: {
        store: number | null;
        /** Format: date */
        today: string;
      };
      canEdit: boolean;
    };
    Context: {
      /** @enum {string} */
      resource: 'contact_task';
      id: string | null;
      customer: number;
      store: number;
      /** @enum {string} */
      role: 'owner' | 'manager' | 'accountant';
      storeId: number | null;
      canEdit: boolean;
      /** @description Target existence for authorization only; never creator receipt confirmation or revision baseline. */
      exists: boolean;
    };
    IdentityRequest: {
      /** @enum {string} */
      action: 'create' | 'update';
      /** Format: uuid */
      id: string;
      request: components['schemas']['Create'] | components['schemas']['Update'];
    };
    Identity:
      | {
          /** @enum {boolean} */
          confirmed: true;
          /** @enum {string} */
          resource: 'contact_task';
          /** Format: uuid */
          request_key: string;
          /** @enum {string} */
          action: 'create' | 'update';
          original: components['schemas']['Original'];
        }
      | {
          /** @enum {boolean} */
          confirmed: false;
          /** @enum {string} */
          resource: 'contact_task';
          /** Format: uuid */
          request_key: string;
          /** @enum {string} */
          action: 'create' | 'update';
        };
    History: {
      items: {
        /** Format: uuid */
        request_key: string;
        actor: string;
        /** @enum {string} */
        action: 'create' | 'update';
        /** Format: date-time */
        at: string;
        revision: number;
        terms: components['schemas']['Terms'];
      }[];
      total: number;
      page: number;
      pages: number;
      /** @enum {string} */
      resource: 'contact_task_history';
      /** Format: uuid */
      id: string;
    };
    Assignees: {
      items: {
        id: number;
        name: string;
      }[];
      total: number;
      page: number;
      pages: number;
      store: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
