/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/crm/customers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listCustomers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crm/customers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['customerProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Customer: {
      id: number;
      name: string;
      phone: string;
      email: string;
      notes: string;
      active: boolean;
    };
    CustomerPage: {
      items: components['schemas']['Customer'][];
      total: number;
      page: number;
      pages: number;
      canEdit: boolean;
    };
    CustomerPurchases: {
      checks: number;
      gross: string;
      returned: string;
      net: string;
      averageCheck: string | null;
      /** Format: date */
      first: string | null;
      /** Format: date */
      last: string | null;
      /** @enum {unknown} */
      segment: 'none' | 'single' | 'repeat';
    };
    CustomerDebt: {
      outstanding: string;
      overdue: string;
      documents: number;
      overdueDocuments: number;
      unknownDueDocuments: number;
    };
    CustomerProfile: {
      customer: components['schemas']['Customer'];
      scope: {
        store: number | null;
        /** Format: date */
        today: string;
        /** @constant */
        basis: 'current';
      };
      purchases: components['schemas']['CustomerPurchases'];
      debt: components['schemas']['CustomerDebt'] | null;
      canEdit: boolean;
    };
    Error: {
      error: string;
      code?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listCustomers: {
    parameters: {
      query?: {
        store?: number;
        q?: string;
        active?: '' | 'yes' | 'no';
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current role-scoped data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerPage'];
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session or role unavailable */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  customerProfile: {
    parameters: {
      query?: {
        store?: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current role-scoped data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerProfile'];
        };
      };
      /** @description Invalid parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Session or role unavailable */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
