/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/documents/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Поточний дозволений стан документа. Секції читаються окремими обмеженими сторінками. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Header'];
          };
        };
        /** @description Некоректний запит */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Сеанс завершено */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Доступ змінився */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/documents/{id}/rows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          section: components['schemas']['Section'];
          page?: number;
          limit?: 10 | 30;
        };
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Поточний дозволений стан документа. Секції читаються окремими обмеженими сторінками. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Page'];
          };
        };
        /** @description Некоректний запит */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Сеанс завершено */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Доступ змінився */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    Section:
      | 'lines'
      | 'stock_movements'
      | 'cash_movements'
      | 'allocations'
      | 'payroll_calculation'
      | 'production_components'
      | 'order_lines'
      | 'reservations';
    /** @enum {string} */
    Action:
      | 'edit'
      | 'post'
      | 'delete'
      | 'reverse'
      | 'receipt'
      | 'sale'
      | 'customer_return'
      | 'supplier_return'
      | 'use_advance'
      | 'refund_advance'
      | 'pay_debt'
      | 'receipt_pricing'
      | 'order_expire'
      | 'order_close'
      | 'order_date'
      | 'order_reserve';
    Caption: {
      id: number;
      name: string;
    };
    Order: {
      /** @enum {string} */
      state: 'draft' | 'approved' | 'partial' | 'fulfilled' | 'closed' | 'cancelled';
      revision: number;
      canManage: boolean;
      expectedDate: string | null;
      minimumAmount: string | null;
    };
    Production: {
      source: string | null;
      version: number | null;
      outputQuantity: string | null;
      unit: string | null;
      plannedOutput: string | null;
      actualOutput: string | null;
      lossQuantity: string | null;
      overrunQuantity: string | null;
      materialCost: string | null;
      expiry: string | null;
      expirySource: string | null;
      varianceReason: string | null;
      expiryReason: string | null;
      expiryApprovedBy: string | null;
    };
    Document: {
      id: number;
      number: string;
      /** @enum {string} */
      kind:
        | 'purchase_order'
        | 'receipt'
        | 'opening'
        | 'sale'
        | 'customer_return'
        | 'supplier_return'
        | 'transfer'
        | 'writeoff'
        | 'inventory'
        | 'production'
        | 'payment'
        | 'advance_allocation'
        | 'payment_refund'
        | 'expense'
        | 'cash_opening'
        | 'payroll'
        | 'payroll_payment'
        | 'customer_order'
        | 'debt_opening'
        | 'cash_transfer'
        | 'cash_difference';
      /** @enum {string} */
      status: 'draft' | 'posted' | 'reversed';
      date: string;
      store: components['schemas']['Caption'];
      warehouse: components['schemas']['Caption'] | null;
      target: components['schemas']['Caption'] | null;
      party: components['schemas']['Caption'] | null;
      employee: components['schemas']['Caption'] | null;
      account: components['schemas']['Caption'] | null;
      shift: number | null;
      reference: number | null;
      revision: number;
      total: string;
      cost: string | null;
      note: string;
      createdBy: string;
      createdAt: string;
      postedAt: string | null;
      fiscalRef: string;
      expenseScope: ('network' | 'store') | null;
      outstanding: string | null;
      unallocated: string | null;
      order: components['schemas']['Order'] | null;
      production: components['schemas']['Production'] | null;
      actions: components['schemas']['Action'][];
    };
    Line: {
      id: number;
      lineKey: string;
      referenceLine: number | null;
      product: string;
      name: string;
      unit: string;
      quantity: string;
      price: string;
      amount: string;
      cost: string | null;
      lot: string;
      expiry: string | null;
      originKnown: boolean | null;
      remaining: string | null;
      remainingAmount: string | null;
    };
    StockMovement: {
      id: number;
      warehouse: components['schemas']['Caption'];
      product: string;
      lot: string;
      line: number | null;
      quantity: string;
      value: string | null;
      reversal: boolean;
    };
    CashMovement: {
      id: number;
      account: components['schemas']['Caption'];
      amount: string;
      reversal: boolean;
    };
    Allocation: {
      id: number;
      source: number;
      number: string;
      amount: string;
    };
    PayrollCalculation: {
      id: number;
      workShift: number;
      date: string;
      cashShift: number | null;
      rate: string;
      units: string;
      baseAmount: string;
      percent: string;
      basisAmount: string;
      accrued: string;
    };
    ProductionComponent: {
      id: number;
      product: string;
      name: string;
      unit: string;
      expectedQuantity: string;
      quantity: string;
      lot: string;
    };
    OrderLine: {
      id: number;
      name: string;
      unit: string;
      quantity: string;
      fulfilled: string;
      remaining: string;
      reserved: string;
    };
    Reservation: {
      id: number;
      line: number;
      name: string;
      unit: string;
      lot: number;
      code: string;
      lotExpiry: string | null;
      owner: string;
      createdAt: string;
      expiresOn: string;
      expiresAt: string;
      quantity: string;
      used: string;
      released: string;
      available: string;
      active: boolean;
    };
    Header: {
      /** @enum {string} */
      contract: 'document-detail-v1';
      context: {
        document: number;
        /** @enum {string} */
        role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
        scopeStore: number | null;
        store: number;
        readAt: string;
      };
      document: components['schemas']['Document'];
      sections: {
        key: components['schemas']['Section'];
        total: number;
      }[];
    };
    Page: {
      /** @enum {string} */
      contract: 'document-detail-v1';
      context: {
        document: number;
        /** @enum {string} */
        role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
        scopeStore: number | null;
        store: number;
        readAt: string;
      };
      document: components['schemas']['Document'];
      sections: {
        key: components['schemas']['Section'];
        total: number;
      }[];
      page: {
        section: components['schemas']['Section'];
        page: number;
        pages: number;
        /** @enum {integer} */
        limit: 10 | 30;
        total: number;
        items: (
          | components['schemas']['Line']
          | components['schemas']['StockMovement']
          | components['schemas']['CashMovement']
          | components['schemas']['Allocation']
          | components['schemas']['PayrollCalculation']
          | components['schemas']['ProductionComponent']
          | components['schemas']['OrderLine']
          | components['schemas']['Reservation']
        )[];
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
