/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/finance/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['financeAccounts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/finance/debts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['financeDebts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/finance/advances': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['financeAdvances'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/finance/ledger': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['financeLedger'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/finance/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['financeDocuments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    FinancePolicy: {
      /** @enum {string} */
      role: 'owner' | 'manager' | 'accountant';
      store: number | null;
      documentKinds: (
        | 'payment'
        | 'advance_allocation'
        | 'payment_refund'
        | 'expense'
        | 'cash_opening'
        | 'debt_opening'
        | 'cash_transfer'
        | 'cash_difference'
      )[];
      createKinds: (
        | 'payment'
        | 'advance_allocation'
        | 'payment_refund'
        | 'expense'
        | 'cash_opening'
        | 'debt_opening'
        | 'cash_transfer'
      )[];
      canManageAccounts: boolean;
    };
    Account: {
      id: number;
      store: number;
      storeName: string;
      name: string;
      /** @enum {string} */
      kind: 'cash' | 'bank' | 'terminal';
      balance: string;
      revision: string | null;
    };
    Debt: {
      id: number;
      store: number;
      storeName: string;
      number: string;
      /** @enum {string} */
      kind: 'sale' | 'receipt';
      /** @enum {string} */
      originalKind: 'sale' | 'receipt' | 'debt_opening';
      /** Format: date */
      date: string;
      party: number | null;
      partyName: string;
      total: string;
      amount: string;
      dueDate: string;
      overdue: boolean;
    };
    Advance: {
      id: number;
      store: number;
      storeName: string;
      number: string;
      /** Format: date */
      date: string;
      party: number;
      partyName: string;
      /** @enum {string} */
      direction: 'customer' | 'supplier';
      unallocated: string;
    };
    LedgerEntry: {
      id: number;
      store: number;
      storeName: string;
      voucher: number;
      number: string;
      /** Format: date */
      date: string;
      account: number;
      accountName: string;
      /** @enum {string} */
      kind:
        | 'purchase_order'
        | 'receipt'
        | 'opening'
        | 'sale'
        | 'customer_return'
        | 'supplier_return'
        | 'transfer'
        | 'writeoff'
        | 'inventory'
        | 'production'
        | 'payment'
        | 'advance_allocation'
        | 'payment_refund'
        | 'expense'
        | 'cash_opening'
        | 'payroll'
        | 'payroll_payment'
        | 'customer_order'
        | 'debt_opening'
        | 'cash_transfer'
        | 'cash_difference';
      amount: string;
      note: string;
      reversal: boolean;
    };
    FinanceDocument: {
      id: number;
      store: number;
      storeName: string;
      number: string;
      /** @enum {string} */
      kind:
        | 'payment'
        | 'advance_allocation'
        | 'payment_refund'
        | 'expense'
        | 'cash_opening'
        | 'debt_opening'
        | 'cash_transfer'
        | 'cash_difference';
      /** @enum {string} */
      status: 'draft' | 'posted' | 'reversed';
      /** Format: date */
      date: string;
      party: number | null;
      partyName: string;
      total: string;
      revision: number;
    };
    AccountsQuery: {
      q: string;
      store: number | null;
    };
    Accounts: {
      items: components['schemas']['Account'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['FinancePolicy'];
      query: components['schemas']['AccountsQuery'];
    };
    DebtsQuery: {
      q: string;
      store: number | null;
      party: number | null;
      from: string;
      to: string;
      due_from: string;
      due_to: string;
      /** @enum {string} */
      status: '' | 'overdue' | 'not_overdue';
    };
    Debts: {
      items: components['schemas']['Debt'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['FinancePolicy'];
      query: components['schemas']['DebtsQuery'];
      totals: {
        owedToUs: string;
        owedByUs: string;
      };
    };
    AdvancesQuery: {
      q: string;
      store: number | null;
      party: number | null;
    };
    Advances: {
      items: components['schemas']['Advance'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['FinancePolicy'];
      query: components['schemas']['AdvancesQuery'];
      totals: {
        customer: string;
        supplier: string;
      };
    };
    LedgerQuery: {
      q: string;
      store: number | null;
      account: number | null;
      from: string;
      to: string;
    };
    Ledger: {
      items: components['schemas']['LedgerEntry'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['FinancePolicy'];
      query: components['schemas']['LedgerQuery'];
    };
    DocumentsQuery: {
      store: number | null;
      /** @enum {string} */
      status: '' | 'draft' | 'posted' | 'reversed';
    };
    Documents: {
      items: components['schemas']['FinanceDocument'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['FinancePolicy'];
      query: components['schemas']['DocumentsQuery'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  financeAccounts: {
    parameters: {
      query?: {
        q?: string;
        store?: number | null;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped READ ONLY RR page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Accounts'];
        };
      };
    };
  };
  financeDebts: {
    parameters: {
      query?: {
        q?: string;
        store?: number | null;
        party?: number | null;
        from?: string;
        to?: string;
        due_from?: string;
        due_to?: string;
        status?: '' | 'overdue' | 'not_overdue';
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped READ ONLY RR page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Debts'];
        };
      };
    };
  };
  financeAdvances: {
    parameters: {
      query?: {
        q?: string;
        store?: number | null;
        party?: number | null;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped READ ONLY RR page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Advances'];
        };
      };
    };
  };
  financeLedger: {
    parameters: {
      query?: {
        q?: string;
        store?: number | null;
        account?: number | null;
        from?: string;
        to?: string;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped READ ONLY RR page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ledger'];
        };
      };
    };
  };
  financeDocuments: {
    parameters: {
      query?: {
        store?: number | null;
        status?: '' | 'draft' | 'posted' | 'reversed';
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped READ ONLY RR page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Documents'];
        };
      };
    };
  };
}
