/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Session */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Session'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          q?: string;
          type?: string;
          category?: string;
          pack?: string;
          promotion?: string;
          page?: number;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ProductPage */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProductPage'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** @description Create a product. Nonempty dictionary fields must exist in references; category must belong to type. Legacy imports retain their text compatibility. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ProductCreate'];
        };
      };
      responses: {
        /** @description Product */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Product'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Product */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Product'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            revision: string;
          };
        };
      };
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Success'];
          };
        };
        /** @description Revision conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** @description Changed dictionary fields must exist in references; changing type also validates category. Unchanged historical values are preserved. */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ProductPatch'];
        };
      };
      responses: {
        /** @description Product */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Product'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/labels/workspace': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['labelWorkspace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['saveLabelWorkspace'];
    trace?: never;
  };
  '/api/v1/labels/prepare': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['prepareLabels'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/references': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Persistent reference entries merged with distinct legacy product values, including default unit шт. Category parentType uses canonical group spelling. No product data is rewritten. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reference dictionaries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceData'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** @description Create a persistent choice. Retries return the same canonical item and ID (200); new value 201. Requires catalogue edit role. Category requires a known nonempty group. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ReferenceCreate'];
        };
      };
      responses: {
        /** @description Existing canonical choice */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceItem'];
          };
        };
        /** @description Created choice */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceItem'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/import/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read-only server validation of a parsed import. Owner, manager or warehouse role; standard cookie authentication, Origin and CSRF. Maximum 1000 rows and 1 MiB JSON request. Names use whitespace normalization and Unicode case folding; duplicate file names or ambiguous existing names are row errors. Computes authoritative regular and effective prices with the editor validator. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CatalogImportRequest'];
        };
      };
      responses: {
        /** @description Validated preview */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CatalogImportPreview'];
          };
        };
        /** @description Invalid request; commit row errors include preview entries and no writes */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Session required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Role or CSRF denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Catalogue snapshot or immutable idempotency key conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/import/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Atomically save every validated row under the ERP ledger lock, or save none. Requires the original entries, unchanged preview snapshot and a stable UUID idempotency key. Revalidates prices, barcodes, recipe references and revisions. Concurrent catalogue/pricing changes return 409. Repeating the identical committed request for the same user returns the original result without writes; a changed payload or different user with that key returns 409. No stock or cash postings. Historical free text dictionary values remain compatible. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CatalogImportCommitRequest'];
        };
      };
      responses: {
        /** @description Atomic commit or original retry result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CatalogImportResult'];
          };
        };
        /** @description Invalid request; commit row errors include preview entries and no writes */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Session required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Role or CSRF denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Catalogue snapshot or immutable idempotency key conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Product: {
      id: string;
      revision: string;
      name: string;
      type: string;
      category: string;
      pack: string;
      size: string;
      unit: string;
      barcode: string;
      priceAt: string;
      cost: string | null;
      markup: string | null;
      price: string | null;
      salePrice: string;
      manualPrice: boolean;
      promotion: boolean;
      minStock: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice: string | null;
      /** @description Current regular price computed from manual pricing or cost/markup, before promotion; not a historical lowest-price record. */
      regularPrice: string;
    };
    ProductPage: {
      items: components['schemas']['Product'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 10 | 20 | 50;
      facets: {
        type: string[];
        category: string[];
        pack: string[];
      };
      canEdit: boolean;
      defaultMarkup: string;
    };
    ProductCreate: {
      name: string;
      type?: string;
      category?: string;
      pack?: string;
      size?: string;
      unit?: string;
      barcode?: string;
      cost?: string;
      markup?: string;
      price?: string | null;
      manualPrice?: boolean;
      promotion?: boolean;
      priceAt?: string;
      priceReviewed?: boolean;
      minStock?: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice?: string | null;
    };
    ProductPatch: {
      revision: string;
      name?: string;
      type?: string;
      category?: string;
      pack?: string;
      size?: string;
      unit?: string;
      barcode?: string;
      cost?: string;
      markup?: string;
      price?: string | null;
      manualPrice?: boolean;
      promotion?: boolean;
      priceAt?: string;
      priceReviewed?: boolean;
      minStock?: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice?: string | null;
    };
    Session: {
      /** @enum {string} */
      role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
      csrf: string;
    };
    Error: {
      error: string;
      code?: string;
    };
    Success: {
      /** @constant */
      ok: true;
    };
    LabelStyle: {
      /** @enum {string} */
      font?: 'rubik' | 'arial' | 'georgia' | 'courier';
      size?: number;
      color?: string;
      /** @enum {string} */
      weight?: '400' | '600' | '700';
      /** @enum {string} */
      align?: 'left' | 'center' | 'right';
    };
    LabelConfig: {
      chain: boolean;
      store: boolean;
      name: boolean;
      nameBig: boolean;
      pack: boolean;
      psize: boolean;
      price: boolean;
      kop: boolean;
      unit: boolean;
      per100: boolean;
      category: boolean;
      date: boolean;
      customEnabled: boolean;
      promo: boolean;
      /** @constant */
      styleVersion: 2;
      /** @enum {string} */
      size: 's' | 'm' | 'l';
      /** @enum {string} */
      border: 'dash' | 'solid' | 'none';
      storeIdx: number;
      custom: string;
      styles: {
        promo?: components['schemas']['LabelStyle'];
        chain?: components['schemas']['LabelStyle'];
        store?: components['schemas']['LabelStyle'];
        custom?: components['schemas']['LabelStyle'];
        name?: components['schemas']['LabelStyle'];
        pack?: components['schemas']['LabelStyle'];
        psize?: components['schemas']['LabelStyle'];
        price?: components['schemas']['LabelStyle'];
        unit?: components['schemas']['LabelStyle'];
        per100?: components['schemas']['LabelStyle'];
        category?: components['schemas']['LabelStyle'];
        date?: components['schemas']['LabelStyle'];
        oldPrice?: components['schemas']['LabelStyle'];
      };
      oldPrice?: boolean;
    };
    LabelSettings: {
      chainName: string;
      storeNames: string[];
      staleDays: number;
    };
    LabelWorkspace: {
      /** @description Saved legacy/v2 layout; frontend migrates supported legacy sizes without rewriting unknown future layouts. */
      config: {
        [key: string]: unknown;
      };
      settings: components['schemas']['LabelSettings'];
      revision: string;
      canEdit: boolean;
      csrf: string;
    };
    LabelWorkspacePatch: {
      revision: string;
      config: components['schemas']['LabelConfig'];
      settings: components['schemas']['LabelSettings'];
    };
    LabelSelection: {
      id: string;
      quantity: number;
    }[];
    LabelPrepareRequest: {
      selection: components['schemas']['LabelSelection'];
    };
    LabelProof: {
      /** @description Saved legacy/v2 layout; frontend migrates supported legacy sizes without rewriting unknown future layouts. */
      config: {
        [key: string]: unknown;
      };
      settings: components['schemas']['LabelSettings'];
      revision: string;
      canEdit: boolean;
      csrf: string;
      products: components['schemas']['Product'][];
      selection: components['schemas']['LabelSelection'];
      /** Format: date */
      date: string;
      snapshot: string;
    };
    /** @enum {string} */
    ReferenceField: 'type' | 'category' | 'pack' | 'size' | 'unit';
    ReferenceItem: {
      id: string;
      field: components['schemas']['ReferenceField'];
      value: string;
      parentType: string;
    };
    ReferenceData: {
      items: components['schemas']['ReferenceItem'][];
      canEdit: boolean;
    };
    ReferenceCreate: {
      field: components['schemas']['ReferenceField'];
      /** @description Whitespace normalized; unit limited to 30 characters. Duplicates match case-insensitively. */
      value: string;
      /** @description Required existing group for category; otherwise absent or empty. */
      parentType?: string;
    };
    /** @description Parsed CSV/XLSX values. Decimal strings, explicit booleans; omitted fields preserve existing metadata. Historical free text dictionary values are supported without creating references. No accounting or recipe fields. */
    CatalogImportValues: {
      name: string;
      type?: string;
      category?: string;
      pack?: string;
      size?: string;
      unit?: string;
      barcode?: string;
      cost?: string;
      markup?: string;
      price?: string | null;
      manualPrice?: boolean;
      promotion?: boolean;
      priceAt?: string;
      priceReviewed?: boolean;
      minStock?: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice?: string | null;
    };
    CatalogImportEntry: {
      line: number;
      /** @description Optional expected ID. Must agree with the unique normalized product name, including hidden products. */
      id?: string;
      /** @description Optional expected product revision; a mismatched revision is a row error. */
      revision?: string;
      values: components['schemas']['CatalogImportValues'];
    };
    CatalogImportRequest: {
      entries: components['schemas']['CatalogImportEntry'][];
      /** @description Initial markup for newly created products; omitted uses the server default. Does not replace an existing markup. */
      defaultMarkup?: string;
    };
    CatalogImportCounts: {
      created: number;
      updated: number;
      errors: number;
    };
    CatalogImportPreviewEntry: {
      line: number | null;
      /** @enum {string} */
      action: 'create' | 'update' | 'error';
      id: string | null;
      revision: string | null;
      values?: components['schemas']['CatalogImportValues'];
      regularPrice?: string;
      salePrice?: string;
      error?: string;
      /** @enum {string} */
      code?: 'invalid_import_row';
    };
    CatalogImportPreview: {
      valid: boolean;
      entries: components['schemas']['CatalogImportPreviewEntry'][];
      counts: components['schemas']['CatalogImportCounts'];
      /** @description Opaque HMAC snapshot of all catalogue documents including hidden products and pricing settings. */
      snapshot: string;
      defaultMarkup: string;
    };
    CatalogImportCommitRequest: {
      entries: components['schemas']['CatalogImportEntry'][];
      /** @description Initial markup for newly created products; omitted uses the server default. Does not replace an existing markup. */
      defaultMarkup?: string;
      snapshot: string;
      /**
       * Format: uuid
       * @description Generate once per confirmed preview; reuse unchanged after an ambiguous network failure. Bound to the user and complete immutable payload.
       */
      idempotencyKey: string;
    };
    CatalogImportResult: {
      /** @constant */
      ok: true;
      /** Format: uuid */
      idempotencyKey: string;
      counts: components['schemas']['CatalogImportCounts'];
      entries: {
        line: number;
        /** @enum {string} */
        action: 'create' | 'update';
        id: string;
        revision: string;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  labelWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelWorkspace'];
        };
      };
      /** @description Success */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  saveLabelWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LabelWorkspacePatch'];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelWorkspace'];
        };
      };
      /** @description Success */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  prepareLabels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LabelPrepareRequest'];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelProof'];
        };
      };
      /** @description Success */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
}
