/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Session */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Session'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          q?: string;
          type?: string;
          category?: string;
          pack?: string;
          promotion?: string;
          page?: number;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ProductPage */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProductPage'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** @description Create a product. Nonempty dictionary fields must exist in references; category must belong to type. Legacy imports retain their text compatibility. 409 `duplicate_name` when another product has the same name after trimming, collapsing spaces and ignoring case (the import matching key). */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ProductCreate'];
        };
      };
      responses: {
        /** @description Product */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Product'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Product */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Product'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** @description Delete an unused product. 400 when it is used in accounting or a recipe, 403 for roles without catalogue editing, 409 `revision_conflict` for a stale revision. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            revision: string;
          };
        };
      };
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Success'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** @description Changed dictionary fields must exist in references; changing type also validates category. Unchanged historical values are preserved. 409 `revision_conflict` for a stale revision; `duplicate_name` when a renamed product matches another product name after trimming, collapsing spaces and ignoring case. Existing duplicates stay editable without a rename. */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ProductPatch'];
        };
      };
      responses: {
        /** @description Product */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Product'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/labels/workspace': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['labelWorkspace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['saveLabelWorkspace'];
    trace?: never;
  };
  '/api/v1/labels/prepare': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['prepareLabels'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/references': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Active persistent choices and compatible legacy product values; explicit archive/merge tombstones suppress old values and defaults. archivedItems supports readable unchanged historical selections. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reference dictionaries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceData'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** @description Create a persistent choice. Retries return the same canonical item and ID (200); new value 201. Requires catalogue edit role. Category requires a known nonempty group. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ReferenceCreate'];
        };
      };
      responses: {
        /** @description Existing canonical choice */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceItem'];
          };
        };
        /** @description Created choice */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceItem'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/import/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read-only server validation of a parsed import. Owner, manager or warehouse role; standard cookie authentication, Origin and CSRF. Maximum 1000 rows and 1 MiB JSON request. Names use whitespace normalization and Unicode case folding; duplicate file names or ambiguous existing names are row errors. Computes authoritative regular and effective prices with the editor validator. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CatalogImportRequest'];
        };
      };
      responses: {
        /** @description Validated preview */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CatalogImportPreview'];
          };
        };
        /** @description Invalid request; commit row errors include preview entries and no writes */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Session required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Role or CSRF denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Catalogue snapshot or immutable idempotency key conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/import/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Atomically save every validated row under the ERP ledger lock, or save none. Requires the original entries, unchanged preview snapshot and a stable UUID idempotency key. Revalidates prices, barcodes, recipe references and revisions. Concurrent catalogue/pricing changes return 409. Repeating the identical committed request for the same user returns the original result without writes; a changed payload or different user with that key returns 409. No stock or cash postings. Historical free text dictionary values remain compatible. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CatalogImportCommitRequest'];
        };
      };
      responses: {
        /** @description Atomic commit or original retry result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CatalogImportResult'];
          };
        };
        /** @description Invalid request; commit row errors include preview entries and no writes */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Session required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Role or CSRF denied */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Catalogue snapshot or immutable idempotency key conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/pricing/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Owner-only read-only preview. Standard cookie authentication, Origin and CSRF. At most 1000 affected products and 1 MiB JSON, with an explicit error rather than truncation. Markup selects active products and preserves manual prices unless resetManualPrices is true. Rounding is global and includes hidden products. Proposed prices and promotion validation use the authoritative shared Decimal calculation. Badge-only legacy promotions block changes that alter their regular price. Future default markup pins old fallback values for excluded existing products; metadata-only pinning preserves priceAt. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CatalogPricingRequest'];
        };
      };
      responses: {
        /** @description Price preview */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CatalogPricingPreview'];
          };
        };
        /** @description Invalid request or row errors; no writes */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Session required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Owner role or CSRF required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Catalogue snapshot or immutable idempotency key conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/pricing/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Owner-only atomic catalogue price change under the ERP ledger lock. Send the original reviewed payload, catalogue/pricing snapshot and one stable UUID. Revalidates every affected product and settings; row errors save nothing. Concurrent catalogue/pricing changes return 409. pricing_runs stores the immutable request hash, owner and original result; identical retries return that result without new writes, changed payload or owner returns 409. No stock or cash postings. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CatalogPricingCommitRequest'];
        };
      };
      responses: {
        /** @description Atomic result or original retry result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CatalogPricingResult'];
          };
        };
        /** @description Invalid request or row errors; no writes */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Session required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Owner role or CSRF required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Catalogue snapshot or immutable idempotency key conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/products/price-preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read-only authoritative Decimal price calculation. No product, audit, inventory or settings writes. Uses same validation and legacy promotion preservation as Save. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ProductPricePreviewRequest'];
        };
      };
      responses: {
        /** @description ProductPricePreview */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProductPricePreview'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Product not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/references/manage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current stable dictionaries including explicit archived/merged entries; read only. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceManagement'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/references/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read-only impact preview. Catalogue edit roles; reference revision required. Same-name group children coalesce only into the explicitly selected target group. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ReferenceMutation'];
        };
      };
      responses: {
        /** @description Result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceImpact'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/references/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Ledger-locked atomic commit of a reviewed impact. Exact same key and request returns the original result; different request conflicts. Current edit policy is revalidated even on retries. Historical accounting/order/lot data is never rewritten. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ReferenceCommit'];
        };
      };
      responses: {
        /** @description Result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReferenceCommitResult'];
          };
        };
        /** @description Error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Error */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/promotions/context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['promotionContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/promotions/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['priceHistory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/promotions/campaigns': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listCampaigns'];
    put?: never;
    post: operations['createCampaign'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/promotions/campaigns/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['archiveCampaign'];
    options?: never;
    head?: never;
    patch: operations['updateCampaign'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Product: {
      id: string;
      revision: string;
      name: string;
      type: string;
      category: string;
      pack: string;
      size: string;
      unit: string;
      barcode: string;
      /** @description Price review date YYYY-MM-DD, separate from purchase document dates; empty when the price was never reviewed. */
      priceAt: string;
      cost: string | null;
      markup: string | null;
      price: string | null;
      salePrice: string;
      manualPrice: boolean;
      promotion: boolean;
      minStock: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice: string | null;
      /** @description Current regular price computed from manual pricing or cost/markup, before promotion; not a historical lowest-price record. */
      regularPrice: string;
      /** @description Server-owned stable dictionary IDs; never accepted in product writes. Legacy text gets a deterministic identity, explicit archives suppress new choices. */
      readonly referenceIds?: {
        type?: string;
        category?: string;
        pack?: string;
        size?: string;
        unit?: string;
      };
      readonly effectivePromotion?: components['schemas']['EffectivePromotion'];
      /** Format: date */
      readonly effectiveDay?: string;
      readonly effectivePriceRevision?: string;
      readonly priceContext?: components['schemas']['PriceContext'];
    };
    ProductPage: {
      items: components['schemas']['Product'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 10 | 20 | 50;
      facets: {
        type: string[];
        category: string[];
        pack: string[];
      };
      canEdit: boolean;
      defaultMarkup: string;
    };
    ProductCreate: {
      name: string;
      type?: string;
      category?: string;
      pack?: string;
      size?: string;
      unit?: string;
      barcode?: string;
      cost?: string;
      markup?: string;
      price?: string | null;
      manualPrice?: boolean;
      promotion?: boolean;
      /** @description Price review date YYYY-MM-DD, separate from purchase document dates; empty when the price was never reviewed. */
      priceAt?: string;
      priceReviewed?: boolean;
      minStock?: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice?: string | null;
      /** @description Optional preview pricing settings revision. Mismatch returns pricing_revision_conflict before any write. */
      pricingRevision?: string;
    };
    ProductPatch: {
      revision: string;
      name?: string;
      type?: string;
      category?: string;
      pack?: string;
      size?: string;
      unit?: string;
      barcode?: string;
      cost?: string;
      markup?: string;
      price?: string | null;
      manualPrice?: boolean;
      promotion?: boolean;
      /** @description Price review date YYYY-MM-DD, separate from purchase document dates; empty when the price was never reviewed. */
      priceAt?: string;
      priceReviewed?: boolean;
      minStock?: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice?: string | null;
      /** @description Optional preview pricing settings revision. Mismatch returns pricing_revision_conflict before any write. */
      pricingRevision?: string;
    };
    Session: {
      /** @enum {string} */
      role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
      csrf: string;
    };
    Error: {
      error: string;
      code?: string;
    };
    Success: {
      /** @constant */
      ok: true;
    };
    LabelStyle: {
      /** @enum {string} */
      font?: 'rubik' | 'arial' | 'georgia' | 'courier';
      size?: number;
      color?: string;
      /** @enum {string} */
      weight?: '400' | '600' | '700';
      /** @enum {string} */
      align?: 'left' | 'center' | 'right';
    };
    LabelConfig: {
      chain: boolean;
      store: boolean;
      name: boolean;
      nameBig: boolean;
      pack: boolean;
      psize: boolean;
      price: boolean;
      kop: boolean;
      unit: boolean;
      per100: boolean;
      category: boolean;
      date: boolean;
      customEnabled: boolean;
      promo: boolean;
      /** @constant */
      styleVersion: 2;
      /** @enum {string} */
      size: 's' | 'm' | 'l';
      /** @enum {string} */
      border: 'dash' | 'solid' | 'none';
      storeIdx: number;
      custom: string;
      styles: {
        promo?: components['schemas']['LabelStyle'];
        chain?: components['schemas']['LabelStyle'];
        store?: components['schemas']['LabelStyle'];
        custom?: components['schemas']['LabelStyle'];
        name?: components['schemas']['LabelStyle'];
        pack?: components['schemas']['LabelStyle'];
        psize?: components['schemas']['LabelStyle'];
        price?: components['schemas']['LabelStyle'];
        unit?: components['schemas']['LabelStyle'];
        per100?: components['schemas']['LabelStyle'];
        category?: components['schemas']['LabelStyle'];
        date?: components['schemas']['LabelStyle'];
        oldPrice?: components['schemas']['LabelStyle'];
      };
      oldPrice?: boolean;
    };
    LabelSettings: {
      chainName: string;
      storeNames: string[];
      staleDays: number;
    };
    LabelWorkspace: {
      /** @description Saved legacy/v2 layout; frontend migrates supported legacy sizes without rewriting unknown future layouts. */
      config: {
        [key: string]: unknown;
      };
      settings: components['schemas']['LabelSettings'];
      revision: string;
      canEdit: boolean;
      csrf: string;
    };
    LabelWorkspacePatch: {
      revision: string;
      config: components['schemas']['LabelConfig'];
      settings: components['schemas']['LabelSettings'];
    };
    LabelSelection: {
      id: string;
      quantity: number;
    }[];
    LabelPrepareRequest: {
      selection: components['schemas']['LabelSelection'];
      /** @description ERP store identity; null means network for an unscoped user, own store for a scoped user. */
      store?: number | null;
    };
    LabelProof: {
      /** @description Saved legacy/v2 layout; frontend migrates supported legacy sizes without rewriting unknown future layouts. */
      config: {
        [key: string]: unknown;
      };
      settings: components['schemas']['LabelSettings'];
      revision: string;
      canEdit: boolean;
      csrf: string;
      products: components['schemas']['Product'][];
      selection: components['schemas']['LabelSelection'];
      /** Format: date */
      date: string;
      snapshot: string;
      readonly priceContext?: components['schemas']['PriceContext'];
    };
    /** @enum {string} */
    ReferenceField: 'type' | 'category' | 'pack' | 'size' | 'unit';
    ReferenceItem: {
      id: string;
      field: components['schemas']['ReferenceField'];
      value: string;
      parentType: string;
    };
    ReferenceData: {
      items: components['schemas']['ReferenceItem'][];
      canEdit: boolean;
      archivedItems?: components['schemas']['ReferenceItem'][];
    };
    ReferenceCreate: {
      field: components['schemas']['ReferenceField'];
      /** @description Whitespace normalized; unit limited to 30 characters. Duplicates match case-insensitively. */
      value: string;
      /** @description Required existing group for category; otherwise absent or empty. */
      parentType?: string;
    };
    /** @description Parsed CSV/XLSX values. Decimal strings, explicit booleans; omitted fields preserve existing metadata. Historical free text dictionary values are supported without creating references. No accounting or recipe fields. */
    CatalogImportValues: {
      name: string;
      type?: string;
      category?: string;
      pack?: string;
      size?: string;
      unit?: string;
      barcode?: string;
      cost?: string;
      markup?: string;
      price?: string | null;
      manualPrice?: boolean;
      promotion?: boolean;
      priceAt?: string;
      priceReviewed?: boolean;
      minStock?: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice?: string | null;
    };
    CatalogImportEntry: {
      line: number;
      /** @description Optional expected ID. Must agree with the unique normalized product name, including hidden products. */
      id?: string;
      /** @description Optional expected product revision; a mismatched revision is a row error. */
      revision?: string;
      values: components['schemas']['CatalogImportValues'];
    };
    CatalogImportRequest: {
      entries: components['schemas']['CatalogImportEntry'][];
      /** @description Initial markup for newly created products; omitted uses the server default. Does not replace an existing markup. */
      defaultMarkup?: string;
    };
    CatalogImportCounts: {
      created: number;
      updated: number;
      errors: number;
    };
    CatalogImportPreviewEntry: {
      line: number | null;
      /** @enum {string} */
      action: 'create' | 'update' | 'error';
      id: string | null;
      revision: string | null;
      values?: components['schemas']['CatalogImportValues'];
      regularPrice?: string;
      salePrice?: string;
      error?: string;
      /** @enum {string} */
      code?: 'invalid_import_row';
    };
    CatalogImportPreview: {
      valid: boolean;
      entries: components['schemas']['CatalogImportPreviewEntry'][];
      counts: components['schemas']['CatalogImportCounts'];
      /** @description Opaque HMAC snapshot of all catalogue documents including hidden products and pricing settings. */
      snapshot: string;
      defaultMarkup: string;
    };
    CatalogImportCommitRequest: {
      entries: components['schemas']['CatalogImportEntry'][];
      /** @description Initial markup for newly created products; omitted uses the server default. Does not replace an existing markup. */
      defaultMarkup?: string;
      snapshot: string;
      /**
       * Format: uuid
       * @description Generate once per confirmed preview; reuse unchanged after an ambiguous network failure. Bound to the user and complete immutable payload.
       */
      idempotencyKey: string;
    };
    CatalogImportResult: {
      /** @constant */
      ok: true;
      /** Format: uuid */
      idempotencyKey: string;
      counts: components['schemas']['CatalogImportCounts'];
      entries: {
        line: number;
        /** @enum {string} */
        action: 'create' | 'update';
        id: string;
        revision: string;
      }[];
    };
    CatalogMarkupRequest: {
      /** @constant */
      kind: 'markup';
      /** @description null selects all active products; explicit IDs must exist and be active. */
      ids: null | string[];
      markup: string;
      /** @description false preserves manually priced products; true explicitly resets them to computed pricing. */
      resetManualPrices: boolean;
      /** @description Allowed only when ids is null. Existing excluded products lacking an explicit markup get their old fallback materialized, including hidden and skipped manual products. */
      updateDefault: boolean;
    };
    CatalogRoundingRequest: {
      /** @constant */
      kind: 'rounding';
      /** @enum {string} */
      rounding: '0.01' | '0.1' | '0.5' | '1';
    };
    CatalogPricingRequest:
      | components['schemas']['CatalogMarkupRequest']
      | components['schemas']['CatalogRoundingRequest'];
    CatalogMarkupCommitRequest: {
      /** @constant */
      kind: 'markup';
      /** @description null selects all active products; explicit IDs must exist and be active. */
      ids: null | string[];
      markup: string;
      /** @description false preserves manually priced products; true explicitly resets them to computed pricing. */
      resetManualPrices: boolean;
      /** @description Allowed only when ids is null. Existing excluded products lacking an explicit markup get their old fallback materialized, including hidden and skipped manual products. */
      updateDefault: boolean;
      snapshot: string;
      /** Format: uuid */
      idempotencyKey: string;
    };
    CatalogRoundingCommitRequest: {
      /** @constant */
      kind: 'rounding';
      /** @enum {string} */
      rounding: '0.01' | '0.1' | '0.5' | '1';
      snapshot: string;
      /** Format: uuid */
      idempotencyKey: string;
    };
    CatalogPricingCommitRequest:
      | components['schemas']['CatalogMarkupCommitRequest']
      | components['schemas']['CatalogRoundingCommitRequest'];
    CatalogPricingPair: {
      regularPrice: string;
      salePrice: string;
    };
    CatalogPricingSettingsValues: {
      defaultMarkup: string;
      rounding: string;
    };
    CatalogPricingSettings: {
      before: components['schemas']['CatalogPricingSettingsValues'];
      after: components['schemas']['CatalogPricingSettingsValues'];
    };
    /** @description Counts of preview product entries. changedRecords counts product writes, including metadata-only fallback pinning; settings changes appear separately. skippedManual counts successful skip entries and can overlap changedRecords when an old fallback must be pinned. errors prevents any commit. */
    CatalogPricingSummary: {
      candidates: number;
      changedPrices: number;
      changedRecords: number;
      skippedManual: number;
      errors: number;
    };
    CatalogPricingPreviewEntry: {
      id: string;
      name: string;
      hidden: boolean;
      /** @enum {string} */
      action: 'update' | 'unchanged' | 'skip' | 'error';
      before: components['schemas']['CatalogPricingPair'];
      after: components['schemas']['CatalogPricingPair'];
      error?: string;
    };
    CatalogPricingPreview: {
      valid: boolean;
      /** @enum {string} */
      kind: 'markup' | 'rounding';
      snapshot: string;
      entries: components['schemas']['CatalogPricingPreviewEntry'][];
      summary: components['schemas']['CatalogPricingSummary'];
      settings: components['schemas']['CatalogPricingSettings'];
    };
    CatalogPricingResult: {
      /** @constant */
      ok: true;
      /** @enum {string} */
      kind: 'markup' | 'rounding';
      /** Format: uuid */
      idempotencyKey: string;
      summary: components['schemas']['CatalogPricingSummary'];
      settings: components['schemas']['CatalogPricingSettings'];
      entries: {
        id: string;
        revision: string;
        /** @enum {string} */
        action: 'update' | 'unchanged' | 'skip';
      }[];
    };
    /** @description Read-only pricing inputs shared with Save. Existing id enables unchanged legacy promotion terms; revision without id is invalid. */
    ProductPricePreviewRequest: {
      cost?: string;
      markup?: string;
      manualPrice?: boolean;
      price?: string | null;
      promotion?: boolean;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice?: string | null;
      priceReviewed?: boolean;
      id?: string;
      revision?: string;
    };
    ProductPricePreview: {
      regularPrice: string;
      salePrice: string;
      config: {
        markup: string;
        rounding: string;
      };
      pricingRevision: string;
      warnings: string[];
      /** @description True only for an enabled, valid explicit promotion below regularPrice. False for no promotion and grandfathered legacy badge-only/invalid promotions. */
      promotionValid: boolean;
      readonly effectivePromotion?: components['schemas']['EffectivePromotion'];
      /** Format: date */
      readonly effectiveDay?: string;
      readonly effectivePriceRevision?: string;
      readonly priceContext?: components['schemas']['PriceContext'];
    };
    ReferenceManagedItem: {
      id: string;
      field: components['schemas']['ReferenceField'];
      value: string;
      parentType: string;
      /** @enum {string} */
      state: 'active' | 'archived' | 'merged';
      parentId: string | null;
      mergedInto: string | null;
      revision: string;
    };
    ReferenceManagement: {
      items: components['schemas']['ReferenceManagedItem'][];
      canEdit: boolean;
      csrf: string;
    };
    ReferenceMutation: {
      sourceId: string;
      revision: string;
      /** @enum {string} */
      operation: 'rename' | 'merge' | 'archive' | 'restore';
      value?: string;
      targetId?: string;
    };
    ReferenceImpact: {
      snapshot: string;
      /** @enum {string} */
      operation: 'rename' | 'merge' | 'archive' | 'restore';
      source: components['schemas']['ReferenceManagedItem'];
      target: components['schemas']['ReferenceManagedItem'] | null;
      productCount: number;
      usageCount: number;
      referenceCount: number;
      coalescedCategories: {
        sourceId: string;
        targetId: string;
        value: string;
      }[];
      examples: {
        id: string;
        name: string;
      }[];
      blocked: string[];
      blockedCount: number;
      warnings: string[];
    };
    ReferenceCommit: {
      sourceId: string;
      revision: string;
      /** @enum {string} */
      operation: 'rename' | 'merge' | 'archive' | 'restore';
      value?: string;
      targetId?: string;
      snapshot: string;
      /** Format: uuid */
      idempotencyKey: string;
    };
    ReferenceCommitResult: {
      snapshot: string;
      /** @enum {string} */
      operation: 'rename' | 'merge' | 'archive' | 'restore';
      source: components['schemas']['ReferenceManagedItem'];
      target: components['schemas']['ReferenceManagedItem'] | null;
      productCount: number;
      usageCount: number;
      referenceCount: number;
      coalescedCategories: {
        sourceId: string;
        targetId: string;
        value: string;
      }[];
      examples: {
        id: string;
        name: string;
      }[];
      blocked: string[];
      blockedCount: number;
      warnings: string[];
      /** @constant */
      ok: true;
    };
    PriceContext: {
      storeId: number | null;
      storeName: string | null;
    };
    EffectivePromotion: {
      /** @enum {string} */
      source: 'legacy' | 'campaign';
      id: string | null;
      name: string;
      price: string;
      /** Format: date */
      startsOn: string | null;
      /** Format: date */
      endsOn: string | null;
      revision: number | null;
    } | null;
    PromotionContext: {
      storeId: number | null;
      storeName: string | null;
      /** Format: date */
      effectiveDay: string;
      stores: {
        id: number;
        name: string;
      }[];
      canManage: boolean;
      canSelectNetwork: boolean;
      canViewHistory: boolean;
      csrf: string;
    };
    CampaignInput: {
      name: string;
      /** Format: date */
      startsOn: string;
      /** Format: date */
      endsOn: string;
      active: boolean;
      /** @enum {string} */
      scope: 'network' | 'stores';
      stores: number[];
      prices: {
        product: string;
        price: string;
      }[];
      reason: string;
    };
    CampaignCreate: {
      name: string;
      /** Format: date */
      startsOn: string;
      /** Format: date */
      endsOn: string;
      active: boolean;
      /** @enum {string} */
      scope: 'network' | 'stores';
      stores: number[];
      prices: {
        product: string;
        price: string;
      }[];
      reason: string;
      /** Format: uuid */
      idempotencyKey: string;
    };
    CampaignPatch: {
      name: string;
      /** Format: date */
      startsOn: string;
      /** Format: date */
      endsOn: string;
      active: boolean;
      /** @enum {string} */
      scope: 'network' | 'stores';
      stores: number[];
      prices: {
        product: string;
        price: string;
      }[];
      reason: string;
      revision: number;
    };
    CampaignArchive: {
      revision: number;
      reason: string;
    };
    Campaign: {
      name: string;
      /** Format: date */
      startsOn: string;
      /** Format: date */
      endsOn: string;
      active: boolean;
      /** @enum {string} */
      scope: 'network' | 'stores';
      stores: number[];
      prices: {
        product: string;
        price: string;
        name: string;
      }[];
      reason: string;
      /** Format: uuid */
      id: string;
      revision: number;
      archived: boolean;
      /** @enum {string} */
      status: 'active' | 'scheduled' | 'expired' | 'disabled' | 'archived';
      author: string;
    };
    PricingTerms: {
      regularPrice: string;
      salePrice: string;
      effectivePromotion: components['schemas']['EffectivePromotion'];
    };
    PriceHistoryItem: {
      id: number;
      product: string;
      storeId: number | null;
      before: components['schemas']['PricingTerms'];
      after: components['schemas']['PricingTerms'];
      author: string;
      source: string;
      reason: string;
      /** Format: date-time */
      at: string;
    };
    CampaignPage: {
      items: components['schemas']['Campaign'][];
    };
    PriceHistoryPage: {
      items: components['schemas']['PriceHistoryItem'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  labelWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelWorkspace'];
        };
      };
      /** @description Success */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  saveLabelWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LabelWorkspacePatch'];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelWorkspace'];
        };
      };
      /** @description Success */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  prepareLabels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LabelPrepareRequest'];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelProof'];
        };
      };
      /** @description Success */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Success */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  promotionContext: {
    parameters: {
      query?: {
        /** @description ERPStore identity; absent means network for unscoped user or own store for scoped user. */
        store?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authoritative promotion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PromotionContext'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  priceHistory: {
    parameters: {
      query?: {
        /** @description ERPStore identity; absent means network for unscoped user or own store for scoped user. */
        store?: number;
        product?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authoritative promotion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PriceHistoryPage'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  listCampaigns: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authoritative promotion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CampaignPage'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  createCampaign: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CampaignCreate'];
      };
    };
    responses: {
      /** @description Authoritative promotion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Campaign'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  archiveCampaign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CampaignArchive'];
      };
    };
    responses: {
      /** @description Authoritative promotion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Campaign'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  updateCampaign: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CampaignPatch'];
      };
    };
    responses: {
      /** @description Authoritative promotion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Campaign'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Validation/access/version error; local draft must be retained */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
}
