/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/purchases/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['purchaseDocuments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/purchases/replenishment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['replenishmentGroups'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/purchases/replenishment/lines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['replenishmentLines'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/purchases/replenishment/draft': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['replenishmentDraft'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PurchasePolicy: {
      /** @enum {string} */
      role: 'owner' | 'manager' | 'warehouse';
      store: number | null;
      documentKinds: ('purchase_order' | 'receipt' | 'supplier_return')[];
    };
    PurchaseQuery: {
      q: string;
      store: number | null;
      /** @enum {string} */
      status: '' | 'draft' | 'posted' | 'reversed';
      /** @enum {string} */
      kind: '' | 'purchase_order' | 'receipt' | 'supplier_return';
      from: string;
      to: string;
    };
    ReplenishmentQuery: {
      q: string;
      store: number | null;
      warehouse: number | null;
    };
    ReplenishmentSelection: {
      q: string;
      store: number | null;
      warehouse: number;
      party: number | null;
    };
    PurchaseDocument: {
      id: number;
      number: string;
      /** @enum {string} */
      kind: 'purchase_order' | 'receipt' | 'supplier_return';
      /** @enum {string} */
      status: 'draft' | 'posted' | 'reversed';
      date: string;
      store: number;
      storeName: string;
      party: number | null;
      partyName: string;
      total: string;
      revision: number;
    };
    PurchaseDocuments: {
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['PurchasePolicy'];
      query: components['schemas']['PurchaseQuery'];
      items: components['schemas']['PurchaseDocument'][];
    };
    ReplenishmentLine: {
      product: string;
      name: string;
      unit: string;
      quantity: string;
      price: string;
      available: string;
      minimum: string;
      onOrder: string;
      costKnown: boolean;
    };
    ReplenishmentGroup: {
      key: string;
      store: number;
      storeName: string;
      warehouse: number;
      warehouseName: string;
      party: number | null;
      partyName: string;
      linesCount: number;
      total: string;
      preview: components['schemas']['ReplenishmentLine'][];
      binding: string;
      parts: number;
    };
    ReplenishmentGroups: {
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['PurchasePolicy'];
      query: components['schemas']['ReplenishmentQuery'];
      asOf: string;
      items: components['schemas']['ReplenishmentGroup'][];
      summary: {
        groups: number;
        lines: number;
        covered: number;
        total: string;
      };
    };
    ReplenishmentLines: {
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      policy: components['schemas']['PurchasePolicy'];
      query: components['schemas']['ReplenishmentSelection'];
      group: components['schemas']['ReplenishmentGroup'];
      binding: string;
      items: components['schemas']['ReplenishmentLine'][];
      /** Format: date */
      asOf: string;
    };
    ReplenishmentDraft: {
      group: components['schemas']['ReplenishmentGroup'];
      binding: string;
      lines: components['schemas']['ReplenishmentLine'][];
      policy: components['schemas']['PurchasePolicy'];
      part: number;
      parts: number;
      /** @enum {integer} */
      limit: 200;
      total: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  purchaseDocuments: {
    parameters: {
      query?: {
        /** @description q */
        q?: string;
        /** @description store */
        store?: number | null;
        /** @description status */
        status?: '' | 'draft' | 'posted' | 'reversed';
        /** @description kind */
        kind?: '' | 'purchase_order' | 'receipt' | 'supplier_return';
        /** @description from */
        from?: string;
        /** @description to */
        to?: string;
        /** @description page */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped RR read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PurchaseDocuments'];
        };
      };
      /** @description Current role or scope denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Replenishment group changed; explicit refresh required */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  replenishmentGroups: {
    parameters: {
      query?: {
        /** @description q */
        q?: string;
        /** @description store */
        store?: number | null;
        /** @description warehouse */
        warehouse?: number | null;
        /** @description page */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped RR read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReplenishmentGroups'];
        };
      };
      /** @description Current role or scope denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Replenishment group changed; explicit refresh required */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  replenishmentLines: {
    parameters: {
      query: {
        /** @description q */
        q?: string;
        /** @description store */
        store?: number | null;
        /** @description warehouse */
        warehouse: number;
        /** @description 0 represents no supplier */
        party: number;
        /** @description binding */
        binding: string;
        /** @description page */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped RR read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReplenishmentLines'];
        };
      };
      /** @description Current role or scope denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Replenishment group changed; explicit refresh required */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  replenishmentDraft: {
    parameters: {
      query: {
        /** @description q */
        q?: string;
        /** @description store */
        store?: number | null;
        /** @description warehouse */
        warehouse: number;
        /** @description 0 represents no supplier */
        party: number;
        /** @description binding */
        binding: string;
        /** @description part */
        part: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped RR read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReplenishmentDraft'];
        };
      };
      /** @description Current role or scope denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Replenishment group changed; explicit refresh required */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
