/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/receipt-pricing/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['receiptPriceCurrent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/receipt-pricing/{id}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['receiptPricePreview'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/receipt-pricing/{id}/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['receiptPriceCommit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/receipt-pricing/{id}/results/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['receiptPriceResult'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SourceLine: {
      id: number;
      /** Format: uuid */
      lineKey: string;
      product: string;
      name: string;
      unit: string;
      quantity: string;
      price: string;
      amount: string;
      landedAmount: string | null;
      lot: string;
      expiry: string;
    };
    ReceiptSource: {
      id: number;
      revision: number;
      /** @enum {unknown} */
      status: 'draft' | 'posted' | 'reversed';
      /** Format: date */
      date: string;
      store: number;
      storeName: string;
      total: string;
      additionalCost: string;
      lines: components['schemas']['SourceLine'][];
    };
    PriceContext: {
      storeId: number | null;
      storeName: string | null;
    };
    SourceBinding: {
      id: number;
      /** Format: uuid */
      lineKey: string;
    };
    PriceValues: {
      cost: string;
      markup: string;
      manualPrice: boolean;
      price: string | null;
      priceReviewed: boolean;
    };
    ProposalEntry: {
      id: string;
      revision: string;
      sourceLine: components['schemas']['SourceBinding'] | null;
      values: components['schemas']['PriceValues'];
    };
    Proposal: {
      sourceRevision: number;
      sourceSnapshot: string;
      priceContext: {
        storeId: number | null;
      };
      entries: components['schemas']['ProposalEntry'][];
      reason: string;
    };
    CommitRequest: {
      sourceRevision: number;
      sourceSnapshot: string;
      priceContext: {
        storeId: number | null;
      };
      entries: components['schemas']['ProposalEntry'][];
      reason: string;
      snapshot: string;
      /** Format: uuid */
      idempotencyKey: string;
    };
    Current: {
      source: components['schemas']['ReceiptSource'];
      sourceSnapshot: string;
      priceContext: components['schemas']['PriceContext'];
      /** Format: date */
      effectiveDay: string;
      csrf: string;
      canEdit: boolean;
      canSelectNetwork: boolean;
      products: components['schemas']['Product'][];
    };
    PreviewEntry: {
      id: string;
      revision: string;
      sourceLine: components['schemas']['SourceBinding'] | null;
      values: {
        cost: string;
        markup: string;
        manualPrice: boolean;
        price: string | null;
      } | null;
      priceReviewed: boolean;
      comparison: components['schemas']['OperationPriceComparison'] | null;
      error: string | null;
    };
    Preview: {
      source: components['schemas']['ReceiptSource'];
      sourceSnapshot: string;
      priceContext: components['schemas']['PriceContext'];
      /** Format: date */
      effectiveDay: string;
      valid: boolean;
      entries: components['schemas']['PreviewEntry'][];
      snapshot: string;
    };
    CommitEntry: {
      line: number;
      /** @enum {unknown} */
      action: 'update';
      id: string;
      revision: string;
      priceResult: components['schemas']['OperationPriceResult'];
    };
    Receipt: {
      /** @constant */
      ok: true;
      /** Format: uuid */
      idempotencyKey: string;
      source: components['schemas']['ReceiptSource'];
      sourceSnapshot: string;
      priceContext: components['schemas']['PriceContext'];
      counts: {
        /** @constant */
        created: 0;
        updated: number;
        /** @constant */
        errors: 0;
      };
      entries: components['schemas']['CommitEntry'][];
    };
    EffectivePromotion: {
      /** @enum {string} */
      source: 'legacy' | 'campaign';
      id: string | null;
      name: string;
      price: string;
      /** Format: date */
      startsOn: string | null;
      /** Format: date */
      endsOn: string | null;
      revision: number | null;
    } | null;
    'schemas-PriceContext': {
      storeId: number | null;
      storeName: string | null;
    };
    Product: {
      id: string;
      revision: string;
      name: string;
      type: string;
      category: string;
      pack: string;
      size: string;
      unit: string;
      barcode: string;
      /** @description Price review date YYYY-MM-DD, separate from purchase document dates; empty when the price was never reviewed. */
      priceAt: string;
      cost: string | null;
      markup: string | null;
      price: string | null;
      salePrice: string;
      manualPrice: boolean;
      promotion: boolean;
      minStock: string;
      /** @description Explicit promotional price; retained when promotion is disabled. Active promotions require a value greater than zero and below regularPrice. Legacy badge-only records may contain null. */
      promotionPrice: string | null;
      /** @description Current regular price computed from manual pricing or cost/markup, before promotion; not a historical lowest-price record. */
      regularPrice: string;
      /** @description Server-owned stable dictionary IDs; never accepted in product writes. Legacy text gets a deterministic identity, explicit archives suppress new choices. */
      readonly referenceIds?: {
        type?: string;
        category?: string;
        pack?: string;
        size?: string;
        unit?: string;
      };
      readonly effectivePromotion?: components['schemas']['EffectivePromotion'];
      /** Format: date */
      readonly effectiveDay?: string;
      readonly effectivePriceRevision?: string;
      readonly priceContext?: components['schemas']['schemas-PriceContext'];
      /** @description Поріг сповіщення про придатність SKU: null — чинний типовий 7 днів; 0 — дата придатності, прострочені включаються завжди. */
      expiryAlertDays?: number | null;
      readonly hidden: boolean;
      readonly canEdit: boolean;
    };
    OperationPriceDisplay: {
      promotion: boolean;
      oldPrice: string | null;
    };
    OperationPriceTerms: {
      productRevision: string;
      effectivePriceRevision: string;
      regularPrice: string;
      salePrice: string;
      effectivePromotion: components['schemas']['EffectivePromotion'] | null;
      display: components['schemas']['OperationPriceDisplay'];
    };
    OperationPriceComparison: {
      before: components['schemas']['OperationPriceTerms'] | null;
      after: components['schemas']['OperationPriceTerms'];
      retailChanged: boolean;
      displayChanged: boolean;
      created: boolean;
    };
    OperationPriceResult: {
      before: components['schemas']['OperationPriceTerms'] | null;
      after: components['schemas']['OperationPriceTerms'];
      retailChanged: boolean;
      displayChanged: boolean;
      created: boolean;
      id: string;
      line: number | null;
      ordinal: number;
      /** @enum {string} */
      outcome: 'created' | 'updated' | 'unchanged' | 'skipped';
      context: {
        storeId: number | null;
        storeName: string | null;
        /** Format: date */
        effectiveDay: string;
      };
      /** Format: date-time */
      committedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  receiptPriceCurrent: {
    parameters: {
      query?: {
        store?: string;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Перевірені дані */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Current'];
        };
      };
      /** @description Некоректна пропозиція */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Поточні права чи контекст не дозволяють доступ */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Джерело, план або ключ повтору змінено */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  receiptPricePreview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Proposal'];
      };
    };
    responses: {
      /** @description Перевірені дані */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Preview'];
        };
      };
      /** @description Некоректна пропозиція */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Поточні права чи контекст не дозволяють доступ */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Джерело, план або ключ повтору змінено */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  receiptPriceCommit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommitRequest'];
      };
    };
    responses: {
      /** @description Перевірені дані */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Receipt'];
        };
      };
      /** @description Некоректна пропозиція */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Поточні права чи контекст не дозволяють доступ */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Джерело, план або ключ повтору змінено */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  receiptPriceResult: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Перевірені дані */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Receipt'];
        };
      };
      /** @description Некоректна пропозиція */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Поточні права чи контекст не дозволяють доступ */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Джерело, план або ключ повтору змінено */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
