/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/reports/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current READ ONLY REPEATABLE READ; independent reads may differ. Full-filter totals. Owner/manager/accountant scoped; payroll rows and bonus excluded for manager. */
    get: operations['reportSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/reports/rows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current READ ONLY REPEATABLE READ; independent reads may differ. Full-filter totals. Owner/manager/accountant scoped; payroll rows and bonus excluded for manager. */
    get: operations['reportRows'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/reports/export.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current READ ONLY REPEATABLE READ; independent reads may differ. Full-filter totals. Owner/manager/accountant scoped; payroll rows and bonus excluded for manager. */
    get: operations['reportCsv'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/report/drilldown': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Current read-only source explanations. Fresh actor inside RR; scalar children; anonymous salary sources for managers. */
    get: {
      parameters: {
        query: {
          mode?: string;
          store?: string;
          from?: string;
          to?: string;
          as_of?: string;
          metric: string;
          source?: string;
          page?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description One source page and full exact total. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Sources'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Summary:
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          mode: 'period';
          store: number | null;
          scope_name: string;
          /** Format: date-time */
          generated_at: string;
          /** @constant */
          basis: 'accounting_dates';
          /** @constant */
          reversal_policy: 'kyiv_reversed_at';
          /** @constant */
          snapshot: 'current';
          snapshot_notice: string;
          can_view_payroll: boolean;
          /** Format: date */
          from: string;
          /** Format: date */
          to: string;
          revenue: string;
          cogs: string;
          expenses: string;
          payroll: string;
          writeoffs: string;
          inventory_adjustment: string;
          supplier_return_variance: string;
          cash_difference: string;
          cash_net: string;
          gross_profit: string;
          profit: string;
          unallocated_expenses: string;
          /** @constant */
          cashiers_basis: 'current_posted_closed_shifts';
          /** @constant */
          debts_basis: 'current';
          counts: {
            products: number;
            by_store: number;
            expenses_by_category: number;
            cashiers: number;
          };
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          mode: 'balances';
          store: number | null;
          scope_name: string;
          /** Format: date-time */
          generated_at: string;
          /** @constant */
          basis: 'accounting_dates';
          /** @constant */
          reversal_policy: 'kyiv_reversed_at';
          /** @constant */
          snapshot: 'current';
          snapshot_notice: string;
          can_view_payroll: boolean;
          /** Format: date */
          as_of: string;
          stock_value: string;
          cash_total: string;
          debt_totals: {
            owed_to_us: string;
            owed_by_us: string;
          };
          advance_totals: {
            customer: string;
            supplier: string;
          };
          counts: {
            stock: number;
            cash: number;
            debts: number;
            advances: number;
            payroll_debts?: number;
          };
        };
    Page:
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'products';
          items: components['schemas']['Row_products'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'by_store';
          items: components['schemas']['Row_by_store'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'expenses_by_category';
          items: components['schemas']['Row_expenses_by_category'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'cashiers';
          items: components['schemas']['Row_cashiers'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'stock';
          items: components['schemas']['Row_stock'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'cash';
          items: components['schemas']['Row_cash'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'debts';
          items: components['schemas']['Row_debts'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'advances';
          items: components['schemas']['Row_advances'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        }
      | {
          /** @constant */
          contract: 'trading-reports-v1';
          /** @constant */
          section: 'payroll_debts';
          items: components['schemas']['Row_payroll_debts'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          limit: 30;
          q: string;
          summary: components['schemas']['Summary'];
        };
    Row_products: {
      product: string;
      name: string;
      unit: string;
      revenue: string;
      cogs: string;
      gross_profit: string;
      writeoff: string;
      inventory: string;
      result: string;
      quantity: string;
      writeoff_quantity: string;
      margin: string | null;
    };
    Row_by_store: {
      store: number;
      name: string;
      revenue: string;
      cogs: string;
      expenses: string;
      payroll: string;
      writeoffs: string;
      inventory_adjustment: string;
      supplier_return_variance: string;
      cash_difference: string;
      cash_net: string;
      gross_profit: string;
      profit: string;
    };
    Row_expenses_by_category: {
      store: number | null;
      /** @enum {unknown} */
      scope: 'network' | 'store';
      store_name: string | null;
      category: string;
      amount: string;
    };
    Row_cashiers: {
      employee: number | null;
      name: string;
      shifts: number;
      with_difference: number;
      shortage: string;
      surplus: string;
      net: string;
      revenue: string;
      late_return_bonus?: string;
      hours: string;
      revenue_per_hour: string | null;
    };
    Row_stock: {
      lot: number;
      code: string;
      warehouse: number;
      warehouse_name: string;
      store: number;
      product: string;
      name: string;
      unit: string;
      expiry: string | null;
      quantity: string;
      value: string;
      expired: boolean;
    };
    Row_cash: {
      account: number;
      name: string;
      store: number;
      kind: string;
      amount: string;
    };
    Row_debts: {
      voucher: number;
      number: string;
      /** @enum {unknown} */
      kind: 'sale' | 'receipt';
      /** @enum {unknown} */
      original_kind: 'sale' | 'receipt' | 'debt_opening';
      store: number;
      /** Format: date */
      date: string;
      party: string;
      party_id: number;
      total: string;
      amount: string;
      due_date: string;
      overdue: boolean;
    };
    Row_advances: {
      payment: number;
      number: string;
      store: number;
      party_id: number;
      party: string;
      /** @enum {unknown} */
      direction: 'customer' | 'supplier';
      /** Format: date */
      date: string;
      amount: string;
    };
    Row_payroll_debts: {
      employee: number;
      name: string;
      store: number;
      amount: string;
    };
    SourceRow:
      | {
          /** @constant */
          type: 'voucher';
          metric: string;
          amount: string;
          /** @enum {unknown} */
          sign: -1 | 1;
          /** Format: date */
          date: string;
          /** Format: date */
          voucher_date: string;
          reversal: boolean;
          store: number;
          kind: string;
          voucher: number | null;
          number: string | null;
          canOpen: boolean;
          entry?: number;
          quantity?: string;
        }
      | {
          /** @constant */
          type: 'aggregate';
          metric: string;
          amount: string;
          label: string;
          /** @constant */
          canOpen: false;
        };
    Sources:
      | {
          /** @constant */
          contract: 'trading-report-sources-v1';
          /** @constant */
          limit: 30;
          store: number | null;
          policy: {
            /** @enum {unknown} */
            role: 'owner' | 'manager' | 'accountant';
            store: number | null;
          };
          metric: string;
          title: string;
          formula: string;
          amount: string;
          items: components['schemas']['SourceRow'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          snapshot: 'current';
          /** @constant */
          basis: 'accounting_dates';
          /** @constant */
          reversal_policy: 'kyiv_reversed_at';
          snapshot_notice: string;
          /** @constant */
          mode: 'period';
          /** Format: date */
          from: string;
          /** Format: date */
          to: string;
        }
      | {
          /** @constant */
          contract: 'trading-report-sources-v1';
          /** @constant */
          limit: 30;
          store: number | null;
          policy: {
            /** @enum {unknown} */
            role: 'owner' | 'manager' | 'accountant';
            store: number | null;
          };
          metric: string;
          title: string;
          formula: string;
          amount: string;
          items: components['schemas']['SourceRow'][];
          total: number;
          page: number;
          pages: number;
          /** @constant */
          snapshot: 'current';
          /** @constant */
          basis: 'accounting_dates';
          /** @constant */
          reversal_policy: 'kyiv_reversed_at';
          snapshot_notice: string;
          /** @constant */
          mode: 'balances';
          /** Format: date */
          as_of: string;
          source: number;
        };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  reportSummary: {
    parameters: {
      query?: {
        mode?: 'period' | 'balances';
        store?: number;
        from?: string;
        to?: string;
        as_of?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current accounting-date read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Summary'];
        };
      };
      /** @description Invalid filters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role/section forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reportRows: {
    parameters: {
      query: {
        mode?: 'period' | 'balances';
        store?: number;
        from?: string;
        to?: string;
        as_of?: string;
        section:
          | 'products'
          | 'by_store'
          | 'expenses_by_category'
          | 'cashiers'
          | 'stock'
          | 'cash'
          | 'debts'
          | 'advances'
          | 'payroll_debts';
        q?: string;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current accounting-date read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page'];
        };
      };
      /** @description Invalid filters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role/section forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reportCsv: {
    parameters: {
      query?: {
        mode?: 'period' | 'balances';
        store?: number;
        from?: string;
        to?: string;
        as_of?: string;
        section?:
          | 'products'
          | 'by_store'
          | 'expenses_by_category'
          | 'cashiers'
          | 'stock'
          | 'cash'
          | 'debts'
          | 'advances'
          | 'payroll_debts'
          | 'summary'
          | 'all';
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current accounting-date read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
      /** @description Invalid filters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role/section forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
