/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/sales/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['salesDocuments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/sales/cash-shifts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['salesCashShifts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SalesQuery: {
      q: string;
      store: number | null;
      /** @enum {string} */
      status: '' | 'draft' | 'posted' | 'reversed';
      /** @enum {string} */
      kind: '' | 'sale' | 'customer_return' | 'customer_order';
      from: string;
      to: string;
    };
    CashShiftQuery: {
      store: number | null;
      employee: number | null;
      /** @enum {string} */
      status: '' | 'open' | 'closed';
      from: string;
      to: string;
    };
    SalesPolicy: {
      /** @enum {string} */
      role: 'owner' | 'manager' | 'cashier';
      store: number | null;
      documentKinds: ('sale' | 'customer_return' | 'customer_order')[];
    };
    SalesDocument: {
      id: number;
      number: string;
      /** @enum {string} */
      kind: 'sale' | 'customer_return' | 'customer_order';
      /** @enum {string} */
      status: 'draft' | 'posted' | 'reversed';
      /** Format: date */
      date: string;
      store: number;
      storeName: string;
      party: number | null;
      partyName: string;
      employee: number | null;
      employeeName: string;
      total: string;
      revision: number;
    };
    CashShift: {
      id: number;
      store: number;
      storeName: string;
      account: number;
      accountName: string;
      employee: number | null;
      employeeName: string;
      /** Format: date-time */
      openedAt: string;
      /** Format: date-time */
      closedAt: string | null;
      openedBy: string;
      openingCash: string;
      expectedCash: string | null;
      countedCash: string | null;
      difference: string | null;
      canClose: boolean;
    };
    SalesDocuments: {
      items: components['schemas']['SalesDocument'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
      query: components['schemas']['SalesQuery'];
      policy: components['schemas']['SalesPolicy'];
      fiscalRequired: boolean;
    };
    CashShifts: {
      items: components['schemas']['CashShift'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
      query: components['schemas']['CashShiftQuery'];
      policy: components['schemas']['SalesPolicy'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  salesDocuments: {
    parameters: {
      query?: {
        q?: string;
        store?: number | null;
        status?: '' | 'draft' | 'posted' | 'reversed';
        kind?: '' | 'sale' | 'customer_return' | 'customer_order';
        from?: string;
        to?: string;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bounded scalar snapshot with fresh policy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SalesDocuments'];
        };
      };
      /** @description Invalid query */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Current role denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read-only endpoint */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  salesCashShifts: {
    parameters: {
      query?: {
        store?: number | null;
        employee?: number | null;
        status?: '' | 'open' | 'closed';
        from?: string;
        to?: string;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bounded scalar snapshot with fresh policy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CashShifts'];
        };
      };
      /** @description Invalid query */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Current role denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read-only endpoint */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
