/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/staff/employees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['staffEmployees'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/staff/work-shifts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['staffWorkShifts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/staff/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['staffDocuments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    StaffPolicy: {
      /** @enum {string} */
      role: 'owner' | 'accountant';
      store: number | null;
      canManageEmployees: boolean;
      canWriteWorkShifts: boolean;
      documentKinds: ('payroll' | 'payroll_payment')[];
      closedThrough: string | null;
    };
    StaffEmployee: {
      id: number;
      store: number;
      storeName: string;
      name: string;
      active: boolean;
      shiftRate: string;
      bonusPercent: string;
      /** @enum {string} */
      bonusBasis: 'store' | 'personal' | 'profit';
      payrollDebt: string;
      revision: string | null;
    };
    StaffWorkShift: {
      id: number;
      store: number;
      storeName: string;
      employee: number;
      employeeName: string;
      employeeActive: boolean;
      /** Format: date */
      date: string;
      cashShift: number | null;
      units: string;
      shiftRate: string;
      bonusPercent: string;
      /** @enum {string} */
      bonusBasis: 'store' | 'personal' | 'profit';
      basisAmount: string;
      accrued: string;
      payroll: number | null;
      revision: string;
      canEdit: boolean;
    };
    StaffDocument: {
      id: number;
      store: number;
      storeName: string;
      number: string;
      /** @enum {string} */
      kind: 'payroll' | 'payroll_payment';
      /** @enum {string} */
      status: 'draft' | 'posted' | 'reversed';
      /** Format: date */
      date: string;
      employee: number | null;
      employeeName: string;
      total: string;
      revision: number;
    };
    StaffEmployeesQuery: {
      q: string;
      store: number | null;
    };
    StaffEmployeesPage: {
      items: components['schemas']['StaffEmployee'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      query: components['schemas']['StaffEmployeesQuery'];
      policy: components['schemas']['StaffPolicy'];
    };
    StaffWorkShiftsQuery: {
      store: number | null;
      employee: number | null;
      from: string;
      to: string;
    };
    StaffWorkShiftsPage: {
      items: components['schemas']['StaffWorkShift'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      query: components['schemas']['StaffWorkShiftsQuery'];
      policy: components['schemas']['StaffPolicy'];
    };
    StaffDocumentsQuery: {
      store: number | null;
      /** @enum {string} */
      status: '' | 'draft' | 'posted' | 'reversed';
    };
    StaffDocumentsPage: {
      items: components['schemas']['StaffDocument'][];
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      query: components['schemas']['StaffDocumentsQuery'];
      policy: components['schemas']['StaffPolicy'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  staffEmployees: {
    parameters: {
      query?: {
        q?: string;
        store?: number;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped read-only snapshot; no salary mutation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StaffEmployeesPage'];
        };
      };
    };
  };
  staffWorkShifts: {
    parameters: {
      query?: {
        store?: number;
        employee?: number;
        from?: string;
        to?: string;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped read-only snapshot; no salary mutation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StaffWorkShiftsPage'];
        };
      };
    };
  };
  staffDocuments: {
    parameters: {
      query?: {
        store?: number;
        status?: '' | 'draft' | 'posted' | 'reversed';
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh scoped read-only snapshot; no salary mutation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StaffDocumentsPage'];
        };
      };
    };
  };
}
