/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/stock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          q?: string;
          store?: number;
          warehouse?: number;
          page?: number;
          view?: 'totals' | 'lots';
          sort?: 'warehouse_product';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current scoped RR snapshot */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StockPage'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/assortment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          warehouse: number;
          q?: string;
          page?: number;
          product?: string;
          sort?: 'name';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current scoped RR snapshot */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AssortmentPage'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AssortmentRequest'];
        };
      };
      responses: {
        /** @description Saved current row, not an immutable receipt */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AssortmentAck'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/stock/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          store?: number;
          status?: '' | 'draft' | 'posted' | 'reversed';
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current scoped RR snapshot */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StockDocuments'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/stock.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          q?: string;
          store?: number;
          warehouse?: number;
          view?: 'totals';
          sort?: 'warehouse_product';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Whole filtered streamed CSV, private costs only when authorized */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/csv': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    StockPolicy: {
      /** @enum {string} */
      role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
      store: number | null;
      costVisible: boolean;
      canEditAssortment: boolean;
      documentKinds: ('opening' | 'transfer' | 'writeoff' | 'inventory' | 'production')[];
      canControl: boolean;
      canLegacyRecipes: boolean;
      canRecipeVersions: boolean;
      canReplenish: boolean;
    };
    StockQuery: {
      q: string;
      store: number | null;
      warehouse: number | null;
      /** @enum {string} */
      view: 'totals' | 'lots';
    };
    StockTotal: {
      warehouse: number;
      product: string;
      name: string;
      unit: string;
      sold: boolean;
      low: boolean;
      quantity: string;
      available: string;
      reserved: string;
      minimum: string;
      value?: string;
    };
    StockLot: {
      id: number;
      warehouse: number;
      product: string;
      name: string;
      unit: string;
      lot: string;
      /** Format: date */
      expiry: string | null;
      expired: boolean;
      quantity: string;
      available: string;
      reserved: string;
      value?: string;
    };
    StockSummary: {
      products: number;
      low: number;
      lots: number;
      expiry: number;
      value?: string;
    };
    StockPage: {
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      items: (components['schemas']['StockTotal'] | components['schemas']['StockLot'])[];
      /** @enum {string} */
      view: 'totals' | 'lots';
      summary: components['schemas']['StockSummary'];
      query: components['schemas']['StockQuery'];
      /** Format: date */
      asOf: string;
      policy: components['schemas']['StockPolicy'];
      alerts: {
        ok: {
          [key: string]: unknown;
        } | null;
        error: {
          [key: string]: unknown;
        } | null;
        stale: boolean;
      } | null;
    };
    AssortmentRow: {
      product: string;
      name: string;
      unit: string;
      default_min: string;
      sold: boolean;
      min_stock: string | null;
      minimum: string;
      revision: string | null;
    };
    AssortmentPage: {
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      warehouse: number;
      rows: components['schemas']['AssortmentRow'][];
      query: {
        q: string;
        product: string;
      };
      policy: components['schemas']['StockPolicy'];
    };
    AssortmentRequest: {
      warehouse: number;
      product: string;
      sold: boolean;
      min_stock: string | null;
      revision: string | null;
    };
    AssortmentAck: {
      warehouse: number;
      row: components['schemas']['AssortmentRow'];
      policy: components['schemas']['StockPolicy'];
    };
    StockDocument: {
      id: number;
      number: string;
      /** @enum {string} */
      kind: 'opening' | 'transfer' | 'writeoff' | 'inventory' | 'production';
      /** @enum {string} */
      status: 'draft' | 'posted' | 'reversed';
      /** Format: date */
      date: string;
      store: number;
      party: number | null;
      employee: number | null;
      total: string;
      revision: number;
    };
    StockDocuments: {
      total: number;
      page: number;
      pages: number;
      /** @enum {integer} */
      limit: 30;
      items: components['schemas']['StockDocument'][];
      query: {
        store: number | null;
        /** @enum {string} */
        status: '' | 'draft' | 'posted' | 'reversed';
      };
      policy: components['schemas']['StockPolicy'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
