/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingBootstrap'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/directories/{type}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingDirectory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/products/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingProductLookup'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/directories/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read-only selection hydration; CSRF required. No business state, revision, receipt or audit is changed. Read-only repeatable-read snapshot. */
    post: operations['tradingSelectedDetails'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/products/template.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingProductTemplate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/entities/{type}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Create with immutable UUID receipt. Legacy no-key creates and revision-bound updates retain legacy contracts. Current actor/role/store policy under ledger lock before receipt lookup. */
    post: operations['createEntityWithReceipt'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/entities/{type}/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description CSRF-protected non-business read, real READ ONLY REPEATABLE READ. Exact original UUID/body/author/resource and current policy required. Does not create, mutate, audit or adopt a current revision. */
    post: operations['readEntityCreateIdentity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/vouchers/recovery-context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Read-only fresh actor/scope authorization. Invalid raw date, closed period or inactive store return canEdit false without denying draft viewing. No write or revision adoption. */
    get: operations['voucherDraftContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/vouchers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Atomic voucher CREATE remains the legacy contract. A bound 400 proof means this HTTP attempt rolled back; it never proves absence of an earlier request with the same key. */
    post: operations['createNativeVoucher'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/entities/{type}/recovery-context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['entityRecoveryContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/work-shifts/recovery-context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Fresh actor, scope and REPEATABLE READ READ ONLY. No business write. Identity is creator-bound; ID never supplies the current revision. */
    get: operations['workShiftRecoveryContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/work-shifts/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Fresh actor, scope and REPEATABLE READ READ ONLY. No business write. Identity is creator-bound; ID never supplies the current revision. */
    get: operations['workShiftCurrent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/work-shifts/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Fresh actor, scope and REPEATABLE READ READ ONLY. No business write. Identity is creator-bound; ID never supplies the current revision. */
    post: operations['workShiftIdentity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/cash-shifts/recovery-context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['cashShiftRecoveryContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/cash-shifts/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['cashShiftCurrent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/cash-shifts/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['cashShiftIdentity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/shifts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description One explicit till open or close under the ledger lock. Exact UUID retry checks fresh access then returns immutable receipt before mutable status/activity/revision checks; no repeated writes/audit. Validation/revision proof only describes initial rolled-back attempt, never global absence. */
    post: operations['cashShiftAction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/settings/{setting}/recovery-context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['settingRecoveryContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/settings/{setting}/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['settingCurrent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/settings/{setting}/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['settingIdentity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/period': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Optional UUID+revision receipt protocol. No-key legacy contract is unchanged. Exact creator/fingerprint replay after fresh owner authorization precedes current-version/business checks. Bound first-live rejection only after rollback; current state is not authorship. */
    post: operations['settingWritePeriod'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/fiscal': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Optional UUID+revision receipt protocol. No-key legacy contract is unchanged. Exact creator/fingerprint replay after fresh owner authorization precedes current-version/business checks. Bound first-live rejection only after rollback; current state is not authorship. */
    post: operations['settingWriteFiscal'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/discount-limit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Optional UUID+revision receipt protocol. No-key legacy contract is unchanged. Exact creator/fingerprint replay after fresh owner authorization precedes current-version/business checks. Bound first-live rejection only after rollback; current state is not authorship. */
    post: operations['settingWriteDiscountLimit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DirectoryItem: {
      id: string;
      name: string;
      store_id?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'supplier' | 'customer' | 'cash' | 'bank' | 'terminal';
      phone?: string;
      email?: string;
      notes?: string;
      revision?: string;
      unit?: string;
      barcode?: string;
      hidden?: boolean;
      promotion?: boolean;
      cost?: string;
      regularPrice?: string;
      salePrice?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
      balance?: string;
      payroll_debt?: string;
      semantic_key?: string;
      account_id?: number;
    };
    /** @enum {string} */
    DirectoryType:
      | 'stores'
      | 'warehouses'
      | 'accounts'
      | 'employees'
      | 'parties'
      | 'products'
      | 'expense_categories'
      | 'cash_shifts';
    DirectoryPage: {
      items: components['schemas']['DirectoryItem'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
    };
    DirectoryRef: {
      type: components['schemas']['DirectoryType'];
      id: string;
    };
    DirectoryDetail: {
      type: components['schemas']['DirectoryType'];
      id: string;
      name: string;
      store_id?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'supplier' | 'customer' | 'cash' | 'bank' | 'terminal';
      phone?: string;
      email?: string;
      notes?: string;
      revision?: string;
      unit?: string;
      barcode?: string;
      hidden?: boolean;
      promotion?: boolean;
      cost?: string;
      regularPrice?: string;
      salePrice?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
      balance?: string;
      payroll_debt?: string;
      semantic_key?: string;
      account_id?: number;
    };
    DirectoryDetailsRequest: {
      ids: components['schemas']['DirectoryRef'][];
      store?: number;
      purpose?: string;
    };
    DirectoryDetails: {
      items: components['schemas']['DirectoryDetail'][];
      unavailable: components['schemas']['DirectoryRef'][];
    };
    TradingBootstrap: {
      csrf: string;
      /** @enum {string} */
      role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
      username: string;
      storeId: number | null;
      defaultStoreId: number | null;
      canViewAudit: boolean;
      /** Format: date */
      closed_through: string | null;
      fiscal_required: boolean;
      max_discount: string;
      alerts_status?: {
        [key: string]: unknown;
      };
      defaultCategoryId: string;
    };
    Error: {
      error: string;
      code?: string;
    };
    EntityCreateRequest: {
      name: string;
      /** Format: uuid */
      idempotency_key: string;
      store?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'cash' | 'bank' | 'terminal' | 'customer' | 'supplier';
      phone?: string;
      email?: string;
      notes?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
    };
    /** @description Immutable original fields. Employee private terms only under current owner policy. */
    EntityOriginalRecord:
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'stores';
          active: boolean;
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'warehouses';
          store_id: number;
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'accounts';
          store_id: number;
          /** @enum {string} */
          kind: 'cash' | 'bank' | 'terminal';
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'employees';
          store_id: number;
          active: boolean;
          shift_rate: string;
          bonus_percent: string;
          /** @enum {string} */
          bonus_basis: 'store' | 'personal' | 'profit';
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'parties';
          active: boolean;
          /** @enum {string} */
          kind: 'customer' | 'supplier';
          phone: string;
          email: string;
          notes: string;
        };
    /** @description Exact frozen request receipt, never a current editable revision. Identical retry after edit/deletion returns initial acknowledgement without writes. */
    EntityCreateAcknowledgement: {
      id: string;
      /** @enum {string} */
      type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      /** Format: uuid */
      request_key: string;
      original: components['schemas']['EntityOriginalRecord'];
    };
    EntityCreateIdentity:
      | {
          /** @constant */
          confirmed: false;
          /** @enum {string} */
          type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
          /** Format: uuid */
          request_key: string;
        }
      | {
          /** @constant */
          confirmed: true;
          exists: boolean;
          id: string;
          /** @enum {string} */
          type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
          /** Format: uuid */
          request_key: string;
          original: components['schemas']['EntityOriginalRecord'];
        };
    VoucherDraftContext: {
      kind: string;
      store: number;
      editing: {
        /** @enum {string} */
        role: 'owner' | 'manager' | 'cashier' | 'warehouse' | 'accountant';
        storeId: number | null;
        /** Format: date */
        closedThrough: string | null;
        storeActive: boolean;
        canEdit: boolean;
      };
    };
    VoucherCreateRejected: {
      error: string;
      /** @constant */
      write_rejected: true;
      /** Format: uuid */
      request_key: string;
      kind: string;
    };
    EntityRecoveryContext: {
      /** @enum {string} */
      type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      id: string | null;
      store: number | null;
      /** @enum {string} */
      role: 'owner' | 'manager' | 'accountant' | 'warehouse' | 'cashier';
      storeId: number | null;
      networkOwner: boolean;
      canCreate: boolean;
      exists: boolean | null;
    };
    WorkShiftCreateRequest: {
      employee: string;
      date: string;
      cash_shift: string;
      units: string;
      shift_rate: string;
      bonus_percent: string;
      bonus_basis: string;
      note: string;
      /** Format: uuid */
      idempotency_key: string;
    };
    WorkShiftCreateAcknowledgement: {
      id: number;
      /** @constant */
      type: 'work_shift';
      /** Format: uuid */
      request_key: string;
      request: components['schemas']['WorkShiftCreateRequest'];
    };
    WorkShiftCreateIdentity:
      | {
          /** @constant */
          confirmed: false;
          /** @constant */
          type: 'work_shift';
          /** Format: uuid */
          request_key: string;
        }
      | {
          /** @constant */
          confirmed: true;
          id: number;
          /** @constant */
          type: 'work_shift';
          /** Format: uuid */
          request_key: string;
          request: components['schemas']['WorkShiftCreateRequest'];
        };
    WorkShiftRecoveryContext: {
      /** @constant */
      type: 'work_shift';
      id: number | null;
      store: number | null;
      employee: number | null;
      /** @enum {unknown} */
      role: 'owner' | 'accountant';
      storeId: number | null;
      networkOwner: boolean;
      exists: boolean | null;
      canEdit: boolean;
    };
    WorkShiftRead: {
      date: string;
      units: string;
      shift_rate: string;
      bonus_percent: string;
      bonus_basis: string;
      accrued: string;
      basis_amount: string;
      note: string;
      revision: string;
      id: number;
      employee_id: number;
      store_id: number;
      cash_shift_id: number | null;
      payroll_id: number | null;
    };
    WorkShiftExactPage: {
      items: components['schemas']['WorkShiftRead'][];
      /** @constant */
      total: 1;
      /** @constant */
      page: 1;
      /** @constant */
      pages: 1;
    };
    /** @description Optional UUID extension; unkeyed legacy /api/erp/shifts behavior remains unchanged. Close revision binds only CashShift stored fields, never live account balance. */
    CashShiftActionRequest:
      | {
          /** @enum {string} */
          action: 'open';
          account: number | string;
          employee: (number | null) | string;
          /** Format: uuid */
          idempotency_key: string;
        }
      | {
          /** @enum {string} */
          action: 'close';
          id: number | string;
          counted: string;
          note: string;
          revision: string;
          /** Format: uuid */
          idempotency_key: string;
        };
    CashShiftActionOriginal:
      | {
          /** @enum {string} */
          action: 'open';
          account: number;
          employee: number | null;
        }
      | {
          /** @enum {string} */
          action: 'close';
          id: number;
          counted: string;
          note: string;
          revision: string;
        };
    CashShiftActionReceipt: {
      id: number;
      /** @enum {string} */
      type: 'cash_shift';
      /** @enum {string} */
      action: 'open' | 'close';
      /** Format: uuid */
      request_key: string;
      original: components['schemas']['CashShiftActionOriginal'];
    };
    CashShiftRecoveryContext: {
      /** @enum {string} */
      type: 'cash_shift';
      /** @enum {string} */
      action: 'open' | 'close';
      id: number | null;
      account: number | null;
      store: number | null;
      /** @enum {string} */
      role: 'owner' | 'manager' | 'cashier';
      storeId: number | null;
      networkOwner: boolean;
      canWrite: boolean;
    };
    CashShiftCurrent: {
      id: number;
      store: number;
      account: number;
      employee: number | null;
      openedBy: number;
      /** Format: date-time */
      openedAt: string;
      /** Format: date-time */
      closedAt: string | null;
      openingCash: string;
      expectedCash: string | null;
      countedCash: string | null;
      note: string;
      revision: string;
      editing: {
        /** @enum {string} */
        role: 'owner' | 'manager' | 'cashier';
        storeId: number | null;
        networkOwner: boolean;
        canWrite: boolean;
      };
    };
    /** @description Positive identity binds creator and full normalized frozen request. Missing receipt=false does not authorize clearing an unknown intent; current state/revision is a separate read. */
    CashShiftActionIdentity:
      | {
          /** @enum {boolean} */
          confirmed: true;
          id: number;
          /** @enum {string} */
          type: 'cash_shift';
          /** @enum {string} */
          action: 'open' | 'close';
          /** Format: uuid */
          request_key: string;
          original: components['schemas']['CashShiftActionOriginal'];
        }
      | {
          /** @enum {boolean} */
          confirmed: false;
          /** @enum {string} */
          type: 'cash_shift';
          /** @enum {string} */
          action: 'open' | 'close';
          /** Format: uuid */
          request_key: string;
        };
    SettingEditingPolicy: {
      /** @constant */
      role: 'owner';
      storeId: number | null;
      networkOwner: boolean;
      /** @constant */
      canWrite: true;
    };
    SettingValue:
      | {
          /** Format: date */
          date: string | null;
          reason: string;
        }
      | {
          required: boolean;
        }
      | {
          percent: string;
        };
    SettingOriginal:
      | {
          /** Format: date */
          date: string | null;
          reason: string;
          revision: string;
        }
      | {
          required: boolean;
          revision: string;
        }
      | {
          percent: string;
          revision: string;
        };
    SettingActionRequest:
      | {
          /** Format: date */
          date: string | null;
          reason: string;
          revision: string;
          /** Format: uuid */
          idempotency_key: string;
        }
      | {
          required: boolean;
          revision: string;
          /** Format: uuid */
          idempotency_key: string;
        }
      | {
          percent: string;
          revision: string;
          /** Format: uuid */
          idempotency_key: string;
        };
    SettingContext: {
      /** @constant */
      type: 'setting';
      /** @enum {string} */
      setting: 'period' | 'fiscal' | 'discount-limit';
      /** @constant */
      role: 'owner';
      storeId: number | null;
      networkOwner: boolean;
      /** @constant */
      canWrite: true;
    };
    SettingCurrent: {
      /** @constant */
      type: 'setting';
      /** @enum {string} */
      setting: 'period' | 'fiscal' | 'discount-limit';
      value: components['schemas']['SettingValue'];
      revision: string;
      editing: components['schemas']['SettingEditingPolicy'];
    };
    SettingAcknowledgement: {
      /** @constant */
      type: 'setting';
      /** @enum {string} */
      setting: 'period' | 'fiscal' | 'discount-limit';
      /** Format: uuid */
      request_key: string;
      original: components['schemas']['SettingOriginal'];
      value: components['schemas']['SettingValue'];
      revision: string;
    };
    SettingIdentityRequest: {
      request: components['schemas']['SettingActionRequest'];
    };
    SettingIdentityResult:
      | {
          /** @constant */
          confirmed: false;
          /** @constant */
          type: 'setting';
          /** @enum {string} */
          setting: 'period' | 'fiscal' | 'discount-limit';
          /** Format: uuid */
          request_key: string;
        }
      | {
          /** @constant */
          confirmed: true;
          /** @constant */
          type: 'setting';
          /** @enum {string} */
          setting: 'period' | 'fiscal' | 'discount-limit';
          /** Format: uuid */
          request_key: string;
          original: components['schemas']['SettingOriginal'];
          value: components['schemas']['SettingValue'];
          revision: string;
        };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  tradingBootstrap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TradingBootstrap'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingDirectory: {
    parameters: {
      query?: {
        q?: string;
        store?: string;
        purpose?: string;
        active?: string;
        kind?: string;
        sort?: string;
        exclude?: string;
        mode?: string;
        page?: string;
      };
      header?: never;
      path: {
        type: components['schemas']['DirectoryType'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryPage'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingProductLookup: {
    parameters: {
      query?: {
        q?: string;
        store?: string;
        purpose?: string;
        active?: string;
        kind?: string;
        sort?: string;
        exclude?: string;
        mode?: string;
        page?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryPage'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingSelectedDetails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DirectoryDetailsRequest'];
      };
    };
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryDetails'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingProductTemplate: {
    parameters: {
      query?: {
        purpose?: 'opening' | 'receipt' | 'inventory';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Full eligible product template; versioned formula-safe streaming CSV */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  createEntityWithReceipt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntityCreateRequest'];
      };
    };
    responses: {
      /** @description Immutable acknowledgement; current row must be read separately */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityCreateAcknowledgement'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  readEntityCreateIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          request: components['schemas']['EntityCreateRequest'];
        };
      };
    };
    responses: {
      /** @description Immutable acknowledgement; current row must be read separately */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityCreateIdentity'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  voucherDraftContext: {
    parameters: {
      query: {
        kind: string;
        store: string;
        date?: string;
        expense_scope?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorized context */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VoucherDraftContext'];
        };
      };
      /** @description Invalid context */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role/store access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createNativeVoucher: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Legacy user-policy-redacted voucher ACK with request_key */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error; optional bound no-write proof */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            components['schemas']['Error'] | components['schemas']['VoucherCreateRejected'];
        };
      };
      /** @description Authorization failure without no-write proof */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict without no-write proof */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  entityRecoveryContext: {
    parameters: {
      query?: {
        id?: string;
        store?: number;
      };
      header?: never;
      path: {
        type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh read-only resource authorization, without validating newer raw fields */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityRecoveryContext'];
        };
      };
      /** @description Resource scope unavailable */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  workShiftRecoveryContext: {
    parameters: {
      query?: {
        id?: number;
        store?: number;
        employee?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorized read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkShiftRecoveryContext'];
        };
      };
      /** @description Read denied or malformed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  workShiftCurrent: {
    parameters: {
      query: {
        id: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorized read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkShiftExactPage'];
        };
      };
      /** @description Read denied or malformed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  workShiftIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          request: components['schemas']['WorkShiftCreateRequest'];
        };
      };
    };
    responses: {
      /** @description Authorized read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkShiftCreateIdentity'];
        };
      };
      /** @description Read denied or malformed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Read denied or malformed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cashShiftRecoveryContext: {
    parameters: {
      query?: {
        action?: 'open' | 'close';
        id?: number;
        account?: number;
        store?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorized READ ONLY snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CashShiftRecoveryContext'];
        };
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cashShiftCurrent: {
    parameters: {
      query: {
        id: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorized READ ONLY snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CashShiftCurrent'];
        };
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cashShiftIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          request: components['schemas']['CashShiftActionRequest'];
        };
      };
    };
    responses: {
      /** @description Authorized READ ONLY snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CashShiftActionIdentity'];
        };
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  cashShiftAction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CashShiftActionRequest'];
      };
    };
    responses: {
      /** @description Immutable exact acknowledgement */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CashShiftActionReceipt'];
        };
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Request refused; keep raw input. Only bound initial rolled-back write_rejected proves this live attempt was not committed. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  settingRecoveryContext: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        setting: 'period' | 'fiscal' | 'discount-limit';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh authorized READ ONLY RR result; identity does not adopt current baseline */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingContext'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Fresh owner permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Identity/revision conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  settingCurrent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        setting: 'period' | 'fiscal' | 'discount-limit';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fresh authorized READ ONLY RR result; identity does not adopt current baseline */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingCurrent'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Fresh owner permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Identity/revision conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  settingIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        setting: 'period' | 'fiscal' | 'discount-limit';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingIdentityRequest'];
      };
    };
    responses: {
      /** @description Fresh authorized READ ONLY RR result; identity does not adopt current baseline */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingIdentityResult'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Fresh owner permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Identity/revision conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  settingWritePeriod: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingActionRequest'];
      };
    };
    responses: {
      /** @description Fresh authorized READ ONLY RR result; identity does not adopt current baseline */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingAcknowledgement'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Fresh owner permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Identity/revision conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  settingWriteFiscal: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingActionRequest'];
      };
    };
    responses: {
      /** @description Fresh authorized READ ONLY RR result; identity does not adopt current baseline */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingAcknowledgement'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Fresh owner permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Identity/revision conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  settingWriteDiscountLimit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingActionRequest'];
      };
    };
    responses: {
      /** @description Fresh authorized READ ONLY RR result; identity does not adopt current baseline */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingAcknowledgement'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Fresh owner permission denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Identity/revision conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
}
