/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingBootstrap'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/directories/{type}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingDirectory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/products/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingProductLookup'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/directories/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read-only selection hydration; CSRF required. No business state, revision, receipt or audit is changed. Read-only repeatable-read snapshot. */
    post: operations['tradingSelectedDetails'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/products/template.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingProductTemplate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DirectoryItem: {
      id: string;
      name: string;
      store_id?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'supplier' | 'customer' | 'cash' | 'bank' | 'terminal';
      phone?: string;
      email?: string;
      notes?: string;
      revision?: string;
      unit?: string;
      barcode?: string;
      hidden?: boolean;
      promotion?: boolean;
      cost?: string;
      regularPrice?: string;
      salePrice?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
      balance?: string;
      payroll_debt?: string;
      semantic_key?: string;
      account_id?: number;
    };
    /** @enum {string} */
    DirectoryType:
      | 'stores'
      | 'warehouses'
      | 'accounts'
      | 'employees'
      | 'parties'
      | 'products'
      | 'expense_categories'
      | 'cash_shifts';
    DirectoryPage: {
      items: components['schemas']['DirectoryItem'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
    };
    DirectoryRef: {
      type: components['schemas']['DirectoryType'];
      id: string;
    };
    DirectoryDetail: {
      type: components['schemas']['DirectoryType'];
      id: string;
      name: string;
      store_id?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'supplier' | 'customer' | 'cash' | 'bank' | 'terminal';
      phone?: string;
      email?: string;
      notes?: string;
      revision?: string;
      unit?: string;
      barcode?: string;
      hidden?: boolean;
      promotion?: boolean;
      cost?: string;
      regularPrice?: string;
      salePrice?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
      balance?: string;
      payroll_debt?: string;
      semantic_key?: string;
      account_id?: number;
    };
    DirectoryDetailsRequest: {
      ids: components['schemas']['DirectoryRef'][];
      store?: number;
      purpose?: string;
    };
    DirectoryDetails: {
      items: components['schemas']['DirectoryDetail'][];
      unavailable: components['schemas']['DirectoryRef'][];
    };
    TradingBootstrap: {
      csrf: string;
      /** @enum {string} */
      role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
      username: string;
      storeId: number | null;
      defaultStoreId: number | null;
      canViewAudit: boolean;
      /** Format: date */
      closed_through: string | null;
      fiscal_required: boolean;
      max_discount: string;
      alerts_status?: {
        [key: string]: unknown;
      };
      defaultCategoryId: string;
    };
    Error: {
      error: string;
      code?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  tradingBootstrap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TradingBootstrap'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingDirectory: {
    parameters: {
      query?: {
        q?: string;
        store?: string;
        purpose?: string;
        active?: string;
        kind?: string;
        sort?: string;
        exclude?: string;
        mode?: string;
        page?: string;
      };
      header?: never;
      path: {
        type: components['schemas']['DirectoryType'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryPage'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingProductLookup: {
    parameters: {
      query?: {
        q?: string;
        store?: string;
        purpose?: string;
        active?: string;
        kind?: string;
        sort?: string;
        exclude?: string;
        mode?: string;
        page?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryPage'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingSelectedDetails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DirectoryDetailsRequest'];
      };
    };
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryDetails'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingProductTemplate: {
    parameters: {
      query?: {
        purpose?: 'opening' | 'receipt' | 'inventory';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Full eligible product template; versioned formula-safe streaming CSV */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
}
