/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/trading/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingBootstrap'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/directories/{type}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingDirectory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/products/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingProductLookup'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/directories/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read-only selection hydration; CSRF required. No business state, revision, receipt or audit is changed. Read-only repeatable-read snapshot. */
    post: operations['tradingSelectedDetails'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/products/template.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['tradingProductTemplate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/entities/{type}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Create with immutable UUID receipt. Legacy no-key creates and revision-bound updates retain legacy contracts. Current actor/role/store policy under ledger lock before receipt lookup. */
    post: operations['createEntityWithReceipt'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/trading/entities/{type}/identity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description CSRF-protected non-business read, real READ ONLY REPEATABLE READ. Exact original UUID/body/author/resource and current policy required. Does not create, mutate, audit or adopt a current revision. */
    post: operations['readEntityCreateIdentity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/vouchers/recovery-context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Read-only fresh actor/scope authorization. Invalid raw date, closed period or inactive store return canEdit false without denying draft viewing. No write or revision adoption. */
    get: operations['voucherDraftContext'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/erp/vouchers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Atomic voucher CREATE remains the legacy contract. A bound 400 proof means this HTTP attempt rolled back; it never proves absence of an earlier request with the same key. */
    post: operations['createNativeVoucher'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DirectoryItem: {
      id: string;
      name: string;
      store_id?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'supplier' | 'customer' | 'cash' | 'bank' | 'terminal';
      phone?: string;
      email?: string;
      notes?: string;
      revision?: string;
      unit?: string;
      barcode?: string;
      hidden?: boolean;
      promotion?: boolean;
      cost?: string;
      regularPrice?: string;
      salePrice?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
      balance?: string;
      payroll_debt?: string;
      semantic_key?: string;
      account_id?: number;
    };
    /** @enum {string} */
    DirectoryType:
      | 'stores'
      | 'warehouses'
      | 'accounts'
      | 'employees'
      | 'parties'
      | 'products'
      | 'expense_categories'
      | 'cash_shifts';
    DirectoryPage: {
      items: components['schemas']['DirectoryItem'][];
      total: number;
      page: number;
      pages: number;
      /** @constant */
      limit: 30;
    };
    DirectoryRef: {
      type: components['schemas']['DirectoryType'];
      id: string;
    };
    DirectoryDetail: {
      type: components['schemas']['DirectoryType'];
      id: string;
      name: string;
      store_id?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'supplier' | 'customer' | 'cash' | 'bank' | 'terminal';
      phone?: string;
      email?: string;
      notes?: string;
      revision?: string;
      unit?: string;
      barcode?: string;
      hidden?: boolean;
      promotion?: boolean;
      cost?: string;
      regularPrice?: string;
      salePrice?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
      balance?: string;
      payroll_debt?: string;
      semantic_key?: string;
      account_id?: number;
    };
    DirectoryDetailsRequest: {
      ids: components['schemas']['DirectoryRef'][];
      store?: number;
      purpose?: string;
    };
    DirectoryDetails: {
      items: components['schemas']['DirectoryDetail'][];
      unavailable: components['schemas']['DirectoryRef'][];
    };
    TradingBootstrap: {
      csrf: string;
      /** @enum {string} */
      role: 'owner' | 'manager' | 'warehouse' | 'cashier' | 'accountant';
      username: string;
      storeId: number | null;
      defaultStoreId: number | null;
      canViewAudit: boolean;
      /** Format: date */
      closed_through: string | null;
      fiscal_required: boolean;
      max_discount: string;
      alerts_status?: {
        [key: string]: unknown;
      };
      defaultCategoryId: string;
    };
    Error: {
      error: string;
      code?: string;
    };
    EntityCreateRequest: {
      name: string;
      /** Format: uuid */
      idempotency_key: string;
      store?: number;
      active?: boolean;
      /** @enum {string} */
      kind?: 'cash' | 'bank' | 'terminal' | 'customer' | 'supplier';
      phone?: string;
      email?: string;
      notes?: string;
      shift_rate?: string;
      bonus_percent?: string;
      /** @enum {string} */
      bonus_basis?: 'store' | 'personal' | 'profit';
    };
    /** @description Immutable original fields. Employee private terms only under current owner policy. */
    EntityOriginalRecord:
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'stores';
          active: boolean;
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'warehouses';
          store_id: number;
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'accounts';
          store_id: number;
          /** @enum {string} */
          kind: 'cash' | 'bank' | 'terminal';
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'employees';
          store_id: number;
          active: boolean;
          shift_rate: string;
          bonus_percent: string;
          /** @enum {string} */
          bonus_basis: 'store' | 'personal' | 'profit';
        }
      | {
          id: string;
          name: string;
          revision: string;
          /** @constant */
          type: 'parties';
          active: boolean;
          /** @enum {string} */
          kind: 'customer' | 'supplier';
          phone: string;
          email: string;
          notes: string;
        };
    /** @description Exact frozen request receipt, never a current editable revision. Identical retry after edit/deletion returns initial acknowledgement without writes. */
    EntityCreateAcknowledgement: {
      id: string;
      /** @enum {string} */
      type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      /** Format: uuid */
      request_key: string;
      original: components['schemas']['EntityOriginalRecord'];
    };
    EntityCreateIdentity:
      | {
          /** @constant */
          confirmed: false;
          /** @enum {string} */
          type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
          /** Format: uuid */
          request_key: string;
        }
      | {
          /** @constant */
          confirmed: true;
          exists: boolean;
          id: string;
          /** @enum {string} */
          type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
          /** Format: uuid */
          request_key: string;
          original: components['schemas']['EntityOriginalRecord'];
        };
    VoucherDraftContext: {
      kind: string;
      store: number;
      editing: {
        /** @enum {string} */
        role: 'owner' | 'manager' | 'cashier' | 'warehouse' | 'accountant';
        storeId: number | null;
        /** Format: date */
        closedThrough: string | null;
        storeActive: boolean;
        canEdit: boolean;
      };
    };
    VoucherCreateRejected: {
      error: string;
      /** @constant */
      write_rejected: true;
      /** Format: uuid */
      request_key: string;
      kind: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  tradingBootstrap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TradingBootstrap'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingDirectory: {
    parameters: {
      query?: {
        q?: string;
        store?: string;
        purpose?: string;
        active?: string;
        kind?: string;
        sort?: string;
        exclude?: string;
        mode?: string;
        page?: string;
      };
      header?: never;
      path: {
        type: components['schemas']['DirectoryType'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryPage'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingProductLookup: {
    parameters: {
      query?: {
        q?: string;
        store?: string;
        purpose?: string;
        active?: string;
        kind?: string;
        sort?: string;
        exclude?: string;
        mode?: string;
        page?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryPage'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingSelectedDetails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DirectoryDetailsRequest'];
      };
    };
    responses: {
      /** @description Read-only authenticated result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryDetails'];
        };
      };
      /** @description Read-only authenticated result */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Read-only authenticated result */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  tradingProductTemplate: {
    parameters: {
      query?: {
        purpose?: 'opening' | 'receipt' | 'inventory';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Full eligible product template; versioned formula-safe streaming CSV */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
      /** @description Role, store scope or CSRF denies this read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  createEntityWithReceipt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntityCreateRequest'];
      };
    };
    responses: {
      /** @description Immutable acknowledgement; current row must be read separately */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityCreateAcknowledgement'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  readEntityCreateIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        type: 'stores' | 'warehouses' | 'accounts' | 'employees' | 'parties';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          request: components['schemas']['EntityCreateRequest'];
        };
      };
    };
    responses: {
      /** @description Immutable acknowledgement; current row must be read separately */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityCreateIdentity'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Current policy/CSRF or conflict refusal */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  voucherDraftContext: {
    parameters: {
      query: {
        kind: string;
        store: string;
        date?: string;
        expense_scope?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authorized context */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VoucherDraftContext'];
        };
      };
      /** @description Invalid context */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Role/store access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createNativeVoucher: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Legacy user-policy-redacted voucher ACK with request_key */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error; optional bound no-write proof */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            components['schemas']['Error'] | components['schemas']['VoucherCreateRejected'];
        };
      };
      /** @description Authorization failure without no-write proof */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict without no-write proof */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
