/* Isolated failure and pending states; no real password or logout mutations. */
const assert = require('node:assert/strict');
module.exports = async function authUX(page, base, wait) {
  const session = '**/api/v1/session';
  const failedSession = route => route.fulfill({status:503, contentType:'application/json', body:'{}'});
  await page.route(session, failedSession);
  await page.goto(base+'/account', {waitUntil:'domcontentloaded'});
  await page.locator('#retry').waitFor({state:'visible'});
  assert.equal(await page.locator('[name=current]').isDisabled(), true);
  assert.equal(await page.locator('#out').isDisabled(), true);
  await page.unroute(session, failedSession);
  await page.locator('#retry').click();
  await wait(async () => !(await page.locator('#out').isDisabled()));
  assert.equal(await page.locator('#retry').isVisible(), false);
  await page.locator('[name=current]').fill('isolated-current-password');
  await page.locator('[name=new]').fill('isolated-new-password');
  let release, requests=0;
  const gate=new Promise(resolve=>release=resolve);
  const passwordURL='**/api/account/password';
  const failPassword=async route=>{requests++;await gate;await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Тестова помилка пароля'})});};
  await page.route(passwordURL,failPassword);
  await page.locator('button[type=submit]').click();
  await wait(async()=>requests===1);
  for(const selector of ['[name=current]','[name=new]','#out','button[type=submit]'])assert.equal(await page.locator(selector).isDisabled(),true);
  await page.locator('#f').evaluate(el=>el.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
  assert.equal(requests,1);
  release();
  await wait(async()=>!(await page.locator('[name=current]').isDisabled()));
  assert.equal(await page.locator('#e').innerText(),'Тестова помилка пароля');
  assert.equal(await page.locator('[name=new]').inputValue(),'isolated-new-password');
  assert.equal(await page.locator('[name=current]').evaluate(el=>document.activeElement===el),true);
  await page.unroute(passwordURL,failPassword);
  const logoutURL='**/api/logout';
  const failLogout=route=>route.fulfill({status:503,body:'{}'});
  await page.route(logoutURL,failLogout);
  await page.locator('#out').click();
  await wait(async()=>(await page.locator('#e').innerText()).includes('Не вдалося завершити сеанс'));
  assert.equal(await page.locator('[name=current]').isDisabled(),false);
  await page.unroute(logoutURL,failLogout);
  await page.context().clearCookies();
  await page.goto(base,{waitUntil:'domcontentloaded'});
  await page.locator('[name=username]').fill('tester');
  await page.locator('[name=password]').fill('isolated-error-password');
  let releaseLogin,loginRequests=0;
  const loginGate=new Promise(resolve=>releaseLogin=resolve);
  const loginURL='**/api/login';
  const failLogin=async route=>{loginRequests++;await loginGate;await route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:'Тестова помилка входу'})});};
  await page.route(loginURL,failLogin);
  await page.locator('button[type=submit]').click();
  await wait(async()=>loginRequests===1);
  assert.equal(await page.locator('[name=username]').isDisabled(),true);
  assert.equal(await page.locator('[name=password]').isDisabled(),true);
  await page.locator('#f').evaluate(el=>el.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
  assert.equal(loginRequests,1);
  releaseLogin();
  await wait(async()=>!(await page.locator('[name=password]').isDisabled()));
  assert.equal(await page.locator('[name=username]').inputValue(),'tester');
  assert.equal(await page.locator('[name=password]').evaluate(el=>document.activeElement===el),true);
  assert.equal(await page.locator('[name=password]').getAttribute('maxlength'),'256');
  await page.unroute(loginURL,failLogin);
  console.log('Auth UX: session retry, pending locks, duplicate prevention, preserved fields and error focus passed');
};
