/* Real downloads and preview, using synthetic data in a disposable localhost SQLite. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright'),csv=require('../app/csv.js');
const root=path.resolve(__dirname,'..'),python=process.env.PYTHON_BIN||'python3',port=18225,base=`http://localhost:${port}`,password='isolated-csv-password';
const data=fs.mkdtempSync(path.join(os.tmpdir(),'tsukenya-csv-db-')),output=path.join(os.tmpdir(),'tsukenya-csv-qa');fs.mkdirSync(output,{recursive:true});
const hash=execFileSync(python,['-c',`from server.auth import hash_password;print(hash_password('${password}'))`],{cwd:root,encoding:'utf8'}).trim();
const env={...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:data,ERP_DB_PATH:path.join(data,'crm.sqlite3'),OWNER_USERNAME:'tester',OWNER_PASSWORD_HASH:hash};
for(const key of ['DATABASE_URL','DB_HOST','DB_PORT','DB_NAME','DB_USER','DB_PASSWORD'])delete env[key];
const log=fs.openSync(path.join(data,'server.log'),'a'),server=spawn(python,['-m','server.main'],{cwd:root,env,stdio:['ignore',log,log]});fs.closeSync(log);
let browser;const errors=[],checks=[];
async function download(page,button,name){const pending=page.waitForEvent('download');await button.click();const file=path.join(output,name);await(await pending).saveAs(file);return fs.readFileSync(file,'utf8');}
(async()=>{try{
 for(let i=0;i<120;i++){if(server.exitCode!==null)throw Error(fs.readFileSync(path.join(data,'server.log'),'utf8').slice(-2000));try{if((await fetch(base+'/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 execFileSync(python,['-c',`import os\nos.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings')\nimport django;django.setup()\nfrom server.erp.models import Document\nfrom django.utils import timezone\nDocument.objects.create(path='products/=csv',data={'name':'=1+1','category':'+SUM(A1:A2)','unit':'шт','pack':'Штучно','cost':12.1234,'markup':30,'manualPrice':True,'price':34.50,'promotion':True,'promotionPrice':21.99,'priceAt':str(timezone.localdate())})`],{cwd:root,env});
 browser=await chromium.launch({ headless: true });
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.abort());await page.route('https://fonts.gstatic.com/**',r=>r.abort());
 await require('./browser-login.cjs')(page,base,password);assert.equal(await page.evaluate(()=>typeof TSukenyaCsv.serialize),'function');
 await page.goto(base+'/#operations/tags');await page.getByRole('tab',{name:/^Товари для друку/}).click();await page.getByRole('searchbox',{name:'Пошук товарів'}).fill('=1+1');await page.locator('.tk-studio-product-row').filter({hasText:'=1+1'}).locator('.tk-studio-check').click();
 await page.getByRole('button',{name:/^Перевірити/}).click();const exportButton=page.getByRole('button',{name:'Експорт CSV',exact:true});await exportButton.waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Експорт CSV'&&!b.disabled));
 const labels=await download(page,exportButton,'labels.csv');assert(labels.includes('"\t=1+1"'));assert(labels.includes('"\t+SUM(A1:A2)"'));const labelRows=csv.parse(labels);assert.deepEqual(labelRows[1],['=1+1','+SUM(A1:A2)','шт','34.50','21.99','21.99','','Так']);checks.push('Real lazy React Label Studio CSV: formula text escaped, regular/promotion/effective exact prices, roundtrip');
 execFileSync(python,['-c',"import os;os.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings');import django;django.setup();from server.erp.models import StockLot,Warehouse;StockLot.objects.create(warehouse=Warehouse.objects.first(),product_id='products/=csv',code='CSV QA',quantity='1.125',value='12.12')"],{cwd:root,env});
 await page.goto(base+'/#trade/stock');await page.locator('[data-trade=stock-csv]').waitFor();const stock=await download(page,page.locator('[data-trade=stock-csv]'),'stock.csv');assert(stock.includes('"\t=1+1"'));const stockRows=csv.parse(stock),csvStock=stockRows.find(row=>row[0]==='=1+1');assert.deepEqual(csvStock.slice(2),['1.125','1.125','шт','12.12']);checks.push('Real streamed ERP stock CSV: protected name, exact quantity and authoritative lot value');
 await page.locator('[data-trade=new-voucher][data-kind=opening]').click();const template=await download(page,page.locator('.trade-dialog[open] [data-trade=lines-template]'),'template.csv');assert(template.includes('ID [TSukenya CSV 1]'));assert(template.includes('"\t=csv"'));const rows=csv.parse(template);const row=rows.find(r=>r[0]==='=csv');assert(row);assert.equal(row[2],'12.1234');
 const filled=csv.serialize(rows[0].map((label,index)=>({label,kind:index===1||index===2?'number':'text'})),[['=csv','1.125',row[2],'=партія','']],{reversible:true});
 const preview=await page.evaluate(async text=>{const state=await(await fetch('/api/state')).json(),r=await fetch('/api/erp/import-preview',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:JSON.stringify({csv:text})});return {status:r.status,body:await r.json()};},filled);assert.equal(preview.status,200);assert.deepEqual(preview.body.lines[0],{product:'=csv',name:'=1+1',quantity:'1.125',price:'12.1234',lot:'=партія',expiry:''});checks.push('Real versioned ERP template download → filled quantities → server preview: IDs/lots unescaped exactly once, precise price');
 await page.keyboard.press('Escape');
 // Report export is an independent server snapshot; mock browser JSON cannot alter its accounting amounts.
 execFileSync(python,['-c',"import os;os.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings');import django;django.setup();from server.erp.models import Voucher,Store,CashAccount,CashEntry;from django.contrib.auth.models import User;from django.utils import timezone;account=CashAccount.objects.first();v=Voucher.objects.create(kind='expense',status='posted',date=timezone.localdate(),store=account.store,account=account,total='23.50',created_by=User.objects.get(username='tester'));CashEntry.objects.create(voucher=v,account=account,amount='-23.50')"],{cwd:root,env});
 await page.goto(base+'/#trade/reports');await page.locator('[data-report-summary] [data-report-export][href]').waitFor();const report=await download(page,page.locator('[data-report-summary] [data-report-export]'),'report.csv'),reportRows=csv.parse(report);assert.equal(reportRows.find(r=>r[0]==='profit')[1],'-23.50');assert.equal(reportRows.find(r=>r[0]==='cash_net')[1],'-23.50');assert(report.includes('"-23.50"')&&!report.includes('"\t-23.50"')&&!report.includes("'-23.50"));checks.push('Authoritative streamed report CSV: negative exact cents numeric; four-place unit cost remains covered by the template roundtrip');
 assert.deepEqual(errors,[]);const summary={checks,errors,scope:'Disposable SQLite only; no posting, Google Sheet or production writes; spreadsheet editor opening not tested.'};fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
}finally{await browser?.close();server.kill('SIGTERM');await new Promise(resolve=>{if(server.exitCode!==null)resolve();else server.once('exit',resolve);});fs.rmSync(data,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
