/* B20 isolated real server/browser workflow; no production writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
module.exports=async function initiatives(page,base,wait,env,python){
 const output=process.env.QA_OUTPUT_DIR||path.join(os.tmpdir(),'tsukenya-initiative-proof');fs.mkdirSync(output,{recursive:true});
 const fixture=JSON.parse(execFileSync(python,['-c',`
import os,json
os.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings')
import django;django.setup()
from server.erp.models import *
from django.contrib.auth.models import User
from django.utils import timezone
for key,title in [('coffee','Кава із собою — перевірити попит на новий формат і обслуговування'),('qualitative','Якісне покращення без числового показника')]:Document.objects.create(path='ideas/'+key,data={'title':title,'text':'Погоджена перевірка формату','reaction':'yes'})
Document.objects.create(path='tasks/initiative_old',data={'title':'Стара задача з довгою назвою: перевірити новий формат обслуговування','stage':2,'status':'todo'})
owner=User.objects.get(username='tester');store=Store.objects.first();account=CashAccount.objects.filter(kind='cash').first()
print(json.dumps({'store':store.pk,'account':account.pk,'today':str(timezone.localdate())}))
`],{env,encoding:'utf8'}));
 const api=(endpoint,body)=>page.evaluate(async({endpoint,body})=>{const state=await(await fetch('/api/state')).json();const r=await fetch('/api/erp/'+endpoint,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':state.csrf},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,data:await r.json()};},{endpoint,body});
 const ok=async(endpoint,body)=>{const r=await api(endpoint,body);assert(r.status<300,JSON.stringify(r));return r.data;};
 const d=()=>page.locator('.initiative-dialog[open]'),action=(name)=>d().getByRole('button',{name,exact:true}),ready=async()=>wait(async()=>await d().count()&&!(await d().innerText()).includes('Завантаження…'));
 const inspect=async(label)=>{for(const width of [1440,320]){await page.setViewportSize({width,height:1050});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await d().evaluate(el=>el.scrollWidth>el.clientWidth+1),false,label);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,label);const sizes=await d().locator('button').evaluateAll(items=>items.map(el=>({w:el.getBoundingClientRect().width,h:el.getBoundingClientRect().height})));assert(sizes.every(s=>s.w>=44&&s.h>=44),JSON.stringify(sizes));await page.screenshot({path:path.join(output,label+'-'+width+'.png')});}};
 await page.goto(base+'/#development/ideas');const opener=page.locator('[data-initiative-create=coffee]');await opener.waitFor();let readFailure=true;await page.route('**/api/erp/initiatives/ideas/coffee',route=>readFailure?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Ізольована помилка читання B20'})}):route.continue());await opener.press('Enter');await action('Повторити читання').waitFor();assert.match(await d().innerText(),/Ізольована помилка читання B20/);readFailure=false;await action('Повторити читання').press('Enter');await d().locator('[name=title]').waitFor();await page.unroute('**/api/erp/initiatives/ideas/coffee');await ready();assert.equal(await d().locator('h2').evaluate(el=>el===document.activeElement),true);assert.equal(await d().locator('[name=plannedBudget]').inputValue(),'');assert.equal(await d().locator('[name=targetValue]').inputValue(),'');
 await d().locator('[name=plannedBudget]').fill('125,50');await d().locator('[name=metric]').fill('Частка повторних покупців');await d().locator('[name=metricUnit]').fill('%');await d().locator('[name=targetValue]').fill('12,0001');await inspect('plan');
 // The write actually commits; only its acknowledgement is replaced. Exact retry cannot duplicate the project.
 const attempts=[];let lost=true;await page.route('**/api/erp/initiatives',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}attempts.push(route.request().postDataJSON());if(lost){lost=false;await route.fetch();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Ізольована втрачена відповідь B20'})});}else await route.continue();});
 await action('Створити проєкт').press('Enter');await action('Повторити ту саму дію').waitFor();assert.equal(await d().locator('[name=title]').isDisabled(),true);await action('Повторити ту саму дію').press('Enter');await action('Редагувати план').waitFor();assert.deepEqual(attempts[0],attempts[1]);await page.unroute('**/api/erp/initiatives');
 const projects=await ok('initiatives');assert.equal(projects.total,1);const id=projects.items[0].id;assert.equal((await ok('initiatives/'+id)).plannedBudget,'125.50');
 await action('Почати реалізацію').press('Enter');await action('Записати результат').waitFor();
 await action('Додати нову задачу').click();await d().locator('[name=title]').fill('Перевірити попит у вихідні');await d().locator('[name=phase]').fill('Пілот');let taskLost=true;const taskAttempts=[];await page.route('**/api/erp/initiatives/'+id,async route=>{if(route.request().method()!=='POST'||route.request().postDataJSON().action!=='task_create'){await route.continue();return;}taskAttempts.push(route.request().postDataJSON());if(taskLost){taskLost=false;await route.fetch();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Втрачено підтвердження задачі'})});}else await route.continue();});await action('Додати задачу').press('Enter');await action('Повторити ту саму дію').waitFor();await action('Повторити ту саму дію').press('Enter');await action('Пов’язати стару задачу').waitFor();assert.deepEqual(taskAttempts[0],taskAttempts[1]);assert.equal((await ok('initiatives/'+id)).tasks.total,1);await page.unroute('**/api/erp/initiatives/'+id);
 await action('Пов’язати стару задачу').click();await d().getByText('Стара задача з довгою назвою: перевірити новий формат обслуговування',{exact:true}).waitFor();await action('Пов’язати').click();await d().locator('[name=phase]').fill('Підготовка');await action('Пов’язати задачу').click();await action('Редагувати план').waitFor();assert.equal((await ok('initiatives/'+id)).tasks.total,2);
 const legacy=await page.evaluate(async()=>{const s=await(await fetch('/api/state')).json();return s.data.tasks.find(t=>t.id==='initiative_old');});assert.equal(legacy.initiative,id);assert.deepEqual(legacy.permissions,{canEdit:false,canDelete:false});
 await action('Змінити стан').first().click();await d().locator('[name=status]').selectOption('done');await action('Зберегти').click();await action('Редагувати план').waitFor();
 // A changed source task gets its own current comparison and explicit fresh token.
 const firstTask=(await ok('initiatives/'+id)).tasks.items[0];await action('Змінити стан').first().click();await d().locator('[name=status]').selectOption('todo');execFileSync(python,['-c',`import os;os.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings');import django;django.setup();from server.erp.models import Document;d=Document.objects.get(pk='tasks/${firstTask.id}');d.data={**d.data,'status':'doing'};d.save()`],{env});await action('Зберегти').click();await action('Порівняти з поточною версією').waitFor();await action('Порівняти з поточною версією').click();await action('Використати поточну версію для чернетки').waitFor();assert.match(await d().locator('[data-initiative-comparison]').innerText(),/Поточне джерело:.*У роботі/);assert.equal(await d().locator('[name=status]').inputValue(),'todo');await action('Використати поточну версію для чернетки').click();await action('Зберегти').click();await action('Редагувати план').waitFor();assert.equal((await ok('initiatives/'+id)).tasks.items[0].status,'todo');
 // 409 preserves the local form; the user inspects latest values before explicitly rebasing it.
 await action('Редагувати план').click();await d().locator('[name=title]').fill('Моя збережена чернетка після конфлікту');await d().locator('[name=plannedBudget]').fill('99,95');execFileSync(python,['-c',`import os;os.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings');import django;django.setup();from server.erp.models import IdeaProject;from django.db.models import F;IdeaProject.objects.filter(pk='${id}').update(title='Інша поточна назва',planned_budget='120.01',revision=F('revision')+1)`],{env});
 await action('Зберегти').click();await action('Порівняти з поточною версією').waitFor();assert.equal(await d().locator('[name=title]').inputValue(),'Моя збережена чернетка після конфлікту');assert.equal(await d().locator('[name=title]').isEnabled(),true);await action('Порівняти з поточною версією').press('Enter');await action('Використати поточну версію для чернетки').waitFor();assert.match(await d().locator('[data-initiative-comparison]').innerText(),/120.01/);await inspect('conflict');await action('Використати поточну версію для чернетки').press('Enter');await action('Зберегти').click();await action('Редагувати план').waitFor();assert.equal((await ok('initiatives/'+id)).plannedBudget,'99.95');
 const expense=await ok('vouchers',{kind:'expense',date:fixture.today,store:fixture.store,account:fixture.account,amount:'20.05',payload:{category:'Пілот нового формату',expense_scope:'store'}});await ok('vouchers/'+expense.id+'/post',{});await action('Пов’язати проведену витрату').click();await d().getByText('№ '+String(expense.id).padStart(6,'0')+' · 20.05 грн',{exact:true}).waitFor();await action('Пов’язати').click();await action('Пов’язати витрату').click();await action('Відкрити джерело').waitFor();assert.equal((await ok('initiatives/'+id)).actualExpenses,'20.05');await action('Відкрити джерело').press('Enter');await d().getByRole('heading',{name:/Джерело витрати/}).waitFor();assert.match(await d().innerText(),/20.05 грн/);assert.equal(await d().getByRole('button',{name:/Провести|Скасувати проведення/}).count(),0);await action('До проєкту').click();
 await ok('vouchers/'+expense.id+'/reverse',{reason:'Пілот скасовано постачальником'});await action('Оновити поточний стан').click();await wait(async()=>(await d().innerText()).includes('Сторновано'));assert.equal((await ok('initiatives/'+id)).actualExpenses,'0.00');
 await action('Записати результат').click();await d().locator('[name=resultSummary]').fill('Перевірили формат. У вихідні повторні покупки зросли.');await d().locator('[name=factValue]').fill('14,0001');await inspect('result');await action('Завершити проєкт').press('Enter');await action('Виправити результат').waitFor();assert.equal((await ok('initiatives/'+id)).factValue,'14.0001');await inspect('completed');await d().press('Escape');assert.equal(await d().count(),0);assert.equal(await opener.evaluate(el=>el===document.activeElement),true);
 // Optional KPI/budget permits a qualitative completed result.
 await page.locator('[data-initiative-create=qualitative]').click();await ready();await action('Створити проєкт').click();await action('Почати реалізацію').waitFor();await action('Почати реалізацію').click();await action('Записати результат').click();assert.equal(await d().locator('[name=factValue]').count(),0);await d().locator('[name=resultSummary]').fill('Процес став зрозумілішим для працівників.');await action('Завершити проєкт').click();await action('Виправити результат').waitFor();await d().press('Escape');
 await page.goto(base+'/#development/devOverview');await page.locator('[data-initiatives] [data-initiative-open]').first().waitFor();assert.match(await page.locator('[data-initiatives]').innerText(),/Проєкти та результати · 2/);
 await page.goto(base+'/#trade/setup');await page.locator('[data-trade=audit]').click();const audit=page.locator('[data-finance-audit]');await audit.locator('[name=q]').fill('initiative/'+id);await audit.locator('[type=submit]').click();await wait(async()=>!!await audit.locator('[data-business-changes]').count());assert.match(await audit.innerText(),/Фактичний показник/);assert.match(await audit.innerText(),/14.0001/);assert.match(await audit.innerText(),/Пов’язана задача або витрата/);assert.equal(await audit.evaluate(el=>el.scrollWidth>el.clientWidth+1),false);await page.screenshot({path:path.join(output,'audit-320.png')});await audit.press('Escape');
 fs.writeFileSync(path.join(output,'report.json'),JSON.stringify({passed:true,checks:['optional budget/KPI and qualitative completion','explicit numeric decimal target/fact','lost ACK actual commit exact retry project + task','legacy task adoption identity/permissions','409 retained draft and explicit current baseline + source task token','expense whole attribution, source readonly, reversed actual0','native keyboard heading/Enter/Escape/focus return','44px and no overflow320/1440','owner business beforeafter audit']},null,2));console.log('PASS B20 isolated UI: '+output);
};
