/* Synthetic local label export only. Native process RSS is a proxy, not physical-device capacity. */
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,execFileSync}=require('node:child_process');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.QA_OUTPUT_DIR||'/tmp/tsukenya-label-memory-baseline';fs.mkdirSync(out,{recursive:true});
const server=spawn('npm',['exec','--workspace','frontend','--','vite','--host','127.0.0.1','--port','18235','--strictPort'],{cwd:root,stdio:['ignore','pipe','pipe']});let logs='';server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
let browserServer,browser,page,timer;const samples=[],errors=[];let phase='baseline';
function rss(){const rows=execFileSync('ps',['-axo','pid=,ppid=,rss=,comm='],{encoding:'utf8'}).trim().split('\n').map(line=>{const match=line.trim().match(/^(\d+)\s+(\d+)\s+(\d+)\s+(.+)$/);return match&&{pid:+match[1],parent:+match[2],rssKiB:+match[3],name:match[4]};}).filter(Boolean);const owned=new Set([browserServer.process().pid]);let count;do{count=owned.size;for(const row of rows)if(owned.has(row.parent))owned.add(row.pid);}while(count!==owned.size);const processes=rows.filter(row=>owned.has(row.pid));return {at:Date.now(),phase,rssKiB:processes.reduce((sum,row)=>sum+row.rssKiB,0),processes};}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:18235/frontend/')).ok)break;}catch{}if(server.exitCode!==null)throw Error(logs);await sleep(100);}
 browserServer=await chromium.launchServer({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-precise-memory-info']});browser=await chromium.connect(browserServer.wsEndpoint());page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:18235/frontend/');
 const session=await page.context().newCDPSession(page);await session.send('HeapProfiler.enable');
 await page.evaluate(async()=>{const output=await import('/frontend/src/features/labels/output.tsx'),fixture=await import('/frontend/src/features/labels/fixtures.ts');window.memoryExport=output.exportPdf;window.memorySnapshot={config:{...fixture.studioConfig,size:'l',per100:true},settings:fixture.studioSettings,date:new Date('2026-10-01T12:00:00Z'),products:Array.from({length:1000},(_,i)=>({...fixture.studioProducts[0],id:'memory-'+i,name:'Товар '+String(i).padStart(4,'0'),unit:'кг',salePrice:99.99,regularPrice:i%3===0?129.99:99.99,promotion:i%3===0}))};window.memoryDownloads=[];const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);window.memoryURLs=new Set();URL.createObjectURL=blob=>{const url=create(blob);window.memoryURLs.add(url);window.memoryDownloads.push({size:blob.size,type:blob.type});return url;};URL.revokeObjectURL=url=>{window.memoryURLs.delete(url);revoke(url);};HTMLAnchorElement.prototype.click=function(){};});
 await page.evaluate(()=>window.memoryExport({...window.memorySnapshot,products:window.memorySnapshot.products.slice(0,1)}));await session.send('HeapProfiler.collectGarbage');samples.push(rss());timer=setInterval(()=>{try{samples.push(rss());}catch(error){errors.push(error.message);}},100);
 const results=[];for(const entry of [{name:'export-1000-distinct-1'},{name:'cancel-page-2',cancel:2},{name:'export-1000-distinct-2'}]){phase=entry.name;const baseline=rss();const started=Date.now();const result=await page.evaluate(async cancel=>{const controller=new AbortController();let nodes=0,captures=0;try{await window.memoryExport(window.memorySnapshot,{signal:controller.signal,onProgress:p=>{nodes=Math.max(nodes,document.querySelectorAll('[style*="left: -10000px"] .tk-label').length,document.querySelectorAll('.tk-label').length);if(p.stage==='capture')captures=Math.max(captures,p.completed);if(p.stage==='pages'&&p.completed===cancel)controller.abort();}});return {outcome:'complete',nodes,captures};}catch(error){return {outcome:error.name,nodes,captures};}},entry.cancel??-1);await session.send('HeapProfiler.collectGarbage');const heap=await session.send('Runtime.getHeapUsage'),dom=await session.send('Memory.getDOMCounters');results.push({name:entry.name,ms:Date.now()-started,baselineRSSKiB:baseline.rssKiB,...result,heap,dom,after:rss(),downloads:await page.evaluate(()=>window.memoryDownloads.slice()),urls:await page.evaluate(()=>window.memoryURLs.size)});assert.equal(result.outcome,entry.cancel?'AbortError':'complete');}
 phase='after-url-expiry';await sleep(61000);await session.send('HeapProfiler.collectGarbage');samples.push(rss());const after=await session.send('Runtime.getHeapUsage');const urls=await page.evaluate(()=>window.memoryURLs.size);clearInterval(timer);timer=undefined;assert.equal(urls,0);assert.deepEqual(errors,[]);const report={date:new Date().toISOString(),platform:os.platform(),release:os.release(),browser:await browser.version(),method:'100 ms sampled sum of RSS KiB of this private Chrome process tree; shared pages may be counted twice, not PSS/native footprint/mobile RAM; Runtime.getHeapUsage after forced GC separately',results,samples,postExpiryHeap:after,postExpiryURLs:urls};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));for(const result of results){const peak=Math.max(...samples.filter(s=>s.phase===result.name).map(s=>s.rssKiB));console.log(result.name,JSON.stringify({ms:result.ms,outcome:result.outcome,nodes:result.nodes,heap:result.heap,rssPeakMiB:peak/1024,rssDeltaMiB:(peak-result.baselineRSSKiB)/1024,urls:result.urls,downloads:result.downloads}));}console.log('Report:',path.join(out,'report.json'));
})().catch(error=>{console.error(error);process.exitCode=1;fs.writeFileSync(path.join(out,'failure.log'),String(error)+'\n'+logs);}).finally(async()=>{if(timer)clearInterval(timer);await browser?.close();await browserServer?.close();server.kill('SIGTERM');});
