const assert=require('node:assert/strict');
const navigateSidebar=require('./browser-navigation.cjs');
module.exports=async(page,base,wait)=>{
 const go=async route=>{await page.goto(base+'/#'+route,{waitUntil:'domcontentloaded'});await page.locator('#pageTitle').waitFor();};
 await go('operations/work');
 const input=page.getByRole('textbox',{name:'Що зробити'});
 await page.getByRole('button',{name:'Додати задачу',exact:true}).click();
 assert.equal(await input.evaluate(i=>i.validationMessage),'Введіть назву.');
 await input.fill('Незбережена робота для перевірки');
 await page.evaluate(()=>window.TSUKENYA_REFRESH());
 await page.locator('#pageTitle').focus();
 await wait(async()=>await input.inputValue()==='Незбережена робота для перевірки');
 const cancel=new Promise(resolve=>page.once('dialog',async d=>{assert.match(d.message(),/Відкинути/);await d.dismiss();resolve();}));
 await navigateSidebar(page,'ideas');await cancel;await wait(async()=>/#operations\/work$/.test(page.url()));
 assert.match(page.url(),/#operations\/work$/);assert.equal(await input.inputValue(),'Незбережена робота для перевірки');
 let writes=0;
 await page.route('**/api/tasks',async r=>{if(r.request().method()==='POST'){writes++;await new Promise(resolve=>setTimeout(resolve,250));}await r.continue();});
 await input.press('Enter');await input.press('Enter').catch(()=>{});
 await wait(async()=>!await page.getByRole('button',{name:'Додати задачу',exact:true}).isDisabled());
 assert.equal(writes,1,'one logical click creates one task');assert.equal(await input.inputValue(),'','successful task clears draft');
 assert(await input.evaluate(i=>i===document.activeElement),'focus returns to task input');
 await page.unroute('**/api/tasks');
 await input.fill('Чернетка після помилки');
 await page.route('**/api/tasks',r=>r.request().method()==='POST'?r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Контрольна помилка'})}):r.continue());
 await input.press('Enter');await wait(async()=>!await page.getByRole('button',{name:'Додати задачу',exact:true}).isDisabled());
 assert.equal(await input.inputValue(),'Чернетка після помилки','failed write retains draft');await page.unroute('**/api/tasks');
 await input.fill('');await navigateSidebar(page,'ideas');
 await wait(async()=>await page.locator('#pageTitle').evaluate(el=>el===document.activeElement));
 assert.equal(await page.locator('#pageTitle').evaluate(el=>el===document.activeElement),true,'route change announces heading');
 await page.getByRole('textbox',{name:'Нова ідея'}).fill('Контрольна нова ідея');await page.getByRole('textbox',{name:'Нова ідея'}).press('Enter');
 await wait(async()=>!await page.getByRole('button',{name:'Записати',exact:true}).isDisabled());assert.equal(await page.getByRole('textbox',{name:'Нова ідея'}).inputValue(),'');
 await page.locator('.tab[data-tab=tasks]').click();await page.getByRole('textbox',{name:'Назва задачі розвитку'}).fill('Контрольна задача розвитку');await page.getByRole('textbox',{name:'Назва задачі розвитку'}).press('Enter');
 await wait(async()=>!await page.getByRole('button',{name:'Додати',exact:true}).isDisabled());assert.equal(await page.getByRole('textbox',{name:'Назва задачі розвитку'}).inputValue(),'');
 await page.locator('.tab[data-tab=expenses]').click();const expense=page.getByRole('textbox',{name:'Нова стаття: Постійні'});await expense.fill('Контрольна нова стаття');await page.locator('[data-act=addExp][data-g=fixed]').click();
 await wait(async()=>!await page.locator('[data-act=addExp][data-g=fixed]').isDisabled());assert.equal(await expense.inputValue(),'');
 console.log('PASS: native empty validation, draft across refresh and cancelled navigation, single submission, error preserves draft, focus, keyboard creation work/idea/development/budget.');
};
