/* Browser regression suite. Starts an isolated server; never touches the live database. */
const assert=require('node:assert/strict');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {spawn,execFileSync}=require('node:child_process');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),data=fs.mkdtempSync(path.join(os.tmpdir(),'tsukenya-ui-'));
const port=18199,base=`http://localhost:${port}`,password='isolated-browser-test-password';
const python=process.env.PYTHON_BIN||'python3';
const hash=execFileSync(python,['-c','from server.main import hash_password; print(hash_password("isolated-browser-test-password"))'],{cwd:root,encoding:'utf8'}).trim();
const server=spawn(python,['-m','server.main'],{cwd:root,env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:data,OWNER_USERNAME:'tester',OWNER_PASSWORD_HASH:hash},stdio:'ignore'});
let browser;
async function check(condition,message){for(let i=0;i<80;i++){if(await condition())return;await new Promise(r=>setTimeout(r,100));}throw Error(message);}
(async()=>{
 await check(async()=>{try{return (await fetch(base+'/health')).ok}catch{return false}},'server startup');
 const executable=process.env.CHROME_PATH||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined);
 browser=await chromium.launch({executablePath:executable,headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('[name=username]').fill('tester');await page.locator('[name=password]').fill(password);await page.locator('button[type=submit]').click();await page.waitForSelector('#main .stats');
 const state=()=>page.evaluate(async()=> (await (await fetch('/api/state')).json()).data);
 const go=async(route)=>{await page.goto(base+'/#'+route);await page.waitForSelector('#main .panel');};
 await go('operations/products');await check(async()=>await page.locator('.catalog-table tbody tr').count()===20,'catalog initial page');
 await page.locator('[data-page="2"]').click();assert.match(await page.locator('.catalog-pagination').innerText(),/21–40/);
 await page.locator('#q').fill('Американо');await check(async()=>await page.locator('.catalog-table tbody tr').count()===1,'search');
 await page.locator('[data-act=fReset]').click();await page.locator('[data-act=newProduct]').click();
 const form=page.locator('#productForm');await form.locator('[name=name]').fill('Контрольний акційний товар');await form.locator('[name=category]').fill('Тест');await form.locator('[name=pack]').selectOption('Штучно');await form.locator('[name=priceMode]').selectOption('manual');await form.locator('[name=price]').fill('45');await form.locator('[name=promotion]').check();await form.locator('[type=submit]').click();await check(async()=>!(await page.locator('dialog').isVisible()),'product save dialog');
 let dataNow=await state(),product=dataNow.products.find(p=>p.data.name==='Контрольний акційний товар');assert(product);assert.equal(product.data.promotion,true);
 await page.reload();await page.waitForSelector('.catalog-table');await page.locator('#q').fill('Контрольний акційний товар');await page.locator(`[data-promotion="${product.id}"]`).waitFor();assert(await page.locator(`[data-promotion="${product.id}"]`).isChecked());
 await go('operations/tags');await page.locator('#q').fill('Контрольний акційний товар');await page.locator(`[data-tag="${product.id}"]`).check();await page.locator('#previewProduct').selectOption(product.id);assert.equal(await page.locator('#individualPreview .t-promo').innerText(),'Акція');
 await page.locator('[data-edit-field=promo]').click();await page.locator('[data-style=promo][data-prop=size]').fill('9');await page.locator('[data-style=promo][data-prop=size]').blur();await check(async()=> (await state())['settings/main'].tag?.styles?.promo?.size===9,'promo font saved');
 await page.locator('[data-edit-field=name]').click();await page.locator('[data-style=name][data-prop=size]').fill('11');await page.locator('[data-style=name][data-prop=size]').blur();await check(async()=> (await state())['settings/main'].tag?.styles?.name?.size===11,'name font saved');
 await page.locator('[data-style=name][data-prop=font]').selectOption('georgia');await page.locator('[data-style=name][data-prop=align]').selectOption('center');await check(async()=> (await state())['settings/main'].tag?.styles?.name?.align==='center','alignment saved');
 await page.locator('[data-act=resetField]').click();await check(async()=> !(await state())['settings/main'].tag?.styles?.name,'field reset saved');await page.reload();await page.waitForSelector('#individualPreview .tag');await page.locator('#q').fill('Контрольний акційний товар');await page.locator(`[data-tag="${product.id}"]`).check();
 await page.locator('[data-edit-field=promo]').click();assert.equal(await page.locator('[data-style=promo][data-prop=size]').inputValue(),'9');
 // Every label element has its own inspector, and can be reached by keyboard.
 const keys=await page.locator('[data-edit-field]').evaluateAll(nodes=>nodes.map(n=>n.dataset.editField));assert.equal(keys.length,12);
 for(const key of keys){await page.locator(`[data-edit-field=${key}]`).click();assert.equal(await page.locator('#fieldInspector [data-prop=size]').count(),1);}
 await page.locator('#individualPreview [data-field=price]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#fieldInspector h3').innerText(),'Ціна');
 // Overflow cannot be printed or exported.
 await page.locator('[data-style=price][data-prop=size]').fill('72');await page.locator('[data-style=price][data-prop=size]').blur();await check(async()=> (await state())['settings/main'].tag?.styles?.price?.size===72,'oversized price saved');
 await page.locator('[data-act=dlPdf]').click();assert(await page.locator('[data-act=confirmOutput]').isDisabled());assert.match(await page.locator('#printIssues').innerText(),/Текст не вміщується/);
 await page.locator('[data-act=closePrintReview]').click();await page.locator('[data-edit-field=price]').click();await page.locator('[data-act=resetField]').click();await check(async()=> !(await state())['settings/main'].tag?.styles?.price,'price reset');
 await page.locator('[data-act=dlPdf]').click();assert(await page.locator('[data-act=confirmOutput]').isEnabled());
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-act=confirmOutput]').click();const download=await downloadPromise;const artifact=path.join(process.env.QA_OUTPUT_DIR||os.tmpdir(),'tsukenya-label-qa.pdf');await download.saveAs(artifact);assert(fs.readFileSync(artifact).subarray(0,8).toString().startsWith('%PDF-1.4'));
 console.log('PDF:',artifact);
 await page.locator('[data-act=closePrintReview]').click();await page.locator('#qtyAll').fill('22');await page.locator('[data-act=qtyAll]').click();await page.locator('[data-act=printReview]').click();assert.equal(await page.locator('#printPages .print-page').count(),2);assert.equal(await page.locator('#printPages .tag').count(),22);
 await page.evaluate(()=>{window.print=()=>{window.testPrintOpened=true;};});await page.locator('[data-act=confirmOutput]').click();assert(await page.evaluate(()=>window.testPrintOpened));assert.equal(await page.locator('#printArea .print-page').count(),2);await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));assert.equal(await page.locator('#printArea').count(),0);

 // No-price records are explicitly blocked.
 await page.locator('[data-act=closePrintReview]').click();await page.locator('[data-act=selNone]').click();await page.locator('#q').fill('');await check(async()=>await page.locator('[data-tag]').count()>40,'pick list search cleared');const noPrice=(await state()).products.find(p=>!p.data.cost&&!p.data.price);await page.locator(`[data-tag="${noPrice.id}"]`).check();await page.locator('[data-act=printReview]').click();assert(await page.locator('[data-act=confirmOutput]').isDisabled());assert.match(await page.locator('#printIssues').innerText(),/Немає ціни/);
 await go('operations/work');await page.locator('#newWork').fill('Щоденна контрольна задача');await page.locator('#newWorkDue').fill('2026-10-01');await page.locator('[data-act=addWork]').click();await check(async()=> (await page.locator('#main').innerText()).includes('Щоденна контрольна задача'),'work created');
 await go('development/tasks');assert(!(await page.locator('#main').innerText()).includes('Щоденна контрольна задача'));await page.locator('#newTask').fill('Розробити облік');await page.locator('[data-act=addTask]').click();await check(async()=> (await page.locator('#main').innerText()).includes('Розробити облік'),'development task created');await go('operations/work');assert(!(await page.locator('#main').innerText()).includes('Розробити облік'));
 await go('development/ideas');await page.locator('#newIdea').fill('Впровадити складський облік');await page.locator('[data-act=addIdea]').click();await check(async()=>await page.locator('[data-react]').count()===2,'idea saved');await page.locator('[data-v=yes]').click();await page.locator('[data-idea-task]').click();await page.locator('.idea a').waitFor();await go('development/tasks');assert.match(await page.locator('#main').innerText(),/Впровадити складський облік/);
 for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:844});for(const route of ['operations/products','operations/tags','operations/work','operations/expenses','development/ideas','development/tasks']){await go(route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${route} overflow at ${width}`);}}
 await page.setViewportSize({width:390,height:844});await go('operations/products');await page.screenshot({path:path.join(os.tmpdir(),'tsukenya-mobile-catalog-viewport.png')});await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await go('operations/tags');await page.locator('.builder-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(os.tmpdir(),'tsukenya-mobile-tags-dark.png')});

 await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({colorScheme:'light'});await go('operations/tags');await page.locator('.builder-panel').screenshot({path:path.join(os.tmpdir(),'tsukenya-builder-desktop.png')});
 await go('operations/products');await page.locator('[data-act=newProduct]').click();await page.locator('dialog').screenshot({path:path.join(os.tmpdir(),'tsukenya-product-editor.png')});await page.locator('[data-act=closeProduct]').first().click();
 // Legacy font sizes were scale factors. Migration keeps their physical print size.
 await page.evaluate(async()=>{const s=await (await fetch('/api/state')).json();await fetch('/api/docs/settings/main',{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:JSON.stringify({tag:{size:'m',styles:{price:{size:22}}}})});});await go('operations/tags');await page.reload();await page.locator('[data-edit-field=price]').click();await check(async()=> (await page.locator('[data-prop=size]').inputValue())==='27.5','legacy point size loaded');await page.locator('[data-prop=color]').evaluate(el=>el.value='#123456');await page.locator('[data-prop=color]').dispatchEvent('change');await check(async()=> (await state())['settings/main'].tag?.styleVersion===2,'legacy style migration saved');assert.equal((await state())['settings/main'].tag.styles.price.size,27.5);
 assert.deepEqual(errors,[]);console.log('PASS: product CRUD/promotion, 12 inspectors, style persistence/reset, matching PDF, overflow/no-price guards, scoped tasks/ideas, keyboard, 5 viewport sizes.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));fs.rmSync(data,{recursive:true,force:true});});
