/* Recipe UX against its own local Django/SQLite; no remote database or Google writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,execFileSync}=require('node:child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),python=process.env.PYTHON_BIN||'python3',port='18229',base=`http://localhost:${port}`,password='isolated-recipes-password';

const data=fs.mkdtempSync(path.join(os.tmpdir(),'tsukenya-production-db-')),output=process.env.QA_OUTPUT_DIR||path.join(os.tmpdir(),'tsukenya-production-qa');fs.mkdirSync(output,{recursive:true});
const hash=execFileSync(python,['-c',`from server.auth import hash_password;print(hash_password('${password}'))`],{cwd:root,encoding:'utf8'}).trim();
const env={...process.env,PORT:port,HOST:'127.0.0.1',DATA_DIR:data,ERP_DB_PATH:path.join(data,'crm.sqlite3'),OWNER_USERNAME:'tester',OWNER_PASSWORD_HASH:hash};
for(const key of ['DATABASE_URL','DB_HOST','DB_PORT','DB_NAME','DB_USER','DB_PASSWORD'])delete env[key];
const log=fs.openSync(path.join(data,'server.log'),'a'),server=spawn(python,['-m','server.main'],{cwd:root,env,stdio:['ignore',log,log]});fs.closeSync(log);
let browser,page,zoomContext,zoomProfile;const results=[],screenshots=[],errors=[];let posts=0;
const wait=async(fn,label)=>{for(let i=0;i<120;i++){if(await fn())return;if(server.exitCode!==null)throw Error('Server exited: '+fs.readFileSync(path.join(data,'server.log'),'utf8').slice(-2000));await new Promise(r=>setTimeout(r,100));}throw Error(`Timeout: ${label}`);};
const fixture=source=>execFileSync(python,['-c',`import os\nos.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings')\nimport django;django.setup()\n${source}`],{cwd:root,env});
const fixtures=()=>fixture(`from server.erp.models import Document,Profile,Store,Warehouse,Counterparty
from server.erp.services import save_voucher,post_voucher
from django.utils import timezone
from datetime import timedelta
u=Profile.objects.get(user__username='tester').user;u.profile.role='owner';u.profile.save()
for id,data in [('raw',{'name':'Сировина з довгою українською назвою','unit':'кг'}),('output',{'name':'Готовий кекс контрольний','unit':'шт','recipe':[{'product':'raw','quantity':'2'}]})]:
 Document.objects.create(path='products/'+id,data=data)
s=Store.objects.first();w=Warehouse.objects.filter(store=s).first();p=Counterparty.objects.create(name='Контрольний постачальник',kind='supplier')
v=save_voucher(u,{'kind':'receipt','store':s.pk,'warehouse':w.pk,'party':p.pk,'date':timezone.localdate().isoformat(),'lines':[{'product':'raw','quantity':'30','price':'2','expiry':(timezone.localdate()+timedelta(days=4)).isoformat()}]});post_voucher(u,v.pk)`);
const dialog=(target=page)=>target.locator('.trade-dialog[open]');
const response=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
async function go(target=page){await target.goto(base+'/#trade/stock');await target.locator('[data-trade=recipe-version]').waitFor();}
async function open(target=page,id){await target.locator('[data-trade=recipe-version]').click();await dialog(target).locator('[name=product]').waitFor();if(id)await choose(target,id);}
async function choose(target,id){await dialog(target).locator('[name=product]').selectOption(id);await wait(async()=>await dialog(target).locator('[name=product]').isEnabled()&&await dialog(target).locator('[type=submit]').isEnabled(),'recipe ready '+id);}
async function close(target=page,dirty=false){if(dirty&&await dialog(target).getAttribute('data-dirty')==='1')target.once('dialog',native=>native.accept());await target.keyboard.press('Escape');await dialog(target).waitFor({state:'hidden'});}
async function error(text,target=page){await dialog(target).locator('#tradeFormError').filter({hasText:text}).waitFor();assert(await dialog(target).locator('#tradeFormError').evaluate(el=>el===document.activeElement),'error focused');}
async function api(target,method,endpoint,value){return target.evaluate(async({method,endpoint,value})=>{const s=await(await fetch('/api/state')).json();const r=await fetch(endpoint,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},...(value===undefined?{}:{body:JSON.stringify(value)})});return {status:r.status,body:await r.json()};},{method,endpoint,value});}
async function screenshot(name,target=page,cdp=false){const filename=path.join(output,name);if(cdp){const session=await zoomContext.newCDPSession(target),shot=await session.send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(filename,Buffer.from(shot.data,'base64'));await session.detach();}else await target.screenshot({path:filename});screenshots.push(filename);}
(async()=>{
 await wait(async()=>{try{return(await fetch(base+'/health')).ok;}catch{return false;}},'server');fixtures();browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await require('./browser-login.cjs')(page,base,password);await go();
 await open(page,'output');await dialog().locator('[name=outputQuantity]').fill('10');await dialog().locator('[data-component=quantity]').fill('20');await dialog().locator('[name=expiryPolicy]').selectOption('minimum_with_shelf_life');await dialog().locator('[name=shelfLifeDays]').fill('2');await dialog().locator('[name=reason]').fill('Технологічний норматив');
 // One actual POST commits then loses its response; changed new text survives exact retry.
 let lost=true,keys=[];await page.route('**/api/erp/recipes/versions',async route=>{if(route.request().method()!=='POST')return route.continue();keys.push(route.request().postDataJSON().idempotencyKey);if(lost){lost=false;await route.fetch();return route.abort();}return route.continue();});
 await dialog().locator('[type=submit]').click();await error('З’єднання перервано');await dialog().locator('[name=reason]').fill('Нове обґрунтування');await dialog().locator('[type=submit]').click();await error('Первісну версію затверджено');assert.equal(keys[0],keys[1]);assert.equal(await dialog().locator('[name=reason]').inputValue(),'Нове обґрунтування');assert.equal((await api(page,'GET','/api/erp/recipes/versions?product=output')).body.total,1);await close(page,true);await page.unroute('**/api/erp/recipes/versions');
 results.push('Confirmed server create with lost HTTP response: same key exact retry, one version, changed text retained: PASS');
 await page.locator('[data-trade=new-voucher][data-kind=production]').click();await dialog().locator('[data-line=product]').selectOption('output');await dialog().locator('[name=productionVersion]').waitFor();await dialog().locator('[data-line=quantity]').fill('8');await dialog().locator('[name=varianceReason]').fill('Втрати під час випікання');await dialog().locator('[data-fact=quantity]').fill('21');
 // An actual failed GET pauses posting without clearing the visible actual quantities or reason.
 await page.route('**/api/erp/recipes/versions?*',route=>response(route,{error:'Контрольне читання недоступне'},503));await dialog().locator('[data-production=retry]').click();await error('Контрольне читання недоступне');assert.equal(await dialog().locator('[data-fact=quantity]').inputValue(),'21');assert.equal(await dialog().locator('[name=varianceReason]').inputValue(),'Втрати під час випікання');await dialog().locator('[value=post]').click();await error('Дочекайтеся актуальних');
 await page.unroute('**/api/erp/recipes/versions?*');await dialog().locator('[data-production=retry]').focus();await page.keyboard.press('Enter');await wait(async()=>!(await dialog().locator('.trade-production').getAttribute('aria-busy')),'retry');assert.equal(await dialog().locator('[data-fact=quantity]').inputValue(),'21');
 await page.setViewportSize({width:320,height:1000});await dialog().locator('[name=varianceReason]').focus();const geometry=await dialog().evaluate(d=>({fits:d.scrollWidth<=d.clientWidth+1,viewport:innerWidth,left:d.getBoundingClientRect().left,right:d.getBoundingClientRect().right,controls:[...d.querySelectorAll('button,input,select')].filter(el=>el.type!=='hidden'&&el.getBoundingClientRect().height>0).map(el=>({label:el.name||el.textContent,width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height}))}));assert(geometry.fits&&geometry.left>=-1&&geometry.right<=geometry.viewport+1,'production dialog fits320');for(const c of geometry.controls)assert(c.width>=44&&c.height>=44,'44px '+c.label);await screenshot('tsukenya-production-320.png');
 await dialog().locator('[value=post]').focus();await page.keyboard.press('Enter');await dialog().getByText('Виробничі умови документа',{exact:true}).waitFor();assert.match(await dialog().innerText(),/Недовипуск/);assert.match(await dialog().innerText(),/42.00/);
 const documents=fixture("from server.erp.models import Voucher,StockLot,AuditEvent\nimport json\nv=Voucher.objects.get(kind='production');print(json.dumps({'status':v.status,'cost':str(v.cost),'expiry':v.lines.get().expiry.isoformat(),'expected':(v.date+__import__('datetime').timedelta(days=2)).isoformat(),'raw':str(StockLot.objects.get(product_id='products/raw').quantity),'posts':AuditEvent.objects.filter(action='production_posted').count()}))");const check=JSON.parse(documents.toString());assert.equal(check.status,'posted');assert.equal(check.cost,'42.00');assert.equal(check.raw,'9.000');assert.equal(check.expiry,check.expected);assert.equal(check.posts,1);assert.deepEqual(errors,[]);
 results.push('Production immutable version, planned10/actual8/raw21, read503 pause and keyboard retry preserve draft, post42actualCOGS expirydate+2, readonly result and320touch targets: PASS');console.log(JSON.stringify({results,screenshots,check},null,2));
})().catch(async error=>{if(page)await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});console.error(error);process.exitCode=1;}).finally(async()=>{await browser?.close();if(server.exitCode===null){server.kill('SIGTERM');await new Promise(resolve=>{const timer=setTimeout(resolve,3000);server.once('exit',()=>{clearTimeout(timer);resolve();});});}if(process.exitCode)fs.copyFileSync(path.join(data,'server.log'),path.join(output,'server.log'));fs.rmSync(data,{recursive:true,force:true});});
