/* Recipe UX against its own local Django/SQLite; no remote database or Google writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,execFileSync}=require('node:child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),python=process.env.PYTHON_BIN||'python3',port='18224',base=`http://localhost:${port}`,password='isolated-recipes-password';
const from=process.env.QA_RECIPES_FROM||'all';assert(['all','tail','validation','conflict','read','layout','zoom'].includes(from),'Unknown QA_RECIPES_FROM');
const data=fs.mkdtempSync(path.join(os.tmpdir(),'tsukenya-recipes-db-')),output=process.env.QA_OUTPUT_DIR||path.join(os.tmpdir(),'tsukenya-recipes-qa');fs.mkdirSync(output,{recursive:true});
const hash=execFileSync(python,['-c',`from server.auth import hash_password;print(hash_password('${password}'))`],{cwd:root,encoding:'utf8'}).trim();
const env={...process.env,PORT:port,HOST:'127.0.0.1',DATA_DIR:data,ERP_DB_PATH:path.join(data,'crm.sqlite3'),OWNER_USERNAME:'tester',OWNER_PASSWORD_HASH:hash};
for(const key of ['DATABASE_URL','DB_HOST','DB_PORT','DB_NAME','DB_USER','DB_PASSWORD'])delete env[key];
const log=fs.openSync(path.join(data,'server.log'),'a'),server=spawn(python,['-m','server.main'],{cwd:root,env,stdio:['ignore',log,log]});fs.closeSync(log);
let browser,page,zoomContext,zoomProfile;const results=[],screenshots=[],errors=[];let posts=0;
const wait=async(fn,label)=>{for(let i=0;i<120;i++){if(await fn())return;if(server.exitCode!==null)throw Error('Server exited: '+fs.readFileSync(path.join(data,'server.log'),'utf8').slice(-2000));await new Promise(r=>setTimeout(r,100));}throw Error(`Timeout: ${label}`);};
const fixture=source=>execFileSync(python,['-c',`import os\nos.environ.setdefault('DJANGO_SETTINGS_MODULE','server.settings')\nimport django;django.setup()\n${source}`],{cwd:root,env});
const fixtures=()=>fixture(`from server.erp.models import Document,Profile
Profile.objects.filter(user__username='tester').update(role='owner')
for id,data in [('recipe_flour',{'name':'Борошно контрольне','unit':'кг'}),('recipe_milk',{'name':'Молоко контрольне','unit':'л'}),('recipe_a',{'name':'Готовий A','unit':'шт','recipe':[{'product':'recipe_flour','quantity':'1'}]}),('recipe_b',{'name':'Готовий B','unit':'шт','recipe':[{'product':'recipe_milk','quantity':'2'}]})]:
 Document.objects.update_or_create(path='products/'+id,defaults={'data':data})`);
const dialog=(target=page)=>target.locator('.trade-dialog[open]');
const response=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
async function go(target=page){await target.goto(base+'/#trade/stock');await target.locator('[data-trade=recipe]').waitFor();}
async function open(target=page,id){await target.locator('[data-trade=recipe]').click();await dialog(target).locator('[name=product]').waitFor();if(id)await choose(target,id);}
async function choose(target,id){await dialog(target).locator('[name=product]').selectOption(id);await wait(async()=>await dialog(target).locator('[name=product]').isEnabled()&&await dialog(target).locator('[type=submit]').isEnabled(),'recipe ready '+id);}
async function close(target=page,dirty=false){if(dirty&&await dialog(target).getAttribute('data-dirty')==='1')target.once('dialog',native=>native.accept());await target.keyboard.press('Escape');await dialog(target).waitFor({state:'hidden'});}
async function error(text,target=page){await dialog(target).locator('#tradeFormError').filter({hasText:text}).waitFor();assert(await dialog(target).locator('#tradeFormError').evaluate(el=>el===document.activeElement),'error focused');}
async function api(target,method,endpoint,value){return target.evaluate(async({method,endpoint,value})=>{const s=await(await fetch('/api/state')).json();const r=await fetch(endpoint,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},...(value===undefined?{}:{body:JSON.stringify(value)})});return {status:r.status,body:await r.json()};},{method,endpoint,value});}
async function screenshot(name,target=page,cdp=false){const filename=path.join(output,name);if(cdp){const session=await zoomContext.newCDPSession(target),shot=await session.send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(filename,Buffer.from(shot.data,'base64'));await session.detach();}else await target.screenshot({path:filename});screenshots.push(filename);}
async function validation(){
 fixture("from server.erp.models import Document\nDocument.objects.filter(path__startswith='products/').delete()");await page.reload();await page.locator('[data-trade=recipe]').waitFor();await open();
 assert.match(await dialog().innerText(),/У каталозі немає товарів/);assert(await dialog().locator('[name=product]').isDisabled());assert(await dialog().locator('[data-trade=add-recipe]').isDisabled());assert(await dialog().locator('[type=submit]').isDisabled());await close();
 fixtures();await page.reload();await page.locator('[data-trade=recipe]').waitFor();await open(page,'recipe_a');
 assert.equal(await dialog().locator('[data-recipe=product] option[value=recipe_a]').count(),0,'finished product excluded');
 await dialog().locator('[data-trade=add-recipe]').click();assert(await dialog().locator('[data-recipe=product]').last().evaluate(el=>el===document.activeElement),'new ingredient focused');
 assert.equal(await dialog().locator('[data-recipe=product]').last().locator('option[value=recipe_flour]').evaluate(el=>el.disabled),true,'duplicate ingredient unavailable');
 const before=posts;await dialog().locator('[data-recipe=product]').last().evaluate(el=>{el.value='recipe_flour';el.dispatchEvent(new Event('change',{bubbles:true}));});await dialog().locator('[data-recipe=quantity]').last().fill('1');await dialog().locator('[type=submit]').click();await error('Інгредієнт не може повторюватись');assert.equal(posts,before);
 await dialog().locator('[data-recipe=product]').last().selectOption('recipe_milk');const qty=dialog().locator('[data-recipe=quantity]').last();
 for(const value of ['0','0.0001','']){await qty.fill(value);await dialog().locator('[type=submit]').click();await error('Кількість інгредієнта:');assert.equal(posts,before);assert.equal(await qty.inputValue(),value);}
 await qty.fill('0.5');await dialog().locator('[data-trade=remove-recipe]').last().click();assert.equal(await dialog().locator('[data-recipe=product]').evaluate(el=>el===document.activeElement),true,'remove returns focus to adjacent ingredient');
 // A real server 400 after the ingredient disappears retains the draft and allows repair.
 fixture("from server.erp.models import Document\nDocument.objects.filter(pk='products/recipe_flour').delete()");await dialog().locator('[data-recipe=quantity]').fill('3');
 const bad=page.waitForResponse(r=>r.url().endsWith('/api/erp/recipes')&&r.request().method()==='POST');await dialog().locator('[type=submit]').click();assert.equal((await bad).status(),400);await error('Інгредієнт');assert.equal(await dialog().locator('[data-recipe=quantity]').inputValue(),'3');assert(await dialog().locator('[type=submit]').isEnabled());
 await dialog().locator('[data-recipe=product]').selectOption('recipe_milk');const saved=page.waitForResponse(r=>r.url().endsWith('/api/erp/recipes')&&r.request().method()==='POST');await dialog().locator('[type=submit]').click();assert.equal((await saved).status(),200);await dialog().waitFor({state:'hidden'});
 assert.deepEqual((await api(page,'GET','/api/erp/recipes?product=recipe_a')).body.recipe,[{product:'recipe_milk',quantity:'3'}]);
 // Empty recipes remain an explicit supported clear operation, with confirmation.
 await open(page,'recipe_a');await dialog().locator('[data-trade=remove-recipe]').click();assert.match(await dialog().innerText(),/Рецептура порожня/);let prompt='';page.once('dialog',async native=>{prompt=native.message();await native.dismiss();});const count=posts;await dialog().locator('[type=submit]').click();assert.match(prompt,/порожню рецептуру/);assert.equal(posts,count);assert(await dialog().isVisible());
 page.once('dialog',native=>native.accept());await dialog().locator('[type=submit]').click();await dialog().waitFor({state:'hidden'});assert.deepEqual((await api(page,'GET','/api/erp/recipes?product=recipe_a')).body.recipe,[]);
 // Preserve an unavailable ingredient ID rather than silently replacing it with blank.
 fixture("from server.erp.models import Document\np=Document.objects.get(pk='products/recipe_a');p.data['recipe']=[{'product':'missing_ingredient','quantity':'1'}];p.save()");await open(page,'recipe_a');assert.equal(await dialog().locator('[data-recipe=product]').inputValue(),'missing_ingredient');assert.match(await dialog().locator('[data-recipe=product]').innerText(),/Недоступний інгредієнт/);await dialog().locator('[type=submit]').click();await error('Інгредієнт недоступний');await close(page,true);
 fixture("from server.erp.models import Document\np=Document.objects.get(pk='products/recipe_a');p.data['recipe']=[{'product':'recipe_a','quantity':'1'}];p.save()");await open(page,'recipe_a');assert.equal(await dialog().locator('[data-recipe=product]').inputValue(),'recipe_a','legacy self ID remains explicit');await dialog().locator('[type=submit]').click();await error('Готовий товар не може бути власним інгредієнтом');await close(page,true);
 results.push('Empty catalogue; self/duplicate exclusions; explicit client quantities; real missing ingredient400 retains draft; successful repair; explicit empty clear; missing legacy ID preserved: PASS');
}
async function conflict(){
 fixtures();await page.reload();await page.locator('[data-trade=recipe]').waitFor();const second=await page.context().newPage();second.setDefaultTimeout(12000);second.on('pageerror',e=>errors.push(e.message));await go(second);
 await open(page,'recipe_a');await open(second,'recipe_a');await dialog().locator('[data-recipe=quantity]').fill('3');await dialog(second).locator('[data-recipe=quantity]').fill('4');
 await dialog().locator('[type=submit]').click();await dialog().waitFor({state:'hidden'});const stale=second.waitForResponse(r=>r.url().endsWith('/api/erp/recipes')&&r.request().method()==='POST');await dialog(second).locator('[type=submit]').click();assert.equal((await stale).status(),409);await error('Товар уже змінено',second);assert.equal(await dialog(second).locator('[data-recipe=quantity]').inputValue(),'4');assert(await dialog(second).locator('[type=submit]').isDisabled());assert.deepEqual((await api(page,'GET','/api/erp/recipes?product=recipe_a')).body.recipe,[{product:'recipe_flour',quantity:'3'}]);
 second.once('dialog',native=>native.dismiss());await dialog(second).locator('[data-recipe-reload]').click();assert.equal(await dialog(second).locator('[data-recipe=quantity]').inputValue(),'4');
 second.once('dialog',native=>native.accept());await dialog(second).locator('[data-recipe-reload]').click();await wait(async()=>await dialog(second).locator('[type=submit]').isEnabled(),'conflict explicit reload');assert.equal(await dialog(second).locator('[data-recipe=quantity]').inputValue(),'3');assert(await dialog(second).locator('[data-recipe=product]').evaluate(el=>el===document.activeElement));
 await dialog(second).locator('[data-recipe=quantity]').fill('5');await dialog(second).locator('[type=submit]').click();await dialog(second).waitFor({state:'hidden'});assert.deepEqual((await api(page,'GET','/api/erp/recipes?product=recipe_a')).body.recipe,[{product:'recipe_flour',quantity:'5'}]);await second.close();
 results.push('Two actual editors: stale save409 retains draft; declined reload preserves4; accepted reload sees3; retry saves5 without overwrite: PASS');
}
async function reads(){
 fixtures();await page.reload();await page.locator('[data-trade=recipe]').waitFor();await open();
 await page.route('**/api/erp/recipes?*',route=>response(route,{error:'Не вдалося прочитати контрольну рецептуру'},503));await dialog().locator('[name=product]').selectOption('recipe_a');await error('Не вдалося прочитати');assert(await dialog().locator('[type=submit]').isDisabled());assert.equal(await dialog().locator('.trade-payment-row').count(),0);await page.unroute('**/api/erp/recipes?*');await dialog().locator('[data-recipe-reload]').click();await wait(async()=>await dialog().locator('[type=submit]').isEnabled(),'read retry');await close();
 // Real permission failure after the editor was opened never offers an empty save.
 await open();fixture("from server.erp.models import Profile\nProfile.objects.filter(user__username='tester').update(role='cashier')");await dialog().locator('[name=product]').selectOption('recipe_a');await error('Недостатньо прав');assert(await dialog().locator('[type=submit]').isDisabled());fixture("from server.erp.models import Profile\nProfile.objects.filter(user__username='tester').update(role='owner')");await dialog().locator('[data-recipe-reload]').click();await wait(async()=>await dialog().locator('[type=submit]').isEnabled(),'permission restored read');await close();
 await open();fixture("from server.erp.models import Document\nDocument.objects.filter(pk='products/recipe_b').delete()");await dialog().locator('[name=product]').selectOption('recipe_b');await error('Готовий товар');assert(await dialog().locator('[type=submit]').isDisabled());assert.equal(await dialog().locator('.trade-payment-row').count(),0);await close();fixtures();
 // Held GET is explicitly aborted on close; late failure cannot touch another editor/route.
 let release,finished,seen=false;const gate=new Promise(r=>release=r),done=new Promise(r=>finished=r);await page.route('**/api/erp/recipes?*',async route=>{seen=true;await gate;await response(route,{error:'Стара помилка рецептури'},503).catch(()=>{});finished();});await open();await dialog().locator('[name=product]').selectOption('recipe_a');await wait(async()=>seen,'held recipe read');assert(await dialog().locator('[type=submit]').isDisabled());const aborted=page.waitForEvent('requestfailed',{predicate:r=>r.url().includes('/api/erp/recipes?')});await close();await aborted;await page.goto(base+'/#trade/customers');await page.locator('[name=partySearch]').waitFor();release();await done;await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.locator('#main').getByText('Стара помилка рецептури',{exact:true}).count(),0);await page.unroute('**/api/erp/recipes?*');
 // Successful recipe POST followed by failed state GET reports the confirmed write; retry reads only.
 await go();await open(page,'recipe_a');await dialog().locator('[data-recipe=quantity]').fill('6');let reads=0;await page.route('**/api/erp/state',route=>{reads++;return reads===1?response(route,{error:'Контрольне оновлення недоступне'},503):route.continue();});const before=posts;await dialog().locator('[type=submit]').click();await page.locator('[data-saved-refresh] [role=alert]').filter({hasText:'збережено'}).waitFor();assert.equal(await dialog().count(),0);assert.equal(posts,before+1);await page.locator('[data-trade=refresh-saved]').focus();await page.keyboard.press('Enter');await page.locator('[data-saved-refresh] [role=status]').filter({hasText:'Список оновлено'}).waitFor();assert.equal(posts,before+1,'read retry never repeats recipe POST');await page.unroute('**/api/erp/state');assert.equal((await api(page,'GET','/api/erp/recipes?product=recipe_a')).body.recipe[0].quantity,'6');
 results.push('Failed fresh503/real403/real404 disable save; GET cancel+late route isolation; real save200+read503 reports confirmed success and GET-only retry: PASS');
}
async function geometry(target,width,label,cdp=false){
 if(width)await target.setViewportSize({width,height:1000});await open(target,'recipe_a');await dialog(target).locator('[data-recipe=quantity]').fill('0');await dialog(target).locator('[type=submit]').click();await error('Кількість інгредієнта:',target);
 const layout=await dialog(target).evaluate(d=>({fits:d.scrollWidth<=d.clientWidth+1,left:d.getBoundingClientRect().left,right:d.getBoundingClientRect().right,viewport:innerWidth,top:d.getBoundingClientRect().top,bottom:d.getBoundingClientRect().bottom,errorTop:d.querySelector('#tradeFormError').getBoundingClientRect().top,errorBottom:d.querySelector('#tradeFormError').getBoundingClientRect().bottom,controls:[...d.querySelectorAll('button,input,select')].filter(el=>!el.hidden&&el.getBoundingClientRect().height>0).map(el=>({label:el.getAttribute('aria-label')||el.textContent||el.name,width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height})),focus:d.querySelector('#tradeFormError')===document.activeElement}));assert(layout.fits&&layout.left>=-1&&layout.right<=layout.viewport+1,'recipe dialog fits '+label);assert(layout.focus,'error focus '+label);assert(layout.errorTop-6>=layout.top&&layout.errorBottom+6<=layout.bottom,'complete error focus outline inside dialog '+label);for(const control of layout.controls)assert(control.width>=44&&control.height>=44,'44px '+label+' '+control.label);await screenshot(`tsukenya-recipes-${label}.png`,target,cdp);
 // Dirty close and route changes can both be declined without losing quantity.
 target.once('dialog',native=>native.dismiss());await target.keyboard.press('Escape');assert(await dialog(target).isVisible());assert.equal(await dialog(target).locator('[data-recipe=quantity]').inputValue(),'0');await close(target,true);
}
async function layouts(){
 fixtures();await page.reload();await page.locator('[data-trade=recipe]').waitFor();if(from!=='zoom')for(const width of [1440,390,320])await geometry(page,width,String(width));
 if(from!=='zoom'){await page.setViewportSize({width:1440,height:1000});await open(page,'recipe_a');await dialog().locator('[data-recipe=quantity]').fill('7');page.once('dialog',native=>native.dismiss());await page.evaluate(()=>{location.hash='#trade/customers';});await wait(async()=>page.url().endsWith('#trade/stock'),'dirty route restored');assert.equal(await dialog().locator('[data-recipe=quantity]').inputValue(),'7');await close(page,true);}
 if(process.platform==='darwin'){
  zoomProfile=fs.mkdtempSync(path.join(os.tmpdir(),'tsukenya-recipes-zoom-'));fs.mkdirSync(path.join(zoomProfile,'Default'));fs.writeFileSync(path.join(zoomProfile,'Default','Preferences'),JSON.stringify({partition:{default_zoom_level:{x:Math.log(2)/Math.log(1.2)}}}));zoomContext=await chromium.launchPersistentContext(zoomProfile,{executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,viewport:null,args:['--window-size=1440,1000']});const zoom=zoomContext.pages()[0];zoom.setDefaultTimeout(12000);zoom.on('pageerror',e=>errors.push(e.message));await require('./browser-login.cjs')(zoom,base,password);assert.equal(await zoom.evaluate(()=>devicePixelRatio),2);assert.equal(await zoom.evaluate(()=>innerWidth),720);await go(zoom);await geometry(zoom,null,'zoom-200',true);await zoomContext.close();zoomContext=null;fs.rmSync(zoomProfile,{recursive:true,force:true});zoomProfile=null;
 }
 results.push(from==='zoom'?'Actual Chrome200% recipe error and complete focus outline visibility: PASS':'Recipe error/focus/44px layouts1440/390/320, dirty Escape+route preservation and actual Chrome200%: PASS');
}
(async()=>{
 await wait(async()=>{try{return(await fetch(base+'/health')).ok;}catch{return false;}},'server');fixtures();browser=await chromium.launch({headless:true,...(process.platform==='darwin'?{executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});const context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/api/erp/recipes')&&r.method()==='POST')posts++;});await require('./browser-login.cjs')(page,base,password);await go();
 if(['all','validation'].includes(from))await validation();if(['all','tail','conflict'].includes(from))await conflict();if(['all','tail','read'].includes(from))await reads();if(['all','tail','layout','zoom'].includes(from))await layouts();assert.deepEqual(errors,[],'browser runtime errors');const report={scope:from,results,screenshots};fs.writeFileSync(path.join(output,`results-${from}.json`),JSON.stringify(report,null,2));console.log('PASS:',JSON.stringify(report,null,2));
})().catch(async e=>{if(page)await page.screenshot({path:path.join(output,'tsukenya-recipes-failure.png'),fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1;}).finally(async()=>{if(zoomContext)await zoomContext.close();if(zoomProfile)fs.rmSync(zoomProfile,{recursive:true,force:true});await browser?.close();if(server.exitCode===null){server.kill('SIGTERM');await new Promise(resolve=>{const timer=setTimeout(resolve,3000);server.once('exit',()=>{clearTimeout(timer);resolve();});});}if(process.exitCode)fs.copyFileSync(path.join(data,'server.log'),path.join(output,'server.log'));fs.rmSync(data,{recursive:true,force:true});});
