import type { ABCFilters, ABCReportData } from './api';
import type { TradingApi } from '../trading/api';
export const fixtureFilters: ABCFilters = {
  from: '2026-09-01',
  to: '2026-09-30',
  store: '',
  aThreshold: '80',
  bThreshold: '95',
  q: '',
  class: '',
};
export function fixtureReport(filters = fixtureFilters): ABCReportData {
  return {
    contract: 'trading-abc-v1',
    from: filters.from,
    to: filters.to,
    store: filters.store ? Number(filters.store) : null,
    scopeName: 'Усі магазини',
    aThreshold: Number(filters.aThreshold).toFixed(2),
    bThreshold: Number(filters.bThreshold).toFixed(2),
    basis: 'net_revenue',
    reversalPolicy: 'kyiv_reversed_at',
    snapshot: 'current',
    snapshotNotice:
      'Кожне читання незалежне; нове проведення може змінити наступну сторінку або CSV.',
    generatedAt: '2026-10-01T08:00:00Z',
    tiePolicy: 'before_group',
    captionBasis: 'first_contributing_line',
    q: filters.q,
    class: filters.class,
    total: 1,
    page: 1,
    pages: 1,
    limit: 30,
    summary: {
      productCount: 1,
      positiveCount: 1,
      zeroCount: 0,
      negativeCount: 0,
      mixedUnitCount: 0,
      hiddenCount: 1,
      netRevenue: '90.00',
      positivePoolRevenue: '90.00',
      negativeRevenue: '0.00',
      netCogs: '50.00',
      grossProfit: '40.00',
      classes: {
        A: { count: 1, netRevenue: '90.00', share: '100.0000' },
        B: { count: 0, netRevenue: '0.00', share: '0.0000' },
        C: { count: 0, netRevenue: '0.00', share: '0.0000' },
        unclassified: { count: 0, netRevenue: '0.00', share: null },
      },
    },
    items: [
      {
        product: 'historical',
        name: 'Шоколад із фундуком — історичний товар',
        unit: 'шт',
        quantity: '2.000',
        unitConflicted: false,
        hiddenCurrent: true,
        netRevenue: '90.00',
        netCogs: '50.00',
        grossProfit: '40.00',
        classification: 'A',
        share: '100.0000',
        cumulativeBefore: '0.0000',
        cumulativeAfter: '100.0000',
      },
    ],
  };
}
export const fixtureDirectories: TradingApi = {
  bootstrap: async () => ({
    csrf: 'synthetic',
    role: 'owner',
    username: 'Власник',
    storeId: null,
    defaultStoreId: null,
    canViewAudit: true,
    closed_through: null,
    fiscal_required: false,
    max_discount: '10',
    defaultCategoryId: 'none',
  }),
  list: async (type) => ({
    type,
    items: [],
    total: 0,
    page: 1,
    pages: 1,
    limit: 30,
    q: '',
    sort: 'name',
    store: null,
    kind: '',
    active: '',
    purpose: 'filter',
  }),
  details: async () => ({ items: [], unavailable: [] }),
  lookup: async () => {
    throw Error('Unused synthetic lookup');
  },
};
