/* Versioned compact-shell boundary. Network data is decoded before replacing cached state. */
(()=>{'use strict';
 const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),text=v=>typeof v==='string',int=v=>Number.isSafeInteger(v)&&v>=0,hash=v=>text(v)&&/^[a-f0-9]{64}$/.test(v),decimal=v=>text(v)&&/^-?\d+(?:\.\d+)?$/.test(v),date=v=>text(v)&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
 const roles=['owner','manager','cashier','warehouse','accountant'],domains=['products','references','tasks','ideas','expenses','settings/main','project/state'];
 const check=v=>{if(!v)throw Error('Сервер повернув некоректні дані порталу. Повторіть читання.');};
 function decodeSession(v){check(object(v)&&roles.includes(v.role)&&text(v.csrf)&&v.csrf.length>0);return v;}
 function decodeState(v){decodeSession(v);check(v.contract==='portal-metadata-v1'&&typeof v.networkOwner==='boolean'&&(!v.networkOwner||v.role==='owner')&&text(v.labelRevision)&&object(v.data));const keys=['tasks','ideas','expenses','settings/main','project/state'];check(Object.keys(v.data).length===keys.length&&keys.every(k=>Object.hasOwn(v.data,k)));for(const k of keys.slice(0,3)){check(Array.isArray(v.data[k]));check(v.data[k].every(item=>object(item)&&text(item.id)&&object(item.data)));}check(v.data.tasks.every(t=>object(t.permissions)&&typeof t.permissions.canEdit==='boolean'&&typeof t.permissions.canDelete==='boolean'));check(object(v.data['settings/main'])&&object(v.data['project/state']));if(v.stateVersions!==undefined)check(object(v.stateVersions)&&Object.keys(v.stateVersions).length===domains.length&&domains.every(d=>hash(v.stateVersions[d])));return v;}
 function decodeSummary(v,model=false,canFinance=model){check(object(v)&&['catalogCount','noPriceCount','stalePriceCount','exampleCount','allExampleCount'].every(k=>int(v[k]))&&v.noPriceCount+v.stalePriceCount<=v.catalogCount&&v.exampleCount<=v.allExampleCount&&date(v.generatedAt)&&(v.nextChangeAt===null||date(v.nextChangeAt))&&hash(v.revision)&&v.priceBasis==='legacy_product_promotion'&&v.staleBasis==='elapsed_24h_strict_greater');if(canFinance)check(decimal(v.plannedExpenses));else check(v.plannedExpenses===undefined);if(model)check(v.basis==='legacy_catalogue_equal_weight'&&decimal(v.fixed)&&decimal(v.variable)&&int(v.coverage)&&v.coverage<=v.catalogCount&&decimal(v.equalWeightMargin)&&(v.breakEvenRevenue===null||decimal(v.breakEvenRevenue))&&['ready','no_coverage','nonpositive_margin'].includes(v.reason)&&int(v.budgetStores)&&v.budgetStores>0&&decimal(v.marginPercent)&&['breakEvenDaily','breakEvenPerStore'].every(k=>v[k]===null||decimal(v[k])));return v;}
 function decodeSalesMargin(v){check(object(v)&&v.basis==='accounting_dates_30d_weighted'&&/^\d{4}-\d{2}-\d{2}$/.test(v.from)&&Number.isFinite(Date.parse(v.from))&&/^\d{4}-\d{2}-\d{2}$/.test(v.to)&&Number.isFinite(Date.parse(v.to))&&['revenue','gross','dailyRevenue','marginPercent'].every(k=>decimal(v[k]))&&['needDaily','gapDaily'].every(k=>v[k]===null||decimal(v[k]))&&['ready','no_sales','nonpositive_margin'].includes(v.reason));return v;}
 function decodeExamples(v){check(object(v)&&Array.isArray(v.items)&&v.items.length<=30&&int(v.total)&&int(v.page)&&v.page>0&&int(v.pages)&&v.pages>0&&v.page<=v.pages&&v.limit===30&&v.pages===Math.max(1,Math.ceil(v.total/30))&&v.items.length===Math.max(0,Math.min(30,v.total-(v.page-1)*30))&&v.items.every(p=>object(p)&&text(p.id)&&/^[A-Za-z0-9_-]{1,120}$/.test(p.id)&&text(p.name)&&typeof p.hidden==='boolean'&&hash(p.revision))&&new Set(v.items.map(p=>p.id)).size===v.items.length);return v;}
 function decodeCleanup(v,input){check(object(v)&&v.ok===true&&v.idempotencyKey===input.idempotencyKey&&Array.isArray(v.items)&&v.items.length===input.items.length&&v.items.every((p,i)=>object(p)&&p.id===input.items[i].id&&['deleted','rejected','conflicted'].includes(p.status)&&(p.status==='deleted'||text(p.error))));return v;}
 async function session(signal){const r=await fetch('/api/v1/session',{credentials:'same-origin',cache:'no-store',signal});if(!r.ok)throw Object.assign(Error('Не вдалося перевірити сеанс. Повторіть читання.'),{status:r.status});return decodeSession(await r.json());}
 async function get(path,decode,signal){const r=await fetch('/api/v1/portal/'+path,{credentials:'same-origin',cache:'no-store',signal});const v=await r.json();if(!r.ok)throw Object.assign(Error(text(v.error)?v.error:'Не вдалося прочитати дані порталу.'),{status:r.status});return decode(v);}
 async function cleanup(input,signal){const s=await session(signal),r=await fetch('/api/v1/portal/examples/delete',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:JSON.stringify(input),signal});const v=await r.json();if(!r.ok)throw Object.assign(Error(text(v.error)?v.error:'Не вдалося прибрати приклади.'),{status:r.status});return decodeCleanup(v,input);}
 // Display exact server decimals; never use binary floats for money text.
 const money=v=>{check(decimal(v));const negative=v.startsWith('-'),digits=v.replace(/^-/,'').split('.'),whole=new Intl.NumberFormat('uk-UA').format(BigInt(digits[0]));return (negative?'-':'')+whole+','+(digits[1]||'').padEnd(2,'0').slice(0,2);};
 const api={decodeSession,decodeState,decodeSummary,decodeSalesMargin,decodeExamples,decodeCleanup,session,get,cleanup,money};if(typeof window!=='undefined')window.PortalApi=api;if(typeof module!=='undefined')module.exports=api;
})();
