/* Versioned compact-shell boundary. Network data is decoded before replacing cached state. */
(()=>{'use strict';
 const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),text=v=>typeof v==='string',int=v=>Number.isSafeInteger(v)&&v>=0,hash=v=>text(v)&&/^[a-f0-9]{64}$/.test(v),decimal=v=>text(v)&&/^-?\d+(?:\.\d+)?$/.test(v),date=v=>text(v)&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
 const roles=['owner','manager','cashier','warehouse','accountant'],domains=['products','references','tasks','ideas','expenses','settings/main','project/state'];
 const check=v=>{if(!v)throw Error('Сервер повернув некоректні дані порталу. Повторіть читання.');};
 function decodeSession(v){check(object(v)&&roles.includes(v.role)&&text(v.csrf)&&v.csrf.length>0);return v;}
 function decodeState(v){decodeSession(v);check(v.contract==='portal-metadata-v1'&&typeof v.networkOwner==='boolean'&&(!v.networkOwner||v.role==='owner')&&text(v.labelRevision)&&object(v.data));const keys=['tasks','ideas','expenses','settings/main','project/state'];check(Object.keys(v.data).length===keys.length&&keys.every(k=>Object.hasOwn(v.data,k)));for(const k of keys.slice(0,3)){check(Array.isArray(v.data[k]));check(v.data[k].every(item=>object(item)&&text(item.id)&&object(item.data)));}check(v.data.tasks.every(t=>object(t.permissions)&&typeof t.permissions.canEdit==='boolean'&&typeof t.permissions.canDelete==='boolean'));check(object(v.data['settings/main'])&&object(v.data['project/state']));if(v.stateVersions!==undefined)check(object(v.stateVersions)&&Object.keys(v.stateVersions).length===domains.length&&domains.every(d=>hash(v.stateVersions[d])));return v;}
 function decodeMetadata(v){decodeSession(v);check(v.contract==='portal-metadata-v2'&&(v.scopeStore===null||int(v.scopeStore)&&v.scopeStore>0)&&typeof v.networkOwner==='boolean'&&(!v.networkOwner||v.role==='owner')&&text(v.labelRevision)&&object(v.data)&&Object.keys(v.data).length===2&&object(v.data['settings/main'])&&object(v.data['project/state']));if(v.stateVersions!==undefined)check(object(v.stateVersions)&&Object.keys(v.stateVersions).length===domains.length&&domains.every(d=>hash(v.stateVersions[d])));return v;}
 function decodeCollectionItem(v,collection){check(object(v)&&text(v.id)&&/^[A-Za-z0-9_-]{1,120}$/.test(v.id)&&text(v.revision)&&/^[a-f0-9]{32}$/.test(v.revision)&&object(v.data)&&object(v.permissions)&&typeof v.permissions.canEdit==='boolean'&&typeof v.permissions.canDelete==='boolean'&&typeof v.managed==='boolean'&&(v.initiative===null||text(v.initiative)&&/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(v.initiative)));if(collection==='expenses')check(decimal(v.data.amount));if(collection==='ideas')check(typeof v.hasDevelopmentTask==='boolean');return v;}
 function decodeCollection(v,collection,input={}){check(object(v)&&object(v.context)&&v.context.collection===collection&&roles.includes(v.context.role)&&(v.context.store===null||int(v.context.store)&&v.context.store>0)&&text(v.context.q)&&date(v.generatedAt)&&Array.isArray(v.items)&&int(v.total)&&int(v.page)&&v.page>0&&v.limit===30&&v.pages===Math.max(1,Math.ceil(v.total/30))&&v.page<=v.pages&&v.items.length===Math.max(0,Math.min(30,v.total-(v.page-1)*30)));for(const [k,val] of Object.entries(input))if(k!=='page')check(v.context[k]===String(val));v.items.forEach(item=>decodeCollectionItem(item,collection));check(new Set(v.items.map(item=>item.id)).size===v.items.length);return v;}
 function decodeCollectionSummary(v,section){check(object(v)&&v.section===section&&date(v.generatedAt)&&object(v.context)&&roles.includes(v.context.role)&&(v.context.store===null||int(v.context.store)&&v.context.store>0));if(section==='budget'){check(decimal(v.plannedTotal)&&object(v.totals)&&['fixed','variable'].every(k=>decimal(v.totals[k])&&int(v.counts?.[k]))&&object(v.byCategory)&&['Оренда','Комунальні','Логістика','Обслуговування','Маркетинг','Податки','Зарплата','Інше'].every(k=>decimal(v.byCategory[k])));}else{check(int(v.total)&&int(v.unfinished)&&int(v.unknownStatus)&&v.unfinished<=v.total&&object(v.statuses)&&['todo','doing','done'].every(k=>int(v.statuses[k]))&&object(v.stages)&&['1','2','3','4','unknown'].every(k=>int(v.stages[k]))&&int(v.activeConditions)&&Array.isArray(v.nearest)&&v.nearest.length<=5);v.nearest.forEach(item=>decodeCollectionItem(item,'tasks'));if(section==='development')check(object(v.reactions)&&['awaiting','yes','no'].every(k=>int(v.reactions[k])));}return v;}
 function decodeSummary(v,model=false,canFinance=model){check(object(v)&&['catalogCount','noPriceCount','stalePriceCount','exampleCount','allExampleCount'].every(k=>int(v[k]))&&v.noPriceCount+v.stalePriceCount<=v.catalogCount&&v.exampleCount<=v.allExampleCount&&date(v.generatedAt)&&(v.nextChangeAt===null||date(v.nextChangeAt))&&hash(v.revision)&&v.priceBasis==='legacy_product_promotion'&&v.staleBasis==='elapsed_24h_strict_greater');if(canFinance)check(decimal(v.plannedExpenses));else check(v.plannedExpenses===undefined);if(model)check(v.basis==='legacy_catalogue_equal_weight'&&decimal(v.fixed)&&decimal(v.variable)&&int(v.coverage)&&v.coverage<=v.catalogCount&&decimal(v.equalWeightMargin)&&(v.breakEvenRevenue===null||decimal(v.breakEvenRevenue))&&['ready','no_coverage','nonpositive_margin'].includes(v.reason)&&int(v.budgetStores)&&v.budgetStores>0&&decimal(v.marginPercent)&&['breakEvenDaily','breakEvenPerStore'].every(k=>v[k]===null||decimal(v[k])));return v;}
 function decodeSalesMargin(v){check(object(v)&&v.basis==='accounting_dates_30d_weighted'&&/^\d{4}-\d{2}-\d{2}$/.test(v.from)&&Number.isFinite(Date.parse(v.from))&&/^\d{4}-\d{2}-\d{2}$/.test(v.to)&&Number.isFinite(Date.parse(v.to))&&['revenue','gross','dailyRevenue','marginPercent'].every(k=>decimal(v[k]))&&['needDaily','gapDaily'].every(k=>v[k]===null||decimal(v[k]))&&['ready','no_sales','nonpositive_margin'].includes(v.reason));return v;}
 function decodeExamples(v){check(object(v)&&Array.isArray(v.items)&&v.items.length<=30&&int(v.total)&&int(v.page)&&v.page>0&&int(v.pages)&&v.pages>0&&v.page<=v.pages&&v.limit===30&&v.pages===Math.max(1,Math.ceil(v.total/30))&&v.items.length===Math.max(0,Math.min(30,v.total-(v.page-1)*30))&&v.items.every(p=>object(p)&&text(p.id)&&/^[A-Za-z0-9_-]{1,120}$/.test(p.id)&&text(p.name)&&typeof p.hidden==='boolean'&&hash(p.revision))&&new Set(v.items.map(p=>p.id)).size===v.items.length);return v;}
 function decodeCleanup(v,input){check(object(v)&&v.ok===true&&v.idempotencyKey===input.idempotencyKey&&Array.isArray(v.items)&&v.items.length===input.items.length&&v.items.every((p,i)=>object(p)&&p.id===input.items[i].id&&['deleted','rejected','conflicted'].includes(p.status)&&(p.status==='deleted'||text(p.error))));return v;}
 function decodeCreateAcknowledgement(v,collection,createKey,payload){
  check(object(v)&&v.ok===true&&v.collection===collection&&v.createKey===createKey&&text(v.id)&&/^[A-Za-z0-9_-]{1,120}$/.test(v.id)&&object(v.original));
  decodeCreateIdentity({collection,createKey,confirmed:true,id:v.id,state:'unchanged',original:v.original,current:v.original},collection,createKey);
  const fields=['title','name','status','dueDate','stage','text','reaction','group','category','amount','scope','store','ideaId','order','byOwner'];
  for(const key of Object.keys(payload)){check(fields.includes(key));const expected=payload[key],actual=v.original.data[key];if(key==='amount')check(typeof expected==='number'&&Number.isFinite(expected)&&decimal(actual)&&Number(actual)===expected);else check(actual===(key==='name'&&typeof expected==='string'?expected.trim():expected));}
  return v;
 }
 function decodeCreateIdentity(v,collection,createKey){
  check(object(v)&&['tasks','ideas','expenses'].includes(collection)&&v.collection===collection&&v.createKey===createKey&&typeof v.confirmed==='boolean');
  if(!v.confirmed){check(!('id' in v)&&!('state' in v)&&!('original' in v)&&!('current' in v));return v;}
  check(text(v.id)&&/^[A-Za-z0-9_-]{1,120}$/.test(v.id)&&['unchanged','changed','deleted'].includes(v.state)&&('original' in v)&&('current' in v));
  for(const key of ['original','current']){if(v[key]!==null){const r=v[key];check(object(r)&&r.collection===collection&&r.id===v.id&&text(r.revision)&&/^[a-f0-9]{32}$/.test(r.revision)&&object(r.data)&&object(r.permissions)&&typeof r.permissions.canEdit==='boolean'&&typeof r.permissions.canDelete==='boolean'&&typeof r.managed==='boolean'&&(r.initiative===null||text(r.initiative)&&/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(r.initiative)));
   const d=r.data,label=collection==='expenses'?d.name:d.title,allowed=collection==='expenses'?['name','group','amount','category','order','byOwner']:collection==='ideas'?['title','text','reaction','order','byOwner']:['title','status','dueDate','stage','scope','store','ideaId','order','byOwner'];check(Object.keys(d).every(k=>allowed.includes(k)));check(text(label)&&label.trim().length>0&&label.length<=250&&Object.values(d).every(x=>x===null||['string','boolean','number'].includes(typeof x)&&(!(typeof x==='number')||Number.isFinite(x))));
   if(collection==='expenses')check(['fixed','variable'].includes(d.group)&&text(d.amount)&&/^\d{1,8}(?:\.\d{1,2})?$/.test(d.amount)&&(d.category===undefined||d.category===null||['Оренда','Комунальні','Логістика','Обслуговування','Маркетинг','Податки','Зарплата','Інше'].includes(d.category)));
   if(collection==='tasks'){check(d.store===undefined||d.store===null||Number.isSafeInteger(d.store)&&d.store>0);check(d.scope===undefined||d.scope===null||['operations','development'].includes(d.scope));check(d.status===undefined||d.status===null||['todo','doing','done'].includes(d.status));if(d.scope!=='operations')check(d.stage===undefined||d.stage===null||Number.isInteger(d.stage)&&d.stage>=1&&d.stage<=4);if(d.dueDate!==undefined&&d.dueDate!==null)check(text(d.dueDate)&&/^\d{4}-\d{2}-\d{2}$/.test(d.dueDate)&&Number.isFinite(Date.parse(d.dueDate))&&new Date(d.dueDate).toISOString().slice(0,10)===d.dueDate);}
   if(collection==='ideas')check((d.text===undefined||d.text===null||text(d.text)&&d.text.length<=4000)&&(d.reaction===undefined||d.reaction===null||['yes','no'].includes(d.reaction)));
  }}
  check(v.state==='deleted'?v.current===null:v.current!==null);return v;
 }
 async function createIdentity(collection,createKey,signal){const q=new URLSearchParams({collection,createKey});return get('create-identity?'+q,v=>decodeCreateIdentity(v,collection,createKey),signal);}
 async function session(signal){const r=await fetch('/api/v1/session',{credentials:'same-origin',cache:'no-store',signal});if(!r.ok)throw Object.assign(Error('Не вдалося перевірити сеанс. Повторіть читання.'),{status:r.status});return decodeSession(await r.json());}
 async function get(path,decode,signal){const r=await fetch('/api/v1/portal/'+path,{credentials:'same-origin',cache:'no-store',signal});const v=await r.json();if(!r.ok)throw Object.assign(Error(text(v.error)?v.error:'Не вдалося прочитати дані порталу.'),{status:r.status,code:text(v.code)?v.code:undefined});return decode(v);}
 async function cleanup(input,signal){const s=await session(signal),r=await fetch('/api/v1/portal/examples/delete',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:JSON.stringify(input),signal});const v=await r.json();if(!r.ok)throw Object.assign(Error(text(v.error)?v.error:'Не вдалося прибрати приклади.'),{status:r.status});return decodeCleanup(v,input);}
 // Display exact server decimals; never use binary floats for money text.
 const money=v=>{check(decimal(v));const negative=v.startsWith('-'),digits=v.replace(/^-/,'').split('.'),whole=new Intl.NumberFormat('uk-UA').format(BigInt(digits[0]));return (negative?'-':'')+whole+','+(digits[1]||'').padEnd(2,'0').slice(0,2);};
 const api={decodeMetadata,decodeCollectionItem,decodeCollection,decodeCollectionSummary,decodeCreateAcknowledgement,decodeCreateIdentity,createIdentity,decodeSession,decodeState,decodeSummary,decodeSalesMargin,decodeExamples,decodeCleanup,session,get,cleanup,money};if(typeof window!=='undefined')window.PortalApi=api;if(typeof module!=='undefined')module.exports=api;
})();
