/* Live legacy recipes and create-only approved versions share the existing React comparison. */
(()=>{'use strict';
function open({mode,api,esc,field,input,num,select,modal,markDirty,busyDialog,formError,onSaved}){
 const legacy=mode==='legacy',a=window.NativeRecipeEditor;if(!a)throw Error('Редактор рецептур ще завантажується. Повторіть дію.');
 const id=legacy?'tradeRecipeForm':'recipeVersionForm',button=(label,action)=>`<button class="btn soft" type="button" data-recipe-action="${action}" ${legacy&&action==='add'?'data-trade="add-recipe"':legacy&&action==='remove'?'data-trade="remove-recipe"':''}>${label}</button>`;
 const d=modal(legacy?'Рецептура готового товару':'Затвердити нову версію рецептури',`<form id="${id}" data-directory-purpose="${legacy?'legacy_recipe':'recipe'}" novalidate><div class="trade-form-grid">${field('Готовий товар','<select name="product" required><option value="">Оберіть товар</option></select>','wide')}${legacy?'':field('Нормативний вихід',num('outputQuantity','1.000','0.001','required min="0.001"'))+field('Технологічна політика придатності',select('expiryPolicy',Object.entries(a.policies).map(([id,name])=>({id,name})),'unspecified',true))+field('Технологічний строк, календарних днів',num('shelfLifeDays','','1','min="1" max="3650" disabled'))+field('Причина нового затвердження',input('reason','','text','required maxlength="500"'),'wide')}</div><p class="trade-caption">${legacy?'Кількість сировини на одну одиницю готового товару. Збереження змінює лише поточну рецептуру картки; затверджені версії та збережені виробничі документи залишаються незмінними.':'Норматив на вказаний вихід. Кожне збереження створює незмінну версію. Придатність визначає явно вибрана технологічна політика.'}</p><p data-recipe-status role="status" aria-live="polite"></p><div data-recipe-rows id="tradeRecipeLines"></div><div class="trade-production-actions">${button('Додати інгредієнт','add')}${button('Повторити читання','read')}${button('Скасувати читання','cancel')}${button('Повторити початкове затвердження','exact')}</div><div data-recipe-comparison></div></form>`,`<button class="btn" type="submit" form="${id}">${legacy?'Зберегти':'Затвердити версію'}</button>`);
 const form=d.querySelector('form'),rows=d.querySelector('[data-recipe-rows]'),product=form.elements.product,save=d.querySelector('[type=submit]'),status=d.querySelector('[data-recipe-status]'),host=d.querySelector('[data-recipe-comparison]'),readButton=d.querySelector('[data-recipe-action=read]'),cancel=d.querySelector('[data-recipe-action=cancel]'),exact=d.querySelector('[data-recipe-action=exact]');
 let baseline=null,base=null,committed='',requested='',reading=false,busy=false,review=false,handle=null,controller=null,generation=0,intent=null,confirmedId=null,confirmedBody=null;
 const live=n=>d.open&&d.isConnected&&generation===n;
 const row=r=>`<div class="${legacy?'trade-payment-row':'trade-production-component'}">${field('Інгредієнт',`<select ${legacy?'data-recipe':'data-component'}="product" required><option value="">Оберіть інгредієнт</option>${r.product?`<option value="${esc(r.product)}" selected>Завантажуємо вибраний товар…</option>`:''}</select>`)}${field(legacy?'Кількість на 1 од.':'Кількість на нормативний вихід',`<input ${legacy?'data-recipe':'data-component'}="quantity" type="number" inputmode="decimal" min="0.001" step="0.001" value="${esc(r.quantity??'')}" required>`)}${button('×','remove').replace('<button ', '<button aria-label="Прибрати інгредієнт" ')}</div>`;
 const rowValues=()=>[...rows.children].map(r=>({product:r.querySelector('select').value,quantity:r.querySelector('[data-recipe=quantity],[data-component=quantity]').value}));
 const rawDraft=()=>({components:JSON.stringify(rowValues()),...legacy?{}:{outputQuantity:form.elements.outputQuantity.value,expiryPolicy:form.elements.expiryPolicy.value,shelfLifeDays:form.elements.expiryPolicy.value==='minimum_with_shelf_life'?Number(form.elements.shelfLifeDays.value):null,reason:form.elements.reason.value}});
 const capture=()=>a.validateDraft(rawDraft(),committed,legacy);
 const signature=()=>JSON.stringify(rawDraft());
 const canSave=()=>baseline&&(legacy?baseline.canEdit:baseline.canApprove);
 function controls(){const locked=busy||reading;form.querySelectorAll('input,select,textarea,button').forEach(e=>{if(!host.contains(e))e.disabled=locked;});product.disabled=locked||!!intent||!!confirmedId;save.disabled=locked||!committed||!canSave()||review||!!intent||!!confirmedId;readButton.hidden=!!intent||(!review&&!!baseline);readButton.disabled=busy||reading;readButton.textContent=baseline?'Порівняти з поточною версією':'Повторити читання';cancel.hidden=!reading;cancel.disabled=busy;exact.hidden=!intent;exact.disabled=busy||reading;form.querySelector('[data-recipe-action=add]').disabled=locked||!committed;if(!legacy)form.elements.shelfLifeDays.disabled=locked||form.elements.expiryPolicy.value!=='minimum_with_shelf_life';window.TradeDirectories.sync(form);}
 const fill=draft=>{rows.innerHTML=JSON.parse(draft.components).map(row).join('');if(!legacy)for(const key of ['outputQuantity','expiryPolicy','shelfLifeDays','reason'])form.elements[key].value=draft[key]??'';window.TradeDirectories.scan(d);};
 const stop=()=>{++generation;controller?.abort();controller=null;handle?.unmount();handle=null;host.replaceChildren();reading=false;controls();};
 const names=(latest,mine)=>Object.fromEntries([...JSON.parse(base.components),...JSON.parse(mine.components),...JSON.parse(a.projection(latest).components)].map(r=>[r.product,latest.items?.flatMap(x=>x.components).find(c=>c.product===r.product)?.name||window.TradeDirectories.get('products',r.product)?.name||r.product]));
 async function fetchCurrent(id,signal){const raw=await api(legacy?'recipes?'+new URLSearchParams({product:id}):'recipes/versions?'+new URLSearchParams({product:id}),'GET',undefined,signal);return legacy?a.decodeLegacy(raw,id):a.decodeList(raw,id);}
 async function read({initial=false}={}){
  if(busy||reading||intent)return;let mine;if(!initial)mine=rawDraft();
  const id=initial?requested:committed,n=++generation;controller?.abort();controller=new AbortController();reading=true;controls();status.textContent=confirmedId?'Перевіряємо первісний UUID та поточні умови без запису…':'Читаємо поточну рецептуру…';d.querySelector('#tradeFormError').textContent='';
  try{
   // Confirm the original UUID separately: a latest page is not proof of that create identity.
   if(confirmedId){const original=await api('recipes/versions/'+confirmedId,'GET',undefined,controller.signal);if(!live(n))return;a.confirmVersion(original,confirmedBody);}
   const latest=await fetchCurrent(id,controller.signal);if(!live(n))return;
   if(!(legacy?latest.canEdit:latest.canApprove))throw Error('Поточна роль не дозволяє збереження рецептури. Чернетка збережена.');
   if(baseline&&latest.product.unit!==baseline.product.unit)throw Error('Одиницю готового товару змінено. Чернетка збережена; автоматичне узгодження недоступне.');
   if(initial){baseline=latest;base=a.projection(latest);committed=id;product.value=id;requested=id;fill(base);review=false;confirmedId=null;d.dataset.dirty='';reading=false;status.textContent=legacy?'Поточну рецептуру завантажено.':'Поточні умови завантажено. Задайте причину нового затвердження.';controls();return;}
   try{mine=a.validateDraft(mine,id,legacy);}catch{throw Error('Поточні умови прочитано, але нове введення потребує виправлення. Запис і версія не підмінені; перевірте кількості та причину, потім повторіть порівняння.');}const server=a.projection(latest);status.textContent='Порівняння готове. Застосування оновить лише чернетку; збереження — окрема дія.';
   handle=window.NativeConflictComparison.mount(host,{base,mine,server,fields:a.recipeFields([base,mine,server],names(latest,mine),legacy),title:'Узгодити рецептуру',onCancel:()=>{if(live(n)){stop();status.textContent='Чернетка збережена.';readButton.focus();}},onApply:merged=>{if(!live(n))return;a.validateDraft(merged,id,legacy);stop();baseline=latest;base=server;confirmedId=null;confirmedBody=null;fill(merged);review=false;markDirty(d);controls();status.textContent='Узгоджено лише чернетку. Збережіть її окремим натисканням.';save.focus();}});controls();
  }catch(error){if(!live(n)||error.name==='AbortError')return;stop();review=!!baseline;product.value=committed;status.textContent='Поточні умови не підтверджено. Введення збережено.';formError(error,d);readButton.hidden=false;readButton.focus();}
 }
 async function write(exactRetry=false){
  if(busy||reading||review&&!exactRetry||!baseline||!canSave())return;let payload,key;
  try{if(exactRetry){if(!intent)return;payload=intent.body;key=intent.key;}else{if(intent||confirmedId)return;const draft=capture();if(!form.reportValidity())return;
   if(legacy&&JSON.parse(draft.components).length===0&&JSON.parse(base.components).length&&!confirm('Зберегти порожню поточну рецептуру?'))return;
   key=signature();payload=legacy?{product:committed,recipe:JSON.parse(draft.components),revision:baseline.revision}:{idempotencyKey:crypto.randomUUID(),product:committed,expectedVersion:baseline.latestVersion,catalogRevision:baseline.catalogRevision,outputQuantity:draft.outputQuantity,components:JSON.parse(draft.components),expiryPolicy:draft.expiryPolicy,shelfLifeDays:draft.shelfLifeDays,reason:draft.reason};if(!legacy)intent={body:structuredClone(payload),key};}
  }catch(error){formError(error,d);return;}
  busy=true;controls();const finish=busyDialog(d,legacy?'Збереження поточної рецептури…':'Затвердження незмінної версії…');if(!finish){busy=false;controls();return;}
  try{const raw=await api(legacy?'recipes':'recipes/versions','POST',payload);if(!d.open)return;
   if(legacy){if(!raw||raw.ok!==true||raw.product!==committed||typeof raw.revision!=='string'||!/^[a-f0-9]{64}$/.test(raw.revision))throw Error('Не вдалося підтвердити збереження поточної рецептури.');}
   else {const saved=a.confirmVersion(raw,payload);intent=null;if(signature()!==key){confirmedId=saved.id;confirmedBody=structuredClone(payload);review=true;status.textContent=`Первісну версію № ${saved.version} підтверджено. Нове введення збережено; прочитайте поточні умови, узгодьте й затвердьте окремо.`;readButton.textContent='Порівняти з поточною версією';return;}}
   d.dataset.dirty='';d.close();await onSaved();
  }catch(error){if(error.status>=400&&error.status<500){if(!legacy&&exactRetry&&intent){confirmedId=intent.body.idempotencyKey;confirmedBody=structuredClone(intent.body);review=true;}else review=error.status===409||error.status===403||error.status===428;intent=null;}else if(legacy)review=true;status.textContent=legacy?'Результат не підтверджено. Прочитайте поточний запис без повторного збереження.':intent?'Результат не підтверджено. Точний повтор використає первісні умови, незалежно від нового введення.':confirmedId?'Повтор відхилено. Результат первісного запиту ще потребує читання за його UUID; нове введення збережено.':'Чернетка збережена; прочитайте поточні умови.';formError(error,d);}
  finally{busy=false;finish();if(d.open)controls();}
 }
 product.addEventListener('change',()=>{if(product.value===committed)return;if(intent||confirmedId){product.value=committed;controls();return;}if(baseline&&d.dataset.dirty==='1'&&!confirm('Відкинути незбережені умови та вибрати інший готовий товар?')){product.value=committed;controls();return;}stop();requested=product.value;if(!requested){committed='';baseline=null;base=null;rows.replaceChildren();controls();return;}baseline=null;committed='';review=false;void read({initial:true});});
 form.addEventListener('change',event=>{if(!host.contains(event.target))controls();});
 form.addEventListener('click',event=>{const action=event.target.closest('[data-recipe-action]')?.dataset.recipeAction;if(!action)return;event.stopPropagation();if(action==='cancel'){stop();status.textContent='Читання скасовано. Чернетка збережена.';readButton.focus();}if(action==='read')void read({initial:!baseline});if(action==='exact')void write(true);if(action==='add'&&!busy&&!reading){rows.insertAdjacentHTML('beforeend',row({}));window.TradeDirectories.scan(d);window.TradeDirectories.focus(rows.lastElementChild.querySelector('select'));markDirty(d);}if(action==='remove'&&!busy&&!reading){event.target.closest(legacy?'.trade-payment-row':'.trade-production-component').remove();markDirty(d);window.TradeDirectories.focus(form.querySelector('[data-recipe-action=add]'));}});
 form.onsubmit=event=>{event.preventDefault();void write(false);};d.addEventListener('close',()=>stop(),{once:true});controls();return d;
}
window.TradeRecipeEditor={open};
})();
