import type { Product, ProductPage } from './api';
export const catalogProducts: Product[] = [
  {
    id: 'sample-1',
    revision: 'synthetic-1',
    name: 'Кава Американо',
    type: 'Напої',
    category: 'Кава',
    pack: 'Стакан',
    size: '200 мл',
    unit: 'шт',
    barcode: '',
    cost: '12.50',
    markup: '30',
    price: '35',
    regularPrice: '35.00',
    promotionPrice: '29.99',
    salePrice: '29.99',
    manualPrice: true,
    promotion: true,
    priceAt: '2026-10-01',
    minStock: '0',
  },
  {
    id: 'sample-2',
    revision: 'synthetic-2',
    name: 'Шоколад із фундуком та карамеллю в подарунковому пакуванні, обмежена серія',
    type: 'Цукерки',
    category: 'Шоколад',
    pack: 'Коробка',
    size: '300 г',
    unit: 'шт',
    barcode: '',
    cost: '105',
    markup: '30',
    price: null,
    regularPrice: '136.50',
    promotionPrice: null,
    salePrice: '136.50',
    manualPrice: false,
    promotion: false,
    priceAt: '',
    minStock: '5',
  },
  {
    id: 'sample-3',
    revision: 'synthetic-3',
    name: 'Новий товар без ціни',
    type: '',
    category: '',
    pack: '',
    size: '',
    unit: 'шт',
    barcode: '',
    cost: '0',
    markup: '30',
    price: null,
    regularPrice: '0.00',
    promotionPrice: null,
    salePrice: '0.00',
    manualPrice: false,
    promotion: false,
    priceAt: '',
    minStock: '0',
  },
];
export const catalogPage: ProductPage = {
  items: catalogProducts,
  total: 3,
  page: 1,
  pages: 1,
  limit: 20,
  facets: {
    type: ['Напої', 'Цукерки'],
    category: ['Кава', 'Шоколад'],
    pack: ['Стакан', 'Коробка'],
  },
  canEdit: true,
  defaultMarkup: '30',
};
